crates/core_arch/src/x86/avx.rs

These were not following the documented (albeit peculiar) semantics for the AVX intrinsics — the differences are around NaN and -0.0.
It was also causing suboptimal codegen, as LLVM needed to, for example, follow a `vminps` with `vcmpunordps` + `vblendvps` to implement the `llvm.minnum` semantics. (This is why I noticed it)
The text quoted inside the tests is from the architecture manual (volume 2B) https://software.intel.com/content/dam/develop/external/us/en/documents-tps/253667-sdm-vol-2b.pdf. Essentially the same text can be found on websites like https://www.felixcloutier.com/x86/minps.
Somewhat surprisingly (or, it's surprising we'd get it right in one place, wrong in the other), we got this right for SSE min/max, so no change needed there.

Avoid using simd_fmin/simd_fmax for AVX float min/max comparisons

---

crates/core_arch/src/macros.rs
crates/core_arch/src/wasm32/simd128.rs

Continuation of https://github.com/rust-lang/stdarch/pull/1160.
Looks like very recently, more users of `simd_shuffle` were added, and thus evaded my grepping for them previously... hopefully this is all of them now. :)

use simd_shuffle macros on wasm32

---

crates/core_arch/src/aarch64/neon/generated.rs
crates/stdarch-gen/neon.spec

FIXES #1156 
This PR serves as a supplement to #1147 
Although vmull_p64 is temporarily unavailable on Arm32 due to the llvm‘s unsupporting, we can still make it available on aarch64.

Add vmull_p64 and vmull_high_p64 for aarch64

---

crates/core_arch/src/lib.rs
crates/core_arch/src/macros.rs
crates/core_arch/src/x86/macros.rs
crates/core_arch/src/x86_64/macros.rs

Currently, `core_arch` uses `1 / (bool_expr as usize)` to generate a
post-monomorphization error when a condition is false. However, this
approach generates opaque error messages
('evaluation of constant value failed'), which could easily be mistaken
for an internal compiler error by users.
Using the `const_panic` feature, we can `panic!()` with a more
descriptive error message. Unfortunately, we cannot include any of the
actual values in our message, since `const` traits do not yet exist.
Helps with https://github.com/rust-lang/rust/issues/85155

Use `#![feature(const_panic)]` to produce better assertion errors

---

crates/core_arch/src/aarch64/neon/generated.rs
crates/core_arch/src/aarch64/neon/mod.rs
crates/core_arch/src/arm_shared/neon/generated.rs
crates/core_arch/src/x86/macros.rs
crates/core_arch/src/x86_64/macros.rs
crates/stdarch-gen/neon.spec

This PR revised the implementation of the d_s64 suffix neon instructions to be consistent with Clang

Modify the implementation of d_s64 suffix instructions

---

crates/core_arch/src/wasm32/simd128.rs
examples/hex.rs

Naming right now for wasm simd intrinsics takes the signededness of the
instruction into account, but some operations are the same regardless of
signededness, such as `i32x4_add`. This commit adds aliases for all of
these operations under unsigned names as well (such as `u32x4_add`)
which are just a `pub use` to rename the item as two names. The goal of
this is to assist in reading code (no need to switch back and forth
between `i` and `u`) as well as writing code (no need to always remember
which operations are the same for signed/unsigned but only available
under the signed names).

wasm: Add convenience aliases with unsigned names

---

crates/core_arch/src/wasm32/simd128.rs

This changes wasm simd intrisnics which deal with memory to match clang
where they all are emitted with an alignment of 1. This is expected to
not impact performance since wasm engines generally ignore alignment as
it's just a hint. Otherwise this can increase safety slightly when used
from Rust since if an unaligned pointer was previously passed in that
could result in UB on the LLVM side. This means that the intrinsics are
slighly more usable in more situations than before.
It's expected that if higher alignment is desired then programs will not
use these intrinsics but rather the component parts. For example instead
of `v128_load` you'd just load the pointer itself (and loading from a
pointer in Rust automatically assumes correct alignment). For
`v128_load64_splat` you'd do a load …

wasm: Lower alignment of all loads/stores

---

crates/core_arch/src/arm_shared/crypto.rs
crates/std_detect/src/detect/arch/aarch64.rs
crates/std_detect/src/detect/arch/arm.rs
crates/std_detect/src/detect/bit.rs
crates/std_detect/src/detect/os/aarch64.rs
crates/std_detect/src/detect/os/freebsd/aarch64.rs
crates/std_detect/src/detect/os/freebsd/auxvec.rs
crates/std_detect/src/detect/os/linux/aarch64.rs
crates/std_detect/src/detect/os/linux/arm.rs
crates/std_detect/src/detect/os/windows/aarch64.rs
crates/std_detect/tests/cpu-detection.rs

All features supported by auxv (see https://github.com/torvalds/linux/blob/master/arch/arm64/include/uapi/asm/hwcap.h) / cpuinfo (https://github.com/torvalds/linux/blob/master/arch/arm64/kernel/cpuinfo.c) and in LLVM 12 are added.
See `llvm-project/llvm/lib/Target/AArch64/AArch64.td` for the LLVM feature names and dependencies. We've done a few passes for silly cross-referencing mistakes ourselves so I'm reasonably confident in its accuracy.
I had a couple notes after working on this:
- Some features, though detection is easy, are still not added based on @Amanieu 's wording [here](https://github.com/rust-lang/stdarch/issues/993#issuecomment-772893003). Is it possible to add detection for a few of the remaining features but not add them to the allowed list in rustc? I don't see why users …

Update aarch64 linux feature detection

---

crates/core_arch/src/lib.rs
crates/core_arch/src/wasm32/simd128.rs

This updates all simd intrinsics to be safe to account for
rust-lang/rust#84988. In the spirit of more safety it also removes the
pervasive usage of `transmute` in the intrinsics in favor of more
targeted casts.

wasm: Mark most simd intrinsics as safe

---

crates/core_arch/src/x86/bt.rs
crates/core_arch/src/x86_64/bt.rs

Unfortunately, rust-lang/rust#86234 landed before rust-lang/rust#86233.

Fix the stabilized version for `simd_x86_bittest`

---

crates/core_arch/src/mod.rs

Implements the first part of the libs team decision given at https://github.com/rust-lang/rust/issues/84019#issuecomment-875880229 .
The first step is to define these items in stdarch. Once this PR is accepted, I have another patch prepared for the Rust repo that will simultaneously remove the definitions in libcore and bump the stdarch submodule.
cc @Amanieu

Move `asm!` and `global_asm!` to `core::arch`

---

crates/core_arch/src/wasm32/simd128.rs

Since most intrinsics are safe it likely makes sense to explicitly
document why there are a few intrinsics that are not safe. These
intrinsics are all unsafe for the same reason, which is that they're
dealing with a raw pointer that must be valid to load/store memory to.
Note that the are no alignment requirements on any of these intrinsics.

Document unsafety of wasm simd intrinsics

---

crates/core_arch/src/mod.rs

This reverts commit 9437b11cd4f42c5995eb41aa92ead877b9b7823a.
With some experimentation we've concluded that instead of forcing these macros to be defined in the stdarch repo, there are benefits to having it defined in a facade `arch` module inside of libcore itself.

Revert "Move `asm!` and `global_asm!` to `core::arch` (#1183)"

---

crates/assert-instr-macro/src/lib.rs
crates/core_arch/src/x86/sse2.rs

This ensures that results are consistent across windows/linux tests.

Force the use of sysv64 calling convention in x86_64 disassembly tests

---

crates/core_arch/src/lib.rs
crates/core_arch/src/wasm32/simd128.rs

Now that `transmute` can be flagged as `const`-stable this commit
updates the `f32x4` and `f64x2` constructors as `const`-stable as well.
This also additionally rewrites the other integer constructors in a more
readable fashion now that the general `v128()` method is `const`-stable.

Mark f32x4 and f64x2 as const-stable on wasm

---

crates/core_arch/src/aarch64/neon/generated.rs
crates/core_arch/src/arm_shared/crypto.rs
crates/core_arch/src/arm_shared/neon/generated.rs
crates/stdarch-gen/neon.spec
crates/stdarch-gen/src/main.rs

This PR removes all occurrences of the `crypto` feature for aarch64 to allow for its removal.
It's necessary to keep the feature for ARM platforms for now.

Clean up aarch64 crypto feature

---

ci/docker/wasm32-wasi/Dockerfile
crates/core_arch/src/wasm32/simd128.rs

Wasmtime now supports all of the simd proposal, so this commit
uncomments instruction assertions and tests, while also adding more
tests, for all wasm simd instructions. This means that all wasm simd
instructions should be tested and have running instruction assertions,
except for `i64x2.abs`, which will require an LLVM upgrade to LLVM 13.

Add tests for remaining wasm simd intrinsics

---

crates/core_arch/src/aarch64/neon/generated.rs
crates/core_arch/src/arm_shared/neon/generated.rs
crates/stdarch-gen/neon.spec
crates/stdarch-test/src/lib.rs

Those intrinsics have the correct semantics for the desired fcvtz instruction,
without any undefined behaviour. The previous simd_cast was undefined for
infinite and NaN which could cause issues.

Update arm vcvt intrinsics to use llvm.fpto(su)i.sat

---

README.md
crates/core_arch/Cargo.toml
crates/core_arch/README.md
crates/std_detect/Cargo.toml
crates/std_detect/README.md

They haven't been published in years. This removes the suggestion that the crates on crates.io are actively updated/maintained.

Remove references to the crates on crates.io.

---

crates/core_arch/src/wasm32/mod.rs

This intrinsic doesn't have any preconditions and is always safe to
call, so it can be safe.
This function is already stable, but dropping `unsafe` is a backwards
compatible change.
Note tha we already have a precedent for wasm intrinsics being safe --
wasm simd is safe.
It is relatively practically important to mark this safe --
wasm32::unreachable is directly useful in practice as more codesize
efficient `panic!()`.

mark core::arch::wasm32::unreachable as safe

---

crates/core_arch/src/wasm32/simd128.rs

- Use "true" and "false" instead of "1" and "0"
- "nonzero" -> "non-zero"
- "returns true if ... or false if ..." -> "returns true ..., false otherwise"
https://github.com/rust-lang/rust/issues/87684

Rewording in Wasm all_true SIMD instruction docs

---

crates/core_arch/src/x86/mod.rs

:wave: 
Everything in the title.

Typo fix: "it's purpose" -> "its purpose"

---

crates/core_arch/src/arm/ex.rs
crates/core_arch/src/x86/sse.rs
crates/std_detect/src/detect/arch/x86.rs

Fix typos “a”→“an”

---

.github/workflows/main.yml
crates/core_arch/src/lib.rs
crates/core_arch/src/wasm32/simd128.rs

Since LLVM 12 a number of simd wasm intrinsics have been updated to no
longer use custom intrinsics in LLVM but rather pattern-match other
types of IR. This commit updates our support in `std::arch` to use the
patterns the LLVM recognizes, removing usage of custom intrinsics where
possible.
Affected intrinsics are:
* `v128_load{32,64}_zero`
* `v128_load{8,16,32,64}_lane`
* `v128_store{8,16,32,64}_lane`
* `i8x16_popcnt`
* `f{32x4,64x2}_p{min,max}`
* `*_extmul_*`
Documentation around the load/store intrinsics have been updated to
indicate that the safe alternatives are suitable replacements.
Closes #1202

Update codegen for simd wasm intrinsics with LLVM 13

---

crates/core_arch/src/aarch64/neon/generated.rs
crates/core_arch/src/arm_shared/neon/generated.rs
crates/stdarch-gen/neon.spec
crates/stdarch-gen/src/main.rs
crates/stdarch-test/src/lib.rs

This PR adds vst1* neon instructions which store mutiple vectors as once.

Add vst neon instructions

---

.github/workflows/main.yml
crates/stdarch-test/src/disassembly.rs
crates/stdarch-test/src/lib.rs

Enabling target features is not possible with otool. Setting a target CPU is possible but the Transactional Memory Extension (TME) is not supported by any CPU yet so that does not help. LLVM objdump is installed with the developer tools out of the box and can be used instead.
Edit: Now uses LLVM objdump for x86_64 as well.

Use LLVM objdump on Macos instead of otool for CI tests

---

crates/assert-instr-macro/src/lib.rs
crates/stdarch-test/src/lib.rs

The dedup guard currently used in the `assert_instr` shims is sometimes compiled to function calls on arm, the new one should also prevent LLVM from merging functions and is never compiled to a function call.
First PR towards implementing inlining checks for arm (#1210).

Use a lighter dedup guard in the assert_instr test shims.

---

crates/core_arch/src/aarch64/neon/mod.rs

vld1* instructions are required to always compile to a single load instruction (see [ARM developer documentation](https://developer.arm.com/architectures/instruction-sets/intrinsics/)). The current implementation causes individual loads to be emitted in LLVM-IR which are not always combined to a single load instruction during LLVM optimization passes. This change causes a single load to be emitted in all cases.
cc @SparrowLii 
TODO:
Fixes #1148.

Change aarch64 vld1* instructions to not cause individual loads

---

crates/stdarch-test/src/disassembly.rs

This is a workaround for an LLVM objdump shortcoming. `uxtl`and `sxtl` are the preferred disassembly for `ushll` and `sshll` if the shift is zero as documented here:
* https://developer.arm.com/documentation/ddi0602/latest/SIMD-FP-Instructions/UXTL--UXTL2--Unsigned-extend-Long--an-alias-of-USHLL--USHLL2-
* https://developer.arm.com/documentation/ddi0602/latest/SIMD-FP-Instructions/SXTL--SXTL2--Signed-extend-Long--an-alias-of-SSHLL--SSHLL2-
This PR fixes some failing tests on Macos ARM64 (see #1206).

Normalize [us]shll.* ..., #0 aarch64 disassembly to the preferred [us]xtl.*

---

.gitignore
Cargo.toml
ci/docker/aarch64-unknown-linux-gnu/Dockerfile
ci/run-docker.sh
ci/run.sh
crates/intrinsic-test/Cargo.toml
crates/intrinsic-test/README.md
crates/intrinsic-test/neon-intrinsics.csv
crates/intrinsic-test/src/argument.rs
crates/intrinsic-test/src/intrinsic.rs
crates/intrinsic-test/src/main.rs
crates/intrinsic-test/src/types.rs
crates/intrinsic-test/src/values.rs

As mentioned in #1125 this is the start of a tool to compare the intrinsics between C and Rust. 
Some notable things:
* All NaN's are treated as equal. I do have a branch that prints them as hex if you would prefer though.
* Intrinsics with a `lane` or `n` argument are skipped due to constraints on the values.
I did notice that some of the intrinsics were marked as done in the tracking spreadsheet but didn't actually exist.
I have also noticed that a few vcvt intrinsics have differences, I haven't yet fully investigated that though.

Intrinsic test tool to compare neon intrinsics with C

---

crates/stdarch-test/src/lib.rs

We tell the test framework not to test for a specific instruction with `assert_instr(nop)`. But even then we should still check that the intrinsic is properly inlined and that the generated assembly does not exceed the specified instruction count.

Tests: check inlining and instruction count even if we don't check for a specific instruction

---

crates/core_arch/src/arm_shared/neon/generated.rs
crates/core_arch/src/arm_shared/neon/mod.rs
crates/stdarch-gen/neon.spec
crates/stdarch-gen/src/main.rs

This fixes muliple issues with 32-bit ARM Fused Multiply-Add intrinsics:
* FMA intrinsics require `vfp4`not `v8`
* Some FMA intrinsics are not inlined by LLVM because the `vdup_n_f32` and `vdupq_n_f32` instructions don't have the vfp4 feature enabled. Fixes #1212.
* ~~It enables the ARM inlining check for #1210.~~

Arm Fused Multiply-Add fixes

---

ci/run.sh
crates/assert-instr-macro/src/lib.rs
crates/core_arch/src/aarch64/neon/generated.rs
crates/core_arch/src/aarch64/neon/mod.rs
crates/core_arch/src/arm/neon.rs
crates/core_arch/src/arm_shared/neon/generated.rs
crates/core_arch/src/arm_shared/neon/mod.rs
crates/core_arch/src/x86/avx512bw.rs
crates/core_arch/src/x86_64/avx512f.rs
crates/std_detect/src/detect/os/linux/auxvec.rs
crates/stdarch-gen/neon.spec

The dedup guard creates additional instructions in the test shims which cause various problems with testing intrinsics such as inadvertedly checking for dedup guard instructions, not useful instructions counts and inadvertedly crossing the inlining threshold.
This PR disables the dedup guard if the environment variable `STDARCH_DISABLE_DEDUP_GUARD` is set. It only works properly if the LLVM MergeFunctions pass is disabled, e.g. with `-Z merge-functions=disabled`in `RUSTFLAGS`.
It also disables the dedup guard for the `ci/run.sh`
TODO:

Make dedup guard optional

---

crates/core_arch/src/aarch64/neon/generated.rs
crates/core_arch/src/aarch64/neon/mod.rs
crates/core_arch/src/arm/neon.rs
crates/core_arch/src/arm_shared/neon/generated.rs
crates/core_arch/src/arm_shared/neon/store_tests.rs
crates/stdarch-gen/neon.spec
crates/stdarch-gen/src/main.rs
crates/stdarch-test/src/lib.rs

This PR completes vst1 neon instructions and makes preparations to generate other vld*, vst* instructions.

Complete vst1 neon instructions

---

crates/core_arch/src/aarch64/neon/generated.rs
crates/core_arch/src/arm_shared/neon/generated.rs
crates/stdarch-gen/neon.spec
crates/stdarch-gen/src/main.rs
crates/stdarch-test/src/lib.rs

This PR completes vld* and vst* neon instructions
One commit will contain one type of them.

Complete vld* and vst* neon instructions

---

crates/core_arch/src/lib.rs
crates/core_arch/src/x86/sse41.rs

An explanation of how this intrinsic works was asked for in https://github.com/rust-lang/rust/issues/57225

Add example to _mm_extract_ps

---

crates/core_arch/src/mod.rs
crates/core_arch/src/wasm32/memory.rs

This follows the x86/x86_64 pattern where `wasm64` simply reexports the
`wasm32` module for now. The documentation is pretty lacking since this
is just the start as well.

Add a rudimentary `wasm64` module with intrinsics

---

crates/core_arch/src/mod.rs

I think it should be idiomatic to use `target_family = "wasm"` instead of `target_arch = "wasmNN"`, so we encourage the ecosystem to write code that works for both. This makes it easier to do that by exporting a `wasm` in addition to `wasm32` and `wasm64`.

expose `wasm` intrinsics using `target_family = "wasm"`

---

crates/core_arch/src/x86/sse41.rs

Came up during
https://github.com/rust-lang/rust/runs/4068713521?check_suite_focus=true

Fix parsing a doc block for `_mm_extract_ps`

---

crates/core_arch/src/mod.rs

Tracking issue: https://github.com/rust-lang/rust/issues/90599

Make the wasm and wasm64 modules unstable

---

crates/core_arch/src/x86/avx.rs

Both _mm256_set_epi8 and _mm256_setr_epi8 claim to set the 8-bit integers in reversed order.

Remove that _mm256_set_epi8 sets in reversed order.

---

crates/core_arch/src/mips/msa.rs

It looks like there was a mistake commenting out this function, which left an unused attribute. 
Unblocks https://github.com/rust-lang/rust/pull/88681 which is extending the unused_attributes lint to catch more situations.

Fix unused link_name attribute.

---

crates/core_arch/src/arm_shared/neon/mod.rs

The beta compiler (1.57) does not support the i8mm feature. This fixes a build failure by not enabling it when bootstrapping.

Fix i8mm feature with bootstrap compiler.

---

crates/std_detect/src/detect/os/x86.rs

Apparently on some chips, `cpuid` is not to be fully trusted. According to http://www.intel.com/content/dam/www/public/us/en/documents/specification-updates/desktop-6th-gen-core-family-spec-update.pdf, some Skylake chips (notably Celerons) will report support for BMI1 and BMI2 without actual support for those operations.
Quoting that document's Errata section:
> | SKL052 | CPUID Incorrectly Reports Bit Manipulation Instructions Support |
> | :-- | :-- |
> | Problem | Executing CPUID with EAX = 7 and ECX = 0 may return EBX with bits [3] and [8] set, incorrectly indicating the presence of BMI1 and BMI2 instruction set extensions. |
> | Implication | Attempting to use instructions from the BMI1 or BMI2 instruction set extensions will result in a #UD exception. |
> | Workaround | It is …

Work-around buggy Intel chips erroneously reporting BMI1/BMI2 support

---

crates/core_arch/src/x86/sse41.rs

The example fails when run with rustdoc since this crate denies warnings. The test has an unneeded `unsafe` block which triggers `unused_unsafe`.
This normally doesn't show up in CI since it requires testing with a `-C target-cpu` that has sse4.1.

Fix _mm_extract_ps example.

---

.github/workflows/main.yml
crates/core_arch/src/core_arch_docs.md
crates/core_arch/src/mod.rs
crates/core_arch/src/riscv/mod.rs

This pull request contains two parts: new RISC-V platform `core::arch` package, and a first platform specific instruction wrapper `pause()` function on RISC-V platform.
As is defined in RISC-V Unprivileged Specification version 20191214-draft (December 1, 2021, with Zihintpause 2.0 Ratified), the PAUSE instruction is defined as follows:
> Chapter 4
> 
> “Zihintpause” Pause Hint, Version 2.0
> 
> The PAUSE instruction is a HINT that indicates the current hart’s rate of instruction retirement
> should be temporarily reduced or paused. The duration of its effect must be bounded and may be
> zero. No architectural state is changed.
> 
> ...
> 
> PAUSE is encoded as a FENCE instruction with pred=W, succ=0, fm=0, rd=x0, and rs1=x0.
This instruction is useful when we need to implement …

Add RISC-V platform and PAUSE instruction

---

crates/simd-test-macro/src/lib.rs
crates/std_detect/src/detect/arch/riscv.rs
crates/std_detect/src/detect/error_macros.rs
crates/std_detect/src/detect/mod.rs
crates/std_detect/src/detect/os/linux/auxvec.rs
crates/std_detect/src/detect/os/linux/cpuinfo.rs
crates/std_detect/src/detect/os/linux/mod.rs
crates/std_detect/src/detect/os/linux/riscv.rs
crates/std_detect/src/lib.rs

This pull request includes:
- RISC-V platform feature and its detect maro
- Detect RISC-V instruction set features in Linux, using Auxvec ~~and /proc/cpuinfo~~. (edit: does not read from /proc/cpuinfo)
~~Marked as draft: these functions are yet to be verified on real Linux RISC-V machines.~~ edit: these function passed tests on RISC-V Linux machines

RISC-V feature and detect macro

---

.github/workflows/main.yml
ci/docker/riscv64gc-unknown-linux-gnu/Dockerfile
ci/run.sh
crates/core_arch/src/aarch64/armclang.rs
crates/core_arch/src/arm/armclang.rs
crates/core_arch/src/arm_shared/barrier/cp15.rs
crates/core_arch/src/arm_shared/hints.rs
crates/core_arch/src/arm_shared/registers/mod.rs
crates/core_arch/src/lib.rs
crates/core_arch/src/riscv/mod.rs
crates/core_arch/src/x86/avx512bw.rs
crates/core_arch/src/x86/avx512f.rs
crates/core_arch/src/x86/bt.rs
crates/core_arch/src/x86/cpuid.rs
crates/core_arch/src/x86/eflags.rs
crates/core_arch/src/x86_64/bt.rs

It is going to be removed from the prelude due to the decision in https://github.com/rust-lang/rust/issues/87228.

Import the asm! macro from core::arch

---

ci/docker/x86_64-linux-android/Dockerfile
crates/core_arch/src/aarch64/prefetch.rs
crates/core_arch/src/arm/mod.rs
crates/core_arch/src/arm_shared/barrier/v8.rs
crates/core_arch/src/wasm32/atomic.rs
crates/core_arch/src/wasm32/simd128.rs
crates/core_arch/src/x86/avx.rs
crates/core_arch/src/x86/avx512f.rs
crates/core_arch/src/x86/fxsr.rs
crates/core_arch/src/x86/sse.rs
crates/core_arch/src/x86/sse41.rs
crates/core_arch/src/x86/sse42.rs
crates/core_arch/src/x86/sse4a.rs
crates/core_arch/src/x86_64/fxsr.rs
crates/intrinsic-test/src/argument.rs
crates/intrinsic-test/src/intrinsic.rs
crates/std_detect/src/detect/arch/aarch64.rs
crates/std_detect/src/detect/arch/x86.rs
crates/stdarch-gen/neon.spec
crates/stdarch-gen/src/main.rs

I took some liberty of changing the variable name to from `paranthes` to `parentheses` instead of `parenthes`.
I hope that none of these files is not supposed to be modified.

Fix a bunch of typos

---

crates/core_arch/src/core_arch_docs.md
crates/core_arch/src/mod.rs
crates/core_arch/src/riscv/mod.rs
crates/core_arch/src/riscv64/mod.rs
crates/core_arch/src/riscv_shared/mod.rs

This pull request includes:
- Hypervisor extension, including memory management insturctions and virtual machine memory load and store instructions
- Supervisor memory management, including address translation fence insturctions (important for Rust kernel development) and cache invalidation insturctions
- Non privileged instructions FENCE.I, NOP and WFI
Module `riscv64` is added to include RV64 only virtual machine memory instructions. RV64 supports all RV32 virtual machine instructions, it's implemented like:
```rust
pub mod riscv64 {
pub use crate::core_arch::riscv::*;
pub use crate::core_arch::riscv64::*;
}
```
(Edit: implemented like `pub use crate::core_arch::riscv32::*;` etc)
Most of implemented functions are marked as unsafe. That's because these functions either load or store …

More RISC-V instructions in `core::arch`

---

crates/core_arch/src/x86/sse42.rs
crates/core_arch/src/x86_64/sse42.rs

x86(-64) actually implements crc32-c and not crc32, the intel documentation fails to mention this properly.
The only indication is the polynomial they use (0x11EDC6F41) in the `Operation` section.
(See: https://www.intel.com/content/www/us/en/docs/intrinsics-guide/index.html#text=_mm_crc32_&ig_expand=1495,1494,1493,1493)
Cross-referencing with this site, the polynomial is mentioned to be of crc32-c (https://sci.math.narkive.com/7MUM37mh/when-is-regular-crc32-better-or-worse-than-crc32-c).
And finally on Wikipedia it is mentioned in the description of `CRC32` that it is actually `CRC32C` (https://en.wikipedia.org/wiki/SSE4#SSE4.2).
Finally, I have tested this experimental with the `crc32c` crate:
```rs
fn main() {
let intel = unsafe {
std::arch::x86_64::_mm_crc32_u32(0xFFFF_FFFF, …
```

fixed documentation crc32 -> crc32-c (with x86(_64))

---

crates/core_arch/avx512f.md
crates/core_arch/src/x86/avx512f.rs

Implement avx512f compressstore intrinsics.

Implement avx512 compressstore intrinsics

---

crates/std_detect/src/detect/mod.rs

This fixes the issue raised in https://github.com/rust-lang/rust/issues/86941#issuecomment-951071896.

Emit the full is_{arch}_feature_detected! macro on all arches when building docs

---

crates/core_arch/src/riscv64/mod.rs
crates/core_arch/src/riscv_shared/mod.rs

This pull request includes:
- `Zksh`, `Zksed` extension in RISC-V K extension. There are four functions: `sm3p0`, `sm3p1`, `sm4ed` and `sm4ks` function.
- Floating point control and state register operations. They are three read instructions `frcsr`, `frrm`, `frflags`, and three swap instructions `fscsr`, `fsrm`, `fsflags` as is defined in the RISC-V unprivileged specification.
- Typo fixes in previous documents (thanks @dramforever).
The features above are all defined as safe Rust functions. Four K extension functions operates like arithmetic functions and does not visit on any memory addresses. The floating point control operations only reads or writes to floating point control configurations of the current hart.
~Note: choose of type `i32` in `sm4ks<const BS: i32>(x: u32, k: u32) -> …

riscv: K extension (part 1), floating-point control and state register

---

crates/core_arch/avx512vbmi2.md
crates/core_arch/src/x86/avx512vbmi2.rs

expandloadu_epi16,epi8
mask_compressstoreu_epi16,epi8

Complete avx512vbmi2

---

crates/std_detect/src/detect/arch/aarch64.rs

Initial implementation, looking for feedback on the approach here. See https://github.com/rust-lang/rust/pull/90271 and https://github.com/rust-lang/rust/issues/86941

Stabilise `is_aarch64_feature_detected!` under `simd_aarch64` feature

---

crates/core_arch/src/aarch64/neon/generated.rs
crates/core_arch/src/arm_shared/neon/generated.rs
crates/core_arch/src/arm_shared/neon/mod.rs
crates/intrinsic-test/missing_aarch64.txt
crates/stdarch-gen/neon.spec

This was missed  when most of the AArch64 intrinsics were stabilized.
cc https://github.com/rust-lang/rust/issues/94083

Stabilize vget_low_s8 on AArch64

---

crates/std_detect/src/detect/os/aarch64.rs

Import the asm macro in std_detect

---

crates/core_arch/src/x86/eflags.rs

In rust-lang/rust#94635, `#[deprecated]` and `#[rustc_deprecated]` were merged. Now that a bootstrap has occurred, I'm migrating all uses of `#[rustc_deprecated]`. This has to occur in submodules (such as `stdarch` here) before it can turn into an error in the compiler.

Remove use of `#[rustc_deprecated]` in favor of `#[deprecated]`

---

crates/core_arch/src/x86/sse2.rs

Typo in _mm_xor_pd description

---

crates/std_detect/src/detect/macros.rs

This is a blocker for https://github.com/rust-lang/rust/pull/95956
That PR modifies the stability checking logic of rustc so that it additionally checks the stability of the path segments used to name an item, rather than only checking the stability of the item itself. This is necessary to allow `std::error::Error` to be moved into a new unstable `core::error` module while still being available on stable via a re-export in the stable `std::error` module.
That change breaks the feature detection macros since they start encountering the `stdsimd` unstable feature which is not explicitly mentioned in those macros `allow_internal_unstable` attribute.

Add  stdsimd feature to allow_internal_unstable attribute in feature detect macros

---

crates/core_arch/src/wasm32/simd128.rs

Most Wasm SIMD instructions are lane-wise, but many of the intrinsics were described as pairwise or even used both terms. The clearest example being the extadd_pairwise intrinsics.

Wasm simd128 pairwise/lane-wise

---

crates/core_arch/src/macros.rs
crates/core_arch/src/powerpc/altivec.rs

The unused macro rules lint is an upcoming lint
for the rust compiler: https://github.com/rust-lang/rust/pull/96150. This PR prepares
for the introduction [so that the CI passes](https://github.com/rust-lang/rust/pull/96150#issuecomment-1119861986).
I have not tested whether this is all of the changes needed. If any more pop up I guess one can just add an `allow` to lib.rs.

Allow unused macro rules for two macros

---

crates/core_arch/src/macros.rs

Allow unused macro rules for simd_shuffle16 too

---

crates/core_arch/src/aarch64/neon/mod.rs
crates/core_arch/src/arm_shared/neon/mod.rs

Fix ARM vbsl* NEON intrinsics (#1191)

---

ci/dox.sh
crates/core_arch/Cargo.toml
crates/core_arch/build.rs
crates/core_arch/src/arm/v7.rs

Context: `rustc` added a few month ago [`--check-cfg`](https://doc.rust-lang.org/nightly/unstable-book/compiler-flags/check-cfg.html) support and enable it in the `rust-lang/rust` repo for every build.
I found out that `stdarch` had condition that were triggering the unstable `unexpected_cfgs` lint:
- `stdarch_intel_sde`: Internal to `stdarch`, status unknown, never set as far as I can tell. [bootstrap exception](https://github.com/rust-lang/rust/blob/1a97162cb245b5e2c7458c28859e3df779908c02/src/bootstrap/lib.rs#L201)
- `dont_compile_me`: Used on the `_rbit_u32` test for armv7, with an outdated comment. [bootstrap exception](https://github.com/rust-lang/rust/blob/1a97162cb245b5e2c7458c28859e3df779908c02/src/bootstrap/lib.rs#L218-L219)
- `core_arch_docs`: Set in `dox.sh` and in the …

Remove useless conditional compilation

---

crates/core_arch/src/aarch64/neon/mod.rs
crates/core_arch/src/arm_shared/neon/mod.rs

These are C structs from `arm_neon.h`, so having them be `#[repr(Rust)]` is wrong. Also they are used by certain intrinsics, and I suspect if they had a weird layout, it would be very broken.
Moreover, it seems reasonable for someone to want to do things like transmute a `float32x4x4_t` into a `[float32x4_t; 4]` and such, which requires `#[repr(C)]`.

Ensure the neon vector aggregates like `float32x4x4_t` are `#[repr(C)]`

---

crates/std_detect/src/detect/macros.rs

Allows these edge-cases to be used without `use`ing the `std::arch` module.
This doesn't happen on x86 due to the macro existing in the `std` root but all other platforms seem to see a cryptic "macro not found" error.

Fully qualify recursive macro calls

---

crates/core_arch/src/x86_64/cmpxchg16b.rs

The names of atomic intrinsics have been modified in
rust-lang/rust#97423. This pull request updates the
stdarch to use the new naming scheme.
Requires nightly-2022-06-30.

Update atomic intrinsics

---

crates/std_detect/src/detect/arch/aarch64.rs
crates/std_detect/src/detect/macros.rs

Now that runtime features and `target_features`are logically separate https://github.com/rust-lang/rust/pull/91608, there's a need to map between the two. Usually runtime feature detection short-circuits if a matching `target_feature` is enabled. However, on `aarch64-apple-darwin` there's no backup runtime detection yet so we rely purely on this behaviour.
Notably this fixes `std::arch::is_aarch64_feature_detected!("fp")` returning false on `aarch64-apple-darwin` and allows for multiple `target_features` to be specified in the future.

Allow mapping a runtime feature to a set of target_features

---

crates/core_arch/src/x86_64/cmpxchg16b.rs

Update cmpxchg16b to match changes from rust-lang/rust#98383.

Remove restrictions on compare-exchange memory ordering.

---

crates/core_arch/src/aarch64/crc.rs
crates/core_arch/src/arm_shared/crc.rs

Hello,
I have added documentation links for arms crc32 intrinsics . If this is okay , I will slowly add the links for other intrinsics in other PR's.

Adding documentation links for arm crc32 intrinsics

---

crates/core_arch/src/aarch64/neon/mod.rs
crates/core_arch/src/arm/neon.rs
crates/core_arch/src/arm_shared/crypto.rs
crates/core_arch/src/arm_shared/neon/mod.rs

Hello,
This is followup of #1316 .
This PR has doc links for arms aes and crypto intrinsics. This should cover most of the non neon intrinsics.
Hopefully, for the neon intrinsics I shall work on it later since it would need changes in stdarch-gen .

Adding doc links for arm crypto and aes intrinsics

---

crates/core_arch/src/aarch64/neon/generated.rs
crates/core_arch/src/arm_shared/neon/generated.rs
crates/stdarch-gen/src/main.rs

Hello
This is a follow up for #1317 .
This PR has doc links for arms neon intrinsics. I have edited the crate stdarch-gen and ran the command present in its readme to generate these doc links.

 Adding doc links for arm neon intrinsics

---

crates/std_detect/src/detect/macros.rs

This allows using feature detection macros, without placing a
requirement of enabled stdsimd feature gate from end users.
A follow-up to changes from #1311, which introduced the new macro.
Noticed while preparing a bump of stdarch submodule in the standard library.

Allow internal use of stdsimd from detect_feature

---

crates/core_arch/src/x86/avx512gfni.rs
crates/core_arch/src/x86/sse.rs
crates/core_arch/src/x86/sse2.rs
examples/hex.rs

See https://github.com/rust-lang/rust/pull/100746

Replace some calls to `pointer::offset` with `add` and `sub`

---

crates/core_arch/src/aarch64/neon/generated.rs
crates/core_arch/src/arm_shared/neon/generated.rs
crates/stdarch-gen/neon.spec
crates/stdarch-gen/src/main.rs

This was previously done as part of #1326, but it modified generated
code without fixing the root issue in neon.spec.

Properly fix vext intrinsic tests

---

crates/intrinsic-test/missing_aarch64.txt
crates/intrinsic-test/src/argument.rs
crates/intrinsic-test/src/intrinsic.rs
crates/intrinsic-test/src/main.rs
crates/intrinsic-test/src/types.rs
crates/intrinsic-test/src/values.rs

The files generated by the intrinsic test tool currently repeat the lines for the call multiple times, which sometimes generates very large test files. Changing it to use a loop and a load intrinsic reduces the size of the generated files and gives some coverage for the load intrinsics. This seems to also reduce the run-time for the test tool, enough that some of the intrinsics that are currently skipped because they take too long can be added back and the Rust test files can be built with `--target` again.
Example generated C before:
```
{
uint64x1_t a = { 0x10000000000000 };
uint64x1_t b = { 0x10000000000000 };
auto __return_value = vadd_u64(a, b);
std::cout << "Result -1: uint64x1_t(" << std::fixed << std::setprecision(150) <<  cast<uint64_t>(__return_value) << ")" << std::endl;
}
{ …
```

Change test tool to use a loop and load intrinsic.

---

crates/core_arch/src/macros.rs
crates/core_arch/src/simd_llvm.rs
crates/core_arch/src/x86/sse3.rs

This slightly reduces the amount of intrinsics codegen backends need to implement.

Remove simd_shuffle<n> usage in favor of simd_shuffle

---

crates/core_arch/src/x86/cpuid.rs

The `late` specifiers are useless in the case of `__cpuid_count`, there are no opportunities for correct register reuse.
Together with https://github.com/llvm/llvm-project/issues/57550 it causes https://github.com/rust-lang/rust/issues/101346. I strongly suggest checking use of `late` specifiers in other asm blocks as well.
This PR also changes the `__cpuid_count` asm to Intel syntax for consistency with asm in `has_cpuid`.

Remove late specifiers in __cpuid_count

---

crates/core_arch/src/lib.rs
crates/core_arch/src/mod.rs
crates/core_arch/src/riscv_shared/mod.rs
crates/core_arch/src/riscv_shared/p.rs

This pull reqeust includes intrinsics for RISC-V Packed SIMD extension. It includes:
Following instructions require work in further pull requests:
I implemented all intrinsic functions from P extension specification, this extension is useful as some RISC-V chips have already taped out with P extension. All intrinsics are implemented as inline assembly, for LLVM does not have these intrinsic functions by now; we can change to LLVM functions if it appears in future. This would be the first pull request as further works would be introduced in other pull requests.
Questions remain before further pull requests are:
- Where should I put RV32 only intrinsics? There are modules named `riscv_shared` and `riscv64` by now.
- How to get returned 64-bit value from inline assembly? Some of the RV32 …

riscv: P extension intrinsics for packed SIMD (part 1)

---

crates/assert-instr-macro/Cargo.toml
crates/assert-instr-macro/src/lib.rs
crates/core_arch/Cargo.toml
crates/intrinsic-test/Cargo.toml
crates/intrinsic-test/src/acle_csv_parser.rs
crates/intrinsic-test/src/intrinsic.rs
crates/intrinsic-test/src/main.rs
crates/intrinsic-test/src/types.rs
crates/intrinsic-test/src/values.rs
crates/simd-test-macro/Cargo.toml
crates/simd-test-macro/src/lib.rs
crates/std_detect/Cargo.toml
crates/std_detect/src/detect/os/linux/aarch64.rs
crates/std_detect/src/detect/os/linux/auxvec.rs
crates/std_detect/tests/cpu-detection.rs
crates/stdarch-gen/Cargo.toml
crates/stdarch-gen/src/main.rs
crates/stdarch-test/Cargo.toml
crates/stdarch-test/src/disassembly.rs
crates/stdarch-test/src/lib.rs
crates/stdarch-verify/Cargo.toml
crates/stdarch-verify/src/lib.rs
crates/stdarch-verify/tests/arm.rs
crates/stdarch-verify/tests/mips.rs
crates/stdarch-verify/tests/x86-intel.rs
examples/Cargo.toml
examples/connect5.rs
examples/hex.rs

Switch to the 2021 edition.
Add the result of running `clippy::uninlined_format_args` lint. Currently the lint is in `pedantic`, but there are plans/hopes to move it to `style`.
Locally, I ran this to generate the changes.  Not ideal because it has produced a number of compilation errors.
```bash
rustup run nightly cargo clippy --fix --no-deps --allow-dirty -- -A clippy::all -W clippy::uninlined_format_args
```

Edition 2021, apply clippy::uninlined_format_args fix

---

crates/core_arch/src/x86/sse42.rs

This was causing aborts with debug builds of the standard library.
Fixes #1336

Fix undefined behavior in SSE4.2 test

---

crates/core_arch/src/arm_shared/neon/generated.rs
crates/core_arch/src/arm_shared/neon/mod.rs
crates/stdarch-gen/src/main.rs

Currently these are only marked as stable on aarch64, which makes them appear as unstable in the standard library docs generated on x86_64.
This is still somewhat misleading in the case of ARM since it makes the docs show some functions as stable when they aren't, but this is still better than the status quo.

Mark arm_shared intrinsics as stable on all target except ARM

---

crates/core_arch/src/x86/avx512vaes.rs
crates/stdarch-verify/tests/x86-intel.rs

These are available on AMD CPUs without AVX512,
Fixes #1343

Don't require AVX512 for 256-bit VAES intrinsics

---

crates/core_arch/src/x86/avx512gfni.rs
crates/core_arch/src/x86/avx512vpclmulqdq.rs
crates/stdarch-verify/tests/x86-intel.rs

Don't require AVX512 for 128/256-bit GFNI & VPCLMULQDQ intrinsics

---

crates/std_detect/src/detect/mod.rs

After digging into why the [`is_aarch64_feature_detected!`](https://doc.rust-lang.org/std/arch/macro.is_aarch64_feature_detected.html) macro didn't work as I expected on my Android device (only `asimd`, `fp`, `neon` were detected by the macro), I came to this line that dispatches the detection depending on the OS.
My understanding is that Android should behave like Linux w.r.t. CPU feature detection on ARM - at least on the devices I've tested with the various methods (`getauxval`, checking `/proc/cpuinfo`) worked fine. However, Rust defines a distinct `target_os` for Android (https://github.com/rust-lang/rust/blob/1.65.0/compiler/rustc_target/src/spec/android_base.rs#L5), so the filtering by `target_os = "linux"` doesn't work (even though Android is arguably a flavor of Linux).
I've …

Detect CPU features with Linux methods on Android for non-Intel CPUs.

---

crates/core_arch/src/x86/avx2.rs
crates/core_arch/src/x86/sse2.rs
crates/core_arch/src/x86/sse41.rs

Copied from wasm32 implementaions
https://github.com/rust-lang/stdarch/blob/547e3b0b80ad0952a12b9dd75f3da05b72b7e188/crates/core_arch/src/wasm32/simd128.rs#L2543-L2554
Affected functions:
sse2:
+ `_mm_max_epi16`
+ `_mm_max_epu8`
+ `_mm_min_epi16`
+ `_mm_min_epu8`
sse41:
+ `_mm_max_epi8`
+ `_mm_max_epu16`
+ `_mm_max_epi32`
+ `_mm_max_epu32`
+ `_mm_min_epi8`
+ `_mm_min_epu16`
+ `_mm_min_epi32`
+ `_mm_min_epu32`
avx2:
+ `_mm256_max_epi16`
+ `_mm256_max_epi32`
+ `_mm256_max_epi8`
+ `_mm256_max_epu16`
+ `_mm256_max_epu32`
+ `_mm256_max_epu8`
+ `_mm256_min_epi16`
+ `_mm256_min_epi32`
+ `_mm256_min_epi8`
+ `_mm256_min_epu16`
+ `_mm256_min_epu32`
+ `_mm256_min_epu8`

Use simd intrinsics for max and min

---

crates/core_arch/src/x86/gfni.rs
crates/core_arch/src/x86/mod.rs
crates/core_arch/src/x86/vaes.rs
crates/core_arch/src/x86/vpclmulqdq.rs
crates/core_arch/tests/cpu-detection.rs
crates/std_detect/src/detect/arch/x86.rs
crates/std_detect/src/detect/macros.rs
crates/std_detect/src/detect/os/x86.rs
crates/std_detect/tests/cpu-detection.rs
crates/std_detect/tests/x86-specific.rs

Renamed features according to rust-lang/rust#100752 (and #1325)
~This works on master, but rust-lang/rust#103750 hasn't hit nightly yet.~ landed on nightly
An open question: in `is_x86_feature_detected`, should `avx512gfni` be an alias for `gfni` (even though it doesn't actually check for `avx512f`), or should it be a separate feature that checks the multiple feature flags required to enable the AVX-512 GFNI instructions? (and the same goes for `avx512vaes` and `avx512vpclmulqdq`)

Rename misleading features

---

triagebot.toml

This migrates this repository from using the highfive bot to using triagebot (aka rustbot).
This should not be merged without coordinating the removal of the highfive webhook and/or merging https://github.com/rust-lang/highfive/pull/438.

[DO NOT MERGE] Migrate from highfive to triagebot

---

triagebot.toml

#1359 incorrectly added the `S-waiting-on-review` autolabel. This repo (and homu) are not configured to use S-waiting-on… labels, so this just removes it.

Remove S-waiting-on-review autolabel

---

crates/core_arch/src/x86_64/cmpxchg16b.rs

Stabilize cmpxchg16b instrinsic

---

crates/core_arch/src/aarch64/neon/generated.rs
crates/core_arch/src/arm_shared/neon/generated.rs
crates/core_arch/src/x86_64/cmpxchg16b.rs
crates/stdarch-gen/src/main.rs

The tests can run if and only if the target_features for the corresponding intrinsics are detected at run-time, so make sure that the tests have an appropriate `simd_test()`.
This fixes some failures due to tests running when they shouldn't. For example, some tests would fail on hardware that lacks "fcma".
This decouples the feature names in the generator, since "arm" and "arm64" use different names, and for "arm" the dynamic `simd_test` features don't match the static `target_feature` names.
There are several changes to the tests, but changes to the generated intrinsics themselves are minimal, and cosmetic.

Fix generated Neon simd_test features.

---

crates/core_arch/src/aarch64/neon/generated.rs
crates/core_arch/src/aarch64/neon/mod.rs
crates/core_arch/src/arm_shared/neon/generated.rs
crates/core_arch/src/arm_shared/neon/mod.rs
crates/core_arch/src/lib.rs
crates/core_arch/src/macros.rs
crates/core_arch/src/powerpc/vsx.rs
crates/core_arch/src/wasm32/simd128.rs
crates/core_arch/src/x86/avx.rs
crates/core_arch/src/x86/avx2.rs
crates/core_arch/src/x86/avx512bw.rs
crates/core_arch/src/x86/avx512f.rs
crates/core_arch/src/x86/sse.rs
crates/core_arch/src/x86/sse2.rs
crates/core_arch/src/x86/sse3.rs
crates/core_arch/src/x86/sse41.rs
crates/core_arch/src/x86/ssse3.rs
crates/stdarch-gen/neon.spec
crates/stdarch-gen/src/main.rs

With inline consts we don't need these associated const hacks any more, and we can use a single macro for all vector widths.

use inline const for last simd_shuffle argument

---

crates/core_arch/src/lib.rs

f16c_target_feature was recently stabilised.
This fixes a warning that results in a CI failure (due to `-D stable-features`) with current nightly Rust.

Don't declare f16c_target_feature.

---

crates/core_arch/src/mod.rs

This PR removes the last `target_arch=nvptx` in accordance to the compiler MCP 496 (https://github.com/rust-lang/compiler-team/issues/496). It came up when cleaning up bootstrap extra cfgs (https://github.com/rust-lang/rust/pull/107080).

Remove obsolete cfg for nvptx

---

crates/std_detect/src/detect/os/windows/aarch64.rs
crates/std_detect/tests/cpu-detection.rs

IsProcessorFeaturePresent currently supports the detection of more CPU features.
([IsProcessorFeaturePresent docs](https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-isprocessorfeaturepresent) currently don't mention most of them but it appears there is [a PR to update it](https://github.com/MicrosoftDocs/sdk-api/pull/1409/files))

std_detect: Support detecting lse/dotprod/jsconv/rcpc on aarch64 Windows

---

crates/std_detect/src/detect/mod.rs
crates/std_detect/src/detect/os/aarch64.rs
crates/std_detect/src/detect/os/freebsd/aarch64.rs
crates/std_detect/src/detect/os/openbsd/aarch64.rs
crates/std_detect/tests/cpu-detection.rs

OpenBSD doesn't trap the mrs instruction, but exposes the system registers through sysctl.
https://github.com/openbsd/src/commit/d335af936b9d7dd9cf655cae1ce19560c45de6c8
So, we can support run-time detection using the register parsing code in [os/aarch64.rs](https://github.com/rust-lang/stdarch/blob/f325623f26c7ed7eb81e2fbd8d71216bc7c54337/crates/std_detect/src/detect/os/aarch64.rs) (currently used on aarch64 FreeBSD) and sysctl. (See also go's patch that does the same thing as this patch: https://github.com/golang/go/commit/cd54ef1f61945459486e9eea2f016d99ef1da925. See also OpenBSD libcrypto patch: https://github.com/openbsd/src/commit/be689f1071529b27fdf00b1407302592c71d1c1a.)
Tested on aarch64 OpenBSD VM 7.2-current/7.2-stable/7.1-stable.
The following screenshot is from a test on …

std_detect: Support run-time detection on aarch64 OpenBSD

---

crates/std_detect/README.md
crates/std_detect/src/detect/os/linux/auxvec.rs

Currently, we use `dlsym` on non-x86[^1] Linux/Android when the `std_detect_dlsym_getauxval` feature (enabled by default) is enabled because `getauxval` may not be available.
However, [since Rust 1.64](https://blog.rust-lang.org/2022/08/01/Increasing-glibc-kernel-requirements.html), all `*-linux-gnu*` targets have glibc requirements higher than [glibc 2.16 that `getauxval` added](https://sourceware.org/legacy-ml/libc-announce/2012/msg00000.html), and we can safely assume `getauxval` is linked to the binary.
Related https://github.com/rust-lang/stdarch/issues/655 (fyi @briansmith)
---
IIUC, at this time, we can do this on only `*-linux-gnu*` targets, because:
- On `*-linux-musl*`, it seems that `getauxval` is not always available, independent of version requirements: …

std_detect: Always avoid dlsym on *-linux-gnu* targets

---

crates/core_arch/src/x86/cpuid.rs

The former reference link to Intel® 64 and IA-32 Architectures Software Developer’s Manuals has failed. The latest URL to the Intel manual book can be found [Intel® 64 and IA-32 Architecture Developer Manuals](https://www.intel.com/content/www/us/en/developer/articles/technical/intel-sdm.html).

update the URL of Intel CPUID reference book

---

crates/std_detect/README.md

This updates platform support docs to reflect aarch64 OpenBSD support by https://github.com/rust-lang/stdarch/pull/1374, aarch64 Windows support by https://github.com/rust-lang/stdarch/pull/829, Android support by https://github.com/rust-lang/stdarch/pull/1351, riscv Linux support by https://github.com/rust-lang/stdarch/pull/1263, arm/powerpc64 FreeBSD support by https://github.com/rust-lang/stdarch/pull/747.

std_detect: Update platform support docs

---

crates/std_detect/src/detect/os/aarch64.rs
crates/std_detect/src/detect/os/openbsd/aarch64.rs
crates/std_detect/tests/cpu-detection.rs

If FEAT_LSE2 is implemented, AT field of ID_AA64MMFR2_EL1 is 0b0001. https://developer.arm.com/documentation/ddi0601/2022-12/AArch64-Registers/ID-AA64MMFR2-EL1--AArch64-Memory-Model-Feature-Register-2?lang=en#fieldset_0-35_32
Also, if FEAT_LSE is implemented, Atomic field of ID_AA64ISAR0_EL1 is >= 0b0010, not >= 0b0001. (0b0001 is reserved) This patch fixes it too.
https://developer.arm.com/documentation/ddi0601/2022-12/AArch64-Registers/ID-AA64ISAR0-EL1--AArch64-Instruction-Set-Attribute-Register-0?lang=en#fieldset_0-23_20

std_detect: Support run-time detection of FEAT_LSE2 on aarch64 BSD

---

crates/std_detect/src/detect/os/linux/aarch64.rs

[Samsung Exynos 9810](https://en.wikichip.org/wiki/samsung/exynos/9810) has a bug that big and little cores have different ISAs. And on older Android (pre-9), the kernel incorrectly reports that features available only on some cores are available on all cores.
See https://reviews.llvm.org/D114523 for details. That patch is about FEAT_LSE, but IIUC the detection of most features that are available in armv8.2-a but may not be available in armv8.0-a should be affected by this issue.

std_detect: Workaround Exynos 9810 bug on aarch64 Android

---

crates/core_arch/src/lib.rs

```
warning: the feature `cmpxchg16b_target_feature` has been stable since 1.69.0-nightly and no longer requires an attribute to enable
--> crates/core_arch/src/lib.rs:24:5
|
24 |     cmpxchg16b_target_feature,
|     ^^^^^^^^^^^^^^^^^^^^^^^^^
|
= note: `#[warn(stable_features)]` on by default
warning: the feature `target_feature_11` has been stable since 1.69.0-nightly and no longer requires an attribute to enable
--> crates/core_arch/src/lib.rs:34:5
|
34 |     target_feature_11,
|     ^^^^^^^^^^^^^^^^^
```

Fix stable_features warnings

---

crates/std_detect/src/detect/os/windows/aarch64.rs
crates/std_detect/tests/cpu-detection.rs

According to google/cpu_features, IsProcessorFeaturePresent(PF_ARM_VFP_32_REGISTERS_AVAILABLE) returns whether fp is available.
https://github.com/google/cpu_features/blob/a6bf4f9031ec601f905660b8cef82d7478b33d64/src/impl_aarch64_windows.c#L112-L113
~~Also, update to respect feature dependencies based on LLVM's feature definitions:
https://github.com/llvm/llvm-project/blob/main/llvm/lib/Target/AArch64/AArch64.td~~
~~I don't know if there is support for [cases where fp or asimd is unavailable](https://developer.arm.com/documentation/den0024/a/AArch64-Floating-point-and-NEON) on Windows, but I think it is reasonable to unify the behavior with [linux](https://github.com/rust-lang/stdarch/blob/15c760e75c58e49f15d32e76022b04d597c308e8/crates/std_detect/src/detect/os/linux/aarch64.rs#L306) and …

std_detect: Support run-time detection of fp on aarch64 Windows

---

crates/core_arch/src/lib.rs

We removed this in 307c42fbf4bdfdda2c46fdc1d330cc61d96b5182, but the stabilization was reverted in https://github.com/rust-lang/rust/pull/108654.

Re-add #![feature(target_feature_11)]

---

crates/core_arch/src/x86/f16c.rs
crates/std_detect/tests/x86-specific.rs

Resolves #1234
Compiler PR for stabilizing corresponding target_feature: https://github.com/rust-lang/rust/pull/106323

Stabilize x86 F16C

---

crates/std_detect/src/detect/arch/x86.rs
crates/std_detect/src/detect/os/x86.rs

Allows users to detect the ERMSB (Enhanced REP MOVSB and STOSB) CPU feature on x86 machines

Implemented `is_x86_feature_detected!("ermsb")`

---

ci/docker/wasm32-wasi/Dockerfile
crates/core_arch/src/wasm32/mod.rs
crates/core_arch/src/wasm32/relaxed_simd.rs
crates/core_arch/src/wasm32/simd128.rs
crates/stdarch-test/Cargo.toml

This commit adds intrinsics to the `wasm32` to support the [relaxed SIMD proposal][proposal]. These are added with the same naming conventions of existing simd-related intrinsics for wasm which is similar to the instruction name but matches sign in a few places.
This additionally updates Wasmtime to execute tests with support for the relaxed simd proposal. No release has been made yet so this uses the `dev` release, and I can make a PR in April when the support in Wasmtime has been released to an official release. The `wasmprinter` crate is also updated to understand these instruction opcodes as well.
Documentation has been added for all intrinsics, but tests have only been added for some of them so far. I hope to follow-up later with more tests.
[proposal]: …

wasm32: Add relaxed simd instructions

---

crates/core_arch/src/x86_64/cmpxchg16b.rs

- Fix a typo in the feature name
- Update docs to reflect changes in behavior on invalid ordering in stabilized PR: invalid ordering is no longer UB, just causes panic as well as compare_exchange
(stdarch submodule in rust-lang/rust has not been updated yet, so the function name fix should not be a problem.)

core_arch: Update cmpxchg16b docs and fix feature name

---

crates/std_detect/src/lib.rs

I'm writing the lint, so it needs to be allowed here.
Needs to wait on rust-lang/compiler-team#596

Allow `internal_features`

---

crates/core_arch/src/arm_shared/neon/mod.rs

This is a follow-up to #1345 where these appeared as unstable in the standard library docs because they are only stabilized for ARM. They were missed in the original PR.

Mark more arm_shared intrinsics and types as stable in docs

---

crates/core_arch/src/powerpc/mod.rs

Now the documentation should be generated correctly and vsx isn't always present.

Fix the powerpc feature guards

---

crates/core_arch/src/aarch64/neon/generated.rs
crates/stdarch-gen/neon.spec

LLVM 16 seems to have regressed codegen for CMGE #0 and uses CMGT #-1 instead.
Also, there are some changes to how SQDMLAL/SQDMLSL is expanded.
Fixes #1404

Update intrinsic tests for LLVM 16

---

crates/std_detect/README.md
crates/std_detect/src/detect/os/linux/auxvec.rs

As mentioned in https://github.com/rust-lang/stdarch/pull/1375, [since Rust 1.68](https://blog.rust-lang.org/2023/01/09/android-ndk-update-r25.html), `*-android*` targets have the minimum supported API level higher than [Android 4.3 (API level 18) that added `getauxval`](https://github.com/aosp-mirror/platform_bionic/blob/d3ebc2f7c49a9893b114124d4a6b315f3a328764/libc/include/sys/auxv.h#L49).

std_detect: Always avoid dlsym on *-android* targets

---

crates/core_arch/src/arm_shared/crypto.rs
crates/std_detect/src/detect/arch/arm.rs
crates/std_detect/src/detect/os/freebsd/arm.rs
crates/std_detect/src/detect/os/linux/arm.rs
crates/std_detect/tests/cpu-detection.rs

Similar to https://github.com/rust-lang/stdarch/pull/1192 and https://github.com/rust-lang/stdarch/pull/1146 done for aarch64, but for arm.
Those PRs skipped arm for compatibility with older LLVM (https://github.com/rust-lang/stdarch/pull/1146#issuecomment-849723187), but the current nightly's minimum LLVM version is 14 (https://github.com/rust-lang/rust/commit/2970ad8aeeaa94ad5af5fc49150c14bcf86bf7c9), so we can do this.
Original motivation is: https://github.com/rust-lang/rust/pull/84665#discussion_r622937124
> LLVM has moved away from a combined "crypto" feature and now uses separate "aes" and "sha2" features. We should do the same here.
(After this is merged, I will send a patch to rust-lang/rust to remove the "crypto" target feature.)

Remove uses of arm crypto target feature

---

crates/core_arch/src/x86/avx.rs
crates/core_arch/src/x86/avx512f.rs
crates/core_arch/src/x86/sse.rs
crates/core_arch/src/x86/sse2.rs

These intrinsics actually are zeroing, so we should be upfront that these still return a valid value in reality. At most, we might in the future want to use a "freezing" semantics here. In any case, they are definitely not returning MaybeUninit, or any other possibly-poison value.
Motivated partly by https://github.com/rust-lang/rust/issues/107945

Clarify undefined can still mean init

---

crates/stdarch-gen/neon.spec

Fixes a *very* minor typo / unfinished doc comment in `neon.spec` for unsigned greater than.
P.S.: I really appreciate this fantastic library. Keep up the great work! :fire:

docs: fix unfinished uint vcgt documentation

---

ci/docker/wasm32-wasi/Dockerfile

This moves from the "dev" release of Wasmtime, used for its relaxed-simd support, to an official release of Wasmtime just made which is the first with relaxed-simd support.

Use Wasmtime 8.0.0 on CI

---

crates/core_arch/src/wasm32/simd128.rs
crates/std_detect/src/detect/os/linux/auxvec.rs

This removes all the instances of drop call that drop copy and ref types and replace them with `let _ = ...;` (as it is the T-lang approved way to suppress the unused variable lint).
Found in https://github.com/rust-lang/rust/pull/109732#issuecomment-1512132280 while uplifting `clippy::{drop,forget}_{ref,copy}`.

Remove useless drop (clippy drop_ref and drop_copy lint)

---

.github/workflows/main.yml
ci/build-std-detect.sh
crates/std_detect/src/detect/os/linux/auxvec.rs

This fixes the build error in https://github.com/rust-lang/rust/pull/110285#issuecomment-1519837713.
In https://github.com/rust-lang/stdarch/pull/1406 I checked only aarch64 android and missed the fact that libc crate does not provide getauxval on 32-bit android (although I believe [android provides getauxval on these targets](https://github.com/aosp-mirror/platform_bionic/commit/2c5153b043b44e9935a334ae9b2d5a4bc5258b40)). Sorry.
The second commit in this PR adds a job to CI that builds non-Linux targets that are not currently tested in CI to prevent such an oversight from occurring again in the future.

std_detect: Do not use libc::getauxval on 32-bit Android

---

crates/intrinsic-test/src/json_parser.rs

Fixes CI for https://github.com/rust-lang/stdarch/pull/1427  which didn't run due to a Github outage. The second commit in the chain broke the intrinsic-test tool.

Fix intrinsic-test rejecting the new `instructions` JSON field

---

crates/core_arch/src/arm_shared/crypto.rs

These have been tested against the equivalent Clang intrinsics with random inputs.

Stabilize AArch64 AES/SHA1/SHA2 intrinsics

---

crates/core_arch/src/x86/mod.rs
crates/stdarch-verify/tests/x86-intel.rs

Preparing in anticipation of FCP in
https://github.com/rust-lang/rust/issues/111193 completing.

Remove ud2 intrinsic (in favor of `asm!` or `abort` as needed)

---

crates/core_arch/src/x86/pclmulqdq.rs
crates/core_arch/src/x86/vpclmulqdq.rs

The documentation says that the multiplication is using polynomials over the field GF(2^k) while those are actually just polynomials over the field GF(2). The k comes from nowhere and is misleading.
This PR replaces the occurences of GF(2^k) in the documentation for those the carryless multiplication intrinsics with GF(2).

Fix documentation for carryless multiplication

---

Cargo.toml

Cargo will soon be generating a warning if the `resolver` field is not set in a virtual workspace. I'm opening this to proactively help avoid the warning in this repo. More information about this change can be found at https://github.com/rust-lang/cargo/issues/10112.

Explicitly set the cargo resolver

---

crates/stdarch-test/src/lib.rs

The LLVM code generation was improved some time ago.

Remove assert_instr exception for AArch64 *cvt*.

---

crates/core_arch/src/x86/mod.rs

While there might be some uncertainty still with all the intrinsics and other related items, could we perhaps stabilize the types?
It seems like there's not much choice to be had, since m512 is definitely f32x16 and m512d is likewise f64x8.
I didn't include `__m512bh` since `__m128bh` is also unstable.
<https://rust-lang.zulipchat.com/#narrow/stream/219381-t-libs/topic/Stabilizing.20AVX2.20.26.20AVX512.20*types*/near/362541037>

Stabilize `__m512i`, `__m512`, and `__m512d`

---

crates/core_arch/src/aarch64/neon/generated.rs
crates/core_arch/src/arm_shared/neon/generated.rs
crates/stdarch-gen/neon.spec

In this PR, removed parens with "simple" expression followed by cast.
The `unused_paren` lint will be [triggered](https://github.com/rust-lang/rust/pull/110189
)  at there in the future.

arm(neon): avoid snippets which triggers unused_paren lint

---

ci/run.sh

This is broken due to rust-lang/rust#112460.

Disable vld2q_dup_f32 test in CI

---

crates/core_arch/src/aarch64/neon/generated.rs
crates/core_arch/src/arm_shared/neon/generated.rs
crates/intrinsic-test/missing_aarch64.txt
crates/intrinsic-test/missing_arm.txt
crates/std_detect/src/detect/arch/arm.rs
crates/std_detect/src/detect/os/linux/arm.rs
crates/std_detect/tests/cpu-detection.rs
crates/stdarch-gen/neon.spec
crates/stdarch-gen/src/main.rs

This covers "i8mm" and "dotprod" for both AArch32 and AArch64.
Note that for AArch32, neither "i8mm" nor the "dotprod" are exposed by Linux [until v6.2](https://github.com/torvalds/linux/commit/956ca3a4eb81c1b8cc3226af3083847544dcb098), so the CI won't cover them immediately. However, the CI's QEMU does support the instructions, and the tests pass if the `simd_test` feature check is manually disabled.

Add support for missing Neon intrinsics.

---

crates/core_arch/src/x86/avx.rs

Rustc_codegen_cranelift requires immediates to already be constant in MIR unlike LLVM which only needs them constant after optimizations.

Use const {} for the immediate args of _mm*_cmp_*

---

crates/core_arch/src/arm_shared/neon/generated.rs
crates/stdarch-gen/src/main.rs

This happens because the docs are built for x86_64, see #1345.
Fixes #1444

Fix some NEON intrinsics not appearing in standard library docs

---

crates/core_arch/src/lib.rs
crates/core_arch/src/powerpc/altivec.rs

`vec_xl` contains an ugly workaround since `copy_nonoverlapping` is not correctly inlined.

More altivec intrinsics

---

.github/workflows/main.yml
ci/dox.sh
crates/core_arch/src/wasm32/simd128.rs

- MIPS targets have been removed from rustup, see https://github.com/rust-lang/compiler-team/issues/648.
- Removed `#[target_feature]` requirements from `const fn`, since that caused const-eval to fail.

Remove MIPS from CI

---

crates/core_arch/src/arm/neon.rs
crates/core_arch/src/wasm32/relaxed_simd.rs
crates/core_arch/src/wasm32/simd128.rs

Remove redundant definitions

---

crates/intrinsic-test/src/argument.rs
examples/connect5.rs

* Fix typo in HTML tag
* Mark some things with backticks to fix warnings about unescaped square brackets.
* Spell "initialize" correctly to fix typos.

docs: Fix warnings and typos.

---

crates/core_arch/src/aarch64/tme.rs
crates/core_arch/src/wasm32/relaxed_simd.rs
crates/core_arch/src/wasm32/simd128.rs
crates/core_arch/src/x86/avx.rs

There are plenty more, but these were infrequent ones. Other PRs will address other lints.

clippy: Some simple clippy fixes.

---

crates/core_arch/src/x86/avx512bw.rs
crates/core_arch/src/x86/avx512f.rs

The full warning is "casting raw pointers to the same type and constness is unnecessary"

clippy: unnecessary cast warnings on x86.

---

crates/core_arch/src/x86/avx.rs
crates/core_arch/src/x86/avx2.rs
crates/core_arch/src/x86/avx512bw.rs
crates/core_arch/src/x86/avx512f.rs
crates/core_arch/src/x86/sse2.rs

Reimplements some x86 without using arch-specific LLVM intrinsics:
* Store unaligned (`_mm*_storeu_*`): Use `<*mut _>::write_unaligned` instead of `llvm.x86.*.storeu.*`.
* Shift by immediate (`_mm*_s{ll,rl,ra}i_epi*`): Use `if` (srl, sll) or `min` (sra) to simulate the behaviour when the RHS is out of range. RHS is constant, so the `if`/`min` will be optimized away.
The advantages are:
* codegen will not have to handle those LLVM instrinsics.
* miri will be able to emulate them without specific shims

Reimplement some x86 intrinsics without arch-specific LLVM intrinsics

---

ci/docker/riscv64gc-unknown-linux-gnu/Dockerfile
ci/run.sh
crates/core_arch/src/riscv_shared/mod.rs
crates/core_arch/src/riscv_shared/zb.rs

This is the second PR for rust-lang/rust#114544 and a follow-up to #1453. 
This PR adds all the instructions for the `zb` extension. This PR will get force-pushed after #1453 is merged.

Implement RISC-V Zb intrinsics 

---

ci/run-docker.sh

This only adds a usage check for the `/ci/run-docker.sh` script.
I have tried to run this script many times without arguments and for some reason it it then defaults to using `ci/docker` as the target. This cost me some debugging time.

Impr: Add a usage check for the ci/run-docker.sh script

---

crates/core_arch/src/x86/sse.rs
crates/core_arch/src/x86/sse2.rs
crates/core_arch/src/x86/test.rs

* Add `#[track_caller]` to some assert functions.
* SSE2 sll/slli/srl/srli/sra/srai now test cases where the shift amount is equal or greater to the number of bits
* Test -0.0 in SSE/SSE2 packed min/max

Improve some SSE and SSE2 tests

---

ci/docker/riscv64gc-unknown-linux-gnu/Dockerfile
ci/run.sh
crates/core_arch/src/riscv64/zk.rs
crates/core_arch/src/riscv_shared/zb.rs
crates/core_arch/src/riscv_shared/zk.rs
crates/stdarch-test/src/disassembly.rs

This switches to `llvm-objdump` instead of the gnu `objdump` variant, and additionally enables `zks` for the SM instructions. This fixes #1464.
There is still a problem with testing for riscv32, I am not 100% sure how to a docker image for this target. Just adding the `NOSTD` and `NORUN` flags, does to do very little.

Reenable RISC-V Zk and Zb `assert_instr`

---

crates/core_arch/src/riscv64/zk.rs

This PR fixes a mistake in #1453 where the `aes64im` is missing.

Add missing `aes64im` of RISC-V Zk extension

---

crates/core_arch/src/arm_shared/barrier/cp15.rs

[ARM11 MPCore Processor Technical Reference Manual](https://developer.arm.com/documentation/ddi0360/e/control-coprocessor-cp15/register-descriptions/c7--cache-operations-register?lang=en) says the value in the Rd register of these instructions is SBZ (should be zero).
> ```
> MCR p15, 0, <Rd>, c7, <CRm>, <Opcode_2>
> ```
> Data
>
> This is the value that is written to CP15 c7. This is the value in the Rd register specified in the MCR instruction.

core_arch: Fix ARMv6 CP15 barrier

---

crates/core_arch/src/x86/sse.rs

Thanks @eduardosm  for pointing me to these operations.
Cc @rust-lang/lang @rust-lang/opsem

Rust does not let you observe or mutate the floating-point register in well-defined ways

---

ci/run.sh
crates/assert-instr-macro/src/lib.rs
crates/core_arch/src/x86/sse.rs
crates/core_arch/src/x86/sse41.rs

Follow-up of https://github.com/rust-lang/stdarch/pull/1454
Additionally, I removed references to `_mm_setcsr` and `_mm_getcsr` from documentation of non-deprecated functions.
cc @RalfJung

Deprecate functions that use `_mm_setcsr` or `_mm_getcsr` internally

---

crates/core_arch/src/arm_shared/neon/shift_and_insert_tests.rs
crates/core_arch/src/x86/sse.rs
crates/core_arch/src/x86/sse2.rs
crates/core_arch/src/x86_64/sse2.rs
crates/simd-test-macro/Cargo.toml
crates/simd-test-macro/src/lib.rs

We are adding stdarch to libstd Miri testing (https://github.com/rust-lang/miri-test-libstd/pull/19).
Some tests required some fixing, while there are other that are simply ignored because it is unlikely that Miri support them in the near future.
For now, only SSE and SSE2 are being considered.
cc @RalfJung

Fix some SSE and SSE2 tests for Miri

---

crates/core_arch/src/x86/sse.rs

1.73 is about to be released as stable and [master branch is at 1.75](https://github.com/rust-lang/rust/blob/master/src/version), so bump the version before updating the submodule.

Bump _mm_getcsr/_mm_setcsr deprecation Rust version to 1.75

---

crates/std_detect/Cargo.toml
crates/std_detect/src/detect/os/linux/auxvec.rs

It hasn't been used since roughly 2018. The latest published version of auxv has a less common license and doesn't specify any license in it's Cargo.toml file.

Remove the auxv dev dependency.

---

crates/core_arch/src/x86/avx.rs
crates/core_arch/src/x86/sse.rs
crates/core_arch/src/x86/sse2.rs

The `simd_bitmask` intrinsic requires each element to be all-1 or all-0, while the x86 functions only check for the highest bit.

Fix UB in _mm_movemask_ps, _mm_movemask_pd, _mm256_movemask_ps and _mm256_movemask_pd

---

crates/core_arch/src/aarch64/mod.rs
crates/core_arch/src/aarch64/neon/mod.rs
crates/core_arch/src/arm/mod.rs
crates/core_arch/src/arm/neon.rs
crates/core_arch/src/arm_shared/mod.rs
crates/core_arch/src/arm_shared/neon/mod.rs

These are currently broken because the order of elements inside vectors is reversed on big-endian systems: the ARM ABI requires that element 0 is located at the highest address of the vector type. However LLVM intrinsics expect element 0 to be located at the lowest address.
See https://llvm.org/docs/BigEndianNEON.html and `arm_neon.h` in Clang for more details.
This is tracked in #1484.
Although this is a breaking change, this is acceptable for 2 reasons:
- big endian ARM targets are only tier 3.
- it is preferable to stop existing code from compiling than to let it run and produce incorrect results.

Disable NEON intrinsics on big-endian ARM

---

crates/core_arch/src/x86/bt.rs
crates/core_arch/src/x86/cpuid.rs
crates/core_arch/src/x86/eflags.rs
crates/core_arch/src/x86/fxsr.rs
crates/core_arch/src/x86/sse4a.rs
crates/core_arch/src/x86/xsave.rs
crates/core_arch/src/x86_64/bt.rs
crates/core_arch/src/x86_64/fxsr.rs
crates/core_arch/src/x86_64/xsave.rs

This includes functions that use inline assemby or that do certains operations such as saving/restoring the processor state.

Add `#[cfg_attr(miri, ignore)]` to tests of functions that cannot be supported by Miri

---

crates/intrinsic-test/README.md

The tracking spreadsheet hasn't been relevant for some time, and seems to have been deleted.

Drop old link from intrinsic-test README.

---

ci/run.sh
crates/intrinsic-test/Cargo.toml
crates/intrinsic-test/src/argument.rs
crates/intrinsic-test/src/main.rs
crates/intrinsic-test/src/types.rs
crates/intrinsic-test/src/values.rs

Notably, fix some warnings that flood the console, making it awkward to debug Arm tests.

Fix some minor intrinsic-test issues.

---

crates/core_arch/src/riscv_shared/mod.rs

This is the RISC-V version of https://github.com/rust-lang/stdarch/pull/1454.

riscv: deprecate intrinsics that cannot be used from Rust

---

crates/core_arch/src/powerpc/altivec.rs

Id' like to revert https://github.com/rust-lang/rust/pull/97276 since we didn't actually mean to support writing to mutable references in `const`. But that won't work if stdarch uses the stability attribute. I hope we can just remove it here, otherwise this will be a pain to land...

do not use const stability attribute when we don't even need to call the intrinsic in const

---

crates/intrinsic-test/README.md
crates/intrinsic-test/src/argument.rs
crates/intrinsic-test/src/format.rs
crates/intrinsic-test/src/intrinsic.rs
crates/intrinsic-test/src/main.rs
crates/intrinsic-test/src/types.rs

Basic indentation makes tests with deeply-nested scopes much easier to follow. Any more than this would be better done with `rustfmt` or `clang-format`, but simple indentation works for both languages and is enough to make the tests easy to follow and debug.
`--generate-only` is handy for quick iteration, and because it generates all tests, rather than stopping at the first one that fails to compile (or run).

Further debugability improvements for intrinsic-test.

---

ci/run.sh
crates/intrinsic-test/missing_arm.txt
crates/stdarch-test/src/lib.rs

These seem to have been introduced by recent LLVM changes.
* The instruction limit for vld*/vst* has been raised. This is not a significant issue, it is only used for testing.
* vld*/vst* instructions are generated with overly strict alignments: https://github.com/rust-lang/stdarch/issues/1217
* vtbl/vtbx instrinsics are failing intrinsic-test for unknown reasons.

Work around CI failures for the ARM target

---

crates/simd-test-macro/src/lib.rs
crates/stdarch-test/src/lib.rs

There's no way for a `#[test]` to dynamically decide if it should be skipped, sadly, but we can still print a message (with `--show-output`).

Report missing features when skipping tests.

---

crates/std_detect/src/detect/arch/riscv.rs

As shortly discussed on Zulip
(https://rust-lang.zulipchat.com/#narrow/stream/250483-t-compiler.2Frisc-v/topic/Stabilization.20of.20RISC-V.20Target.20Features/near/394793704), this commit PR the ratified RISC-V instruction bases and extensions.
Specifically, this PR stabilizes the:
* Instruction-Fetch Fence (Zifencei) on v2.0
* Control and Status Register (Zcsr) on v2.0
* Pause Hint (Zihintpause) on v2.0
* Zicntr and Zihpm were ratified March 2023
* ~Total Store Ordering (Ztso) on v1.0~
* Supervisor-level Instructions (S) on v1.12
* Atomic Instructions (A) on v2.0
* Compressed Instructions (C) on v2.0
* ~Double-Precision Floating-Point (D) on v2.2~
* Embedded Base (E) (Given as `RV32E` / `RV64E`) on v2.0
* ~Single-Precision Floating-Point (F) on v2.2~
* Integer Multiplication and Division …

Stabilize Ratified RISC-V Target Features

---

crates/core_arch/src/arm_shared/neon/mod.rs
crates/std_detect/src/lib.rs

Some details were missed in #1486 which caused build failures when integrated in std.

Fixes for use in the standard library

---

crates/std_detect/src/lib.rs

This is more fallout from #1486

Fix std build failure on non-x86 architectures

---

crates/core_arch/src/lib.rs
crates/std_detect/src/lib.rs
crates/std_detect/tests/macro_trailing_commas.rs
crates/std_detect/tests/x86-specific.rs
examples/connect5.rs
examples/hex.rs

Fix std_detect not being an unstable crate

---

.github/workflows/main.yml

This PR adds a new CI job that only succeeds if all other CI jobs have succeeded. This should make it easier to check if CI was green. After this PR, we can easily gate CI behind the "success" job in `team`, to avoid having to enumerate all the individual jobs, and to make sure that if new jobs are added in the future, they will be gated without having to modify `team`.

CI: add a success conclusion job

---

crates/core_arch/src/aarch64/neon/generated.rs
crates/stdarch-gen/neon.spec

vcgez/vclez now generate different (and more obvious) instructions.
fmadd/fmsub are now preferred over the slower fmla/fmls in more cases. I believe this is specific to the LANE=0 case, but I couldn't figure out how to switch testing to use LANE=1 without also breaking the case where only LANE=0 is valid.

Update test expectations for aarch64

---

crates/std_detect/src/detect/arch/aarch64.rs
crates/std_detect/src/detect/os/aarch64.rs
crates/std_detect/src/detect/os/linux/aarch64.rs
crates/std_detect/src/detect/os/macos/aarch64.rs

LLVM's `ssbs` and `mte` target_features represent two Arm features. Linux's HWCAP also represents the same two features, so this is just a documentation update.
LLVM's `ras` target_feature represents two Arm features - FEAT_RAS and FEAT_RASv1p1. There is no runtime detection for this, so this is a no-op in stdarch.
LLVM's `aes` feature covers both `FEAT_AES` and `FEAT_PMULL`, but Linux exposes seperate feature bits. This patch makes the `aes` target_feature correctly shortcut runtime `pmull` detection and also makes the `aes` feature check for `pmull` at runtime to bring it in line with the target_feature behaviour. In practice I think this makes the two runtime features identical since the ID_AA64ISAR0_EL1 register does not allow for PMULL without AES. I haven't added a `pmull` …

Improve feature detect for combined aarch64 features

---

crates/core_arch/src/simd_llvm.rs

These intrinsics are very tied to rustc so it's nicer to have them in the same repo as rustc. This also lets us share the definitions with portable-simd.
However it turns out some intrinsics are still missing on the rustc side, I will add them there. Also some intrinsics seem to be entirely unused:
- simd_reduce_min_nanless
- simd_reduce_max_nanless
- simd_fsin
- simd_fcos
- simd_fexp
- simd_fexp2
- simd_flog10
- simd_flog2
- simd_flog

import LLVM SIMD intrinsics from core rather than declaring them locally

---

crates/core_arch/src/aarch64/neon/generated.rs
crates/core_arch/src/aarch64/neon/mod.rs
crates/core_arch/src/arm_shared/neon/generated.rs
crates/core_arch/src/arm_shared/neon/mod.rs
crates/core_arch/src/macros.rs
crates/core_arch/src/simd.rs
crates/core_arch/src/wasm32/simd128.rs
crates/core_arch/src/x86/avx.rs
crates/core_arch/src/x86/avx2.rs
crates/core_arch/src/x86/avx512f.rs
crates/core_arch/src/x86/sse.rs
crates/core_arch/src/x86/sse2.rs
crates/core_arch/src/x86/sse41.rs
crates/core_arch/src/x86_64/avx.rs
crates/core_arch/src/x86_64/avx2.rs
crates/core_arch/src/x86_64/avx512f.rs
crates/core_arch/src/x86_64/sse2.rs
crates/core_arch/src/x86_64/sse41.rs
crates/stdarch-gen/neon.spec

In https://github.com/rust-lang/rust/issues/77477 the general consensus seems to be that these arguments should always be consts. So I have a patch for rustc that enforces them to be const. This is the stdarch side of this, adding const-blocks everywhere to ensure these arguments are const. I decided to follow the same pattern as simd_shuffle and add a macro that adds the const block.
However, there's one use of non-constant indices that can't be easily ported to use inline const blocks: the `extract` method on SIMD types, which is used (at least) by PowerPC tests. Also see [here](https://github.com/rust-lang/rust/issues/77477#issuecomment-1949910702).

put the idx arguments of simd_insert and simd_extract into const blocks

---

crates/core_arch/src/macros.rs

Directly giving a type hint by instantiating the simd_shuffle generics seems nicer.

simd_shuffle: remove unnecessary let binding

---

crates/core_arch/src/x86/avx.rs
crates/core_arch/src/x86/avx2.rs
crates/core_arch/src/x86/avx512bf16.rs
crates/core_arch/src/x86/avx512bw.rs
crates/core_arch/src/x86/avx512cd.rs
crates/core_arch/src/x86/avx512f.rs
crates/core_arch/src/x86/avx512vnni.rs
crates/core_arch/src/x86/f16c.rs
crates/core_arch/src/x86/mod.rs
crates/core_arch/src/x86/sha.rs
crates/core_arch/src/x86/sse.rs
crates/core_arch/src/x86/sse2.rs
crates/core_arch/src/x86/sse3.rs
crates/core_arch/src/x86/sse41.rs
crates/core_arch/src/x86/sse42.rs
crates/core_arch/src/x86/sse4a.rs
crates/core_arch/src/x86/ssse3.rs

These were introduced by rust-lang/rust#117772.

Fix redundant import warnings

---

crates/core_arch/src/x86/avx.rs
crates/core_arch/src/x86/avx512f.rs
crates/core_arch/src/x86/sse.rs
crates/core_arch/src/x86/sse2.rs
crates/core_arch/src/x86/sse4a.rs
crates/core_arch/src/x86_64/sse2.rs

This is my proposed alternative to https://github.com/rust-lang/stdarch/pull/1457. It builds on the model I sketched [here](https://github.com/rust-lang/rust/issues/114582#issuecomment-1674265397).
Changing the docs alone is not sufficient IMO, we also should stop using LLVM's non-temporal hint as LLVM passes do not properly take into account the non-standard nature of non-temporal stores. Originally I thought these all have to become inline assembly, but now I noticed that some of these operations are using different LLVM intrinsics:
```
#[link_name = "llvm.x86.sse4a.movnt.sd"]
fn movntsd(x: *mut f64, y: __m128d);
#[link_name = "llvm.x86.sse4a.movnt.ss"]
fn movntss(x: *mut f32, y: __m128);
```
Do these intrinsics exist for the other operations as well, e.g. for movntps? I found …

non-temporal stores: document interaction with Rust memory model

---

triagebot.toml

Recently we missed a ping due to this confusion: https://github.com/rust-lang/stdarch/issues/1479
I haven't added any labels since there didn't seem to be any that fit the ping groups exactly.

Add ping groups from Rust to stdarch

---

crates/std_detect/src/detect/arch/x86.rs
crates/std_detect/src/detect/os/x86.rs
crates/std_detect/tests/cpu-detection.rs
crates/std_detect/tests/x86-specific.rs

get cpuid number from https://cdrdv2-public.intel.com/678970/intel-avx512-fp16.pdf

std_detect: add avx512fp16

---

crates/core_arch/src/x86/avx.rs
crates/core_arch/src/x86/sse.rs
crates/core_arch/src/x86/sse2.rs
crates/core_arch/src/x86_64/sse2.rs

A follow-up to https://github.com/rust-lang/rust/pull/121556

Use `addr_of!`

---

crates/core_arch/src/x86/sse41.rs

Reported in rust-lang/rust#103058.
I searched for `_mm_insert_ps` in the rust repo and the behavior seems to be correct everywhere. Only this doc comment was messed up.
[Intel's documentation](https://www.intel.com/content/www/us/en/docs/intrinsics-guide/index.html#text=_mm_insert_ps)

[x86 SSE4.1] Correct `_mm_insert_ps` documentation

---

crates/std_detect/src/detect/os/x86.rs

reference: https://www.intel.com/content/dam/develop/external/us/en/documents/architecture-instruction-set-extensions-programming-reference.pdf
`avx512vp2intersect` is on page 26, `avx512bf16` is on page 27

fix: invalid bit for detecting avx512 feature

---

crates/std_detect/src/detect/arch/loongarch.rs
crates/std_detect/src/detect/os/linux/loongarch.rs

This PR removes features that are not supported by LLVM and adds LLVM target features that are detectable runtime:
* f
* d
* frecipe
* lbt

std_detect: loongarch: Sync runtime detectable features from LLVM

---

crates/core_arch/src/wasm32/mod.rs

For use in rust-lang/rust#121438. I was conservative in the wording of the docs cause I feel like this is the right place to put the intrinsic, but it likely won't be stabilized (at least in its current state).

[wasm32] Add an intrinsic for the throw instruction

---

crates/core_arch/src/x86/avx512f.rs

Fixes #1555 by changing the implementations of `_mm512_set4_epi64` and `_mm512_setr4_epi64` to use `_mm512_set_epi64`. This makes these implementations consistent with the other `_mm512_set[r]4_*` implementations as well as changes their behavior to be in line with what the intrinsics guide describes.

fix: reversed _mm512_set4_epi64 implementation

---

crates/core_arch/src/arm_shared/hints.rs
crates/core_arch/src/lib.rs

Support for Arm64EC inline assembly was recently added to Rust (<https://github.com/rust-lang/rust/pull/123507>), so we can enable functions that were previously disabled since they were implemented using inline assembly (namely `__nop`).

Use inline assembly for Arm64EC

---

crates/core_arch/src/aarch64/neon/generated.rs
crates/core_arch/src/aarch64/neon/mod.rs
crates/intrinsic-test/src/json_parser.rs
crates/stdarch-gen-arm/src/main.rs

See also: rust-lang/rust#117225

Stabilize AArch64 SHA3 intrinsics

---

crates/intrinsic-test/src/json_parser.rs

Remove duplicated `allow(dead_code)` attribute

---

crates/core_arch/src/powerpc/altivec.rs
crates/core_arch/src/powerpc/macros.rs

llvm uses some different encoding for splats

Power9 instructions tests

---

.github/workflows/main.yml
crates/core_arch/src/aarch64/neon/generated.rs
crates/core_arch/src/aarch64/neon/mod.rs
crates/core_arch/src/aarch64/tme.rs
crates/stdarch-gen-arm/neon.spec
crates/stdarch-gen-arm/src/main.rs
crates/stdarch-test/src/disassembly.rs

Enables testing for AArch64 Windows as "no run", as there are no AArch64 GitHub runners available.
* Fixes setting up the `GITHUB_ENV` for Windows (use Bash instead of PowerShell).
* Instruct dumpbin not to print the raw assembly bytes.
* Fix rewriting the `shll` instructions to handle dumpbin's format.
* Skip tests where dumpbin does not know how to handle the instruction.
* Rewrite `ins` as `mov` for MSVC.
* In one case, expect `dup` instead of `mov` for MSVC.

Enable testing for AArch64 Windows

---

crates/std_detect/Cargo.toml

@chrisdenton started a little project to make Windows targets not depend on libc. They already mostly don't, so I'm finishing things up. One of the obstacles to my own testing is that stdarch is dragging the libc rlib into the sysroot and making rustc's test suite pass when it shouldn't. Lol.

Don't depend on libc for cfg(windows)

---

.github/workflows/main.yml
crates/std_detect/src/detect/cache.rs

As noted in #1563, the only dependency on `libc` when building `stdarch` for Windows was a call to `getenv` when the `std_detect_env_override` feature was enabled. Since the `libc` dependency is only enabled for non-Windows platforms, enabling the `std_detect_env_override` feature on Windows would cause a build break.
This change replaces the use of `getenv` with a call to `GetEnvironmentVariableA` on Windows and enables testing the `std_detect_env_override` feature.
Fixes #1563
r? @ChrisDenton

Fix `std_detect_env_override` feature on Windows by avoiding `libc`

---

crates/core_arch/src/arm_shared/crc.rs
crates/core_arch/src/arm_shared/mod.rs
crates/intrinsic-test/src/main.rs

Stabilization for CRC32 intrinsics on ARM, for which the FCP has been completed
https://github.com/rust-lang/rust/issues/117215

feat: stabilization for stdarch_arm_crc32

---

crates/stdarch-test/src/lib.rs

These are generated as padding and are not actually part of the function.

Ignore int3 instructions when counting instructions in tests

---

crates/core_arch/src/x86/avx.rs
crates/core_arch/src/x86/avx2.rs

This intrinsic should have `target_feature` AVX, (according to Intel Intrinsics Guide) but had AVX2  ([Issue](https://github.com/rust-lang/stdarch/issues/1577))

Fixed `_mm256_cvtsd_f64`

---

crates/core_arch/src/powerpc/altivec.rs

Address https://github.com/rust-lang/rust/issues/126260

Use longer associated types in the Altivec traits

---

crates/core_arch/src/x86/avx.rs
crates/core_arch/src/x86/fma.rs
crates/core_arch/src/x86/sse.rs
crates/core_arch/src/x86/sse2.rs

Continuation of #790. Back then, there were instances where it was not possible to use the generic SIMD intrinsics due to LLVM bugs. These bugs have since then been fixed.

Use stdsimd instead of LLVM imports in more instances.

---

crates/core_arch/src/x86/adx.rs
crates/core_arch/src/x86_64/adx.rs

I don't know why these functions use `u8` in their signature, but surely they must actually be writing a u32/u64?
I also synced the doc comments between addcarry and addcarryx.

addcarryx: use pointers of the right type

---

crates/std_detect/src/detect/arch/x86.rs
crates/std_detect/src/detect/cache.rs
crates/std_detect/src/detect/os/x86.rs
crates/std_detect/tests/x86-specific.rs

Added run-time detection for 5 new x86 target features. Expanded the Cache size to 93.
- `AVX-IFMA`
- `AVX-NE-CONVERT`
- `AVX-VNNI`
- `AVX-VNNI_INT8`
- `AVX-VNNI_INT16`
Fixed run-time detection of `VAES`, `GFNI`, `VPCLMULQDQ` (they do not need `AVX512` support, the 512-bit versions need `AVX512F`, and that should be handled in target-feature attributes of the intrinsics.
See also the [rustc PR](https://github.com/rust-lang/rust/pull/126617)

Runtime detection of VEX variants of AVX512

---

crates/core_arch/src/wasm32/mod.rs
crates/core_arch/src/wasm32/relaxed_simd.rs

This is for https://github.com/rust-lang/rust/pull/117468, which has to be accepted (but not merged) first before this can be merged.
I also changed some functions to use the proper LLVM instructions instead of their aliases, see #1396.
Additionally I added aliases to unsigned variants when appropriate (as is done in SIMD128).
Fixes #1396.
~~Depends on #1523.~~

Stabilize Wasm relaxed SIMD

---

crates/core_arch/src/x86/sse41.rs

Fixes https://github.com/rust-lang/rust/issues/126935
This PR corrects the doc comment on the function and rewords it for clarity.
---
According to the issue linked above, the behavior of this function is correct and corresponds to [Intel's documentation](https://www.intel.com/content/www/us/en/docs/intrinsics-guide/index.html#text=_mm_blendv_epi8&ig_expand=487).
This can be verified by inspecting the unit tests here: [library/stdarch/examples/hex.rs](https://github.com/mtilda/stdarch/blob/c7eaae44727e626d2f61ae7510c6b91b8cb6919d/examples/hex.rs#L222-L318).
I am able to run these tests with the commands
```bash
cd examples
```
```bash
cargo +nightly test
```
_So far I have not gotten `ci/run.sh` to work correctly. I have also had no luck with the command `cargo +nightly test --example hex …

Fix documentation of arguments of function `core::arch::x86::_mm_blendv_epi8`

---

crates/core_arch/src/x86/cpuid.rs
crates/std_detect/src/detect/os/x86.rs
crates/std_detect/src/lib.rs

Implements the resolution of https://github.com/rust-lang/rust/issues/60123

Remove `has_cpuid`

---

crates/core_arch/missing-x86.md
crates/core_arch/src/x86/avx512ifma.rs

This adds the masked versions of the AVX IFMA intrinsics, completing the feature. This also fixes a test that was testing the wrong function.

Define remaining IFMA intrinsics

---

crates/core_arch/src/x86/avx512f.rs

Some of the masked reduction operations had bogus values for the masked out elements.

Fix incorrect reduction operations in avx512f

---

crates/core_arch/src/lib.rs
crates/core_arch/src/mod.rs
crates/std_detect/src/detect/arch/x86.rs
crates/std_detect/src/detect/os/x86.rs
crates/std_detect/tests/cpu-detection.rs
crates/std_detect/tests/x86-specific.rs

This is an effort towards [#126624](https://github.com/rust-lang/rust/issues/126624). This adds run-time detection for these target features.

Add Runtime detection for SHA512, SM3 and SM4

---

crates/std_detect/src/detect/arch/x86.rs
crates/std_detect/src/detect/os/x86.rs
crates/std_detect/tests/cpu-detection.rs
crates/std_detect/tests/x86-specific.rs

This is an effort towards feature [`x86_amx_intrinsics`](https://github.com/rust-lang/rust/issues/126622). This implements the runtime detection for the 5 target-features for AMX. This depends on Rustc PR [#126639](https://github.com/rust-lang/rust/pull/126639), and should be merged together.

Runtime detection for `AMX` target-features

---

crates/std_detect/src/detect/arch/x86.rs
crates/std_detect/src/detect/os/x86.rs
crates/std_detect/tests/cpu-detection.rs
crates/std_detect/tests/x86-specific.rs

This is an effort towards rust-lang/rust#127208. This Implements the runtime detection of `xop`.

Runtime detection of `xop` target-feature

---

crates/core_arch/src/x86/sse4a.rs
crates/core_arch/src/x86_64/mod.rs
crates/core_arch/src/x86_64/tbm.rs

The `extracti`, `inserti` and `bextri` intrinsics were implemented. They were left out because of #248. This also tidies up the `tbm` module and divides it into x86 and x86_64 specific modules. This completes all the `SSE4a` and `TBM` intrinsics. These are under rust-lang/rust#126936 `#[feature(simd_x86_updates)]`

Implement missing in `sse4a` and `tbm` intrinsics

---

crates/core_arch/src/x86/adx.rs
crates/core_arch/src/x86/avx512bw.rs
crates/core_arch/src/x86/avx512dq.rs
crates/core_arch/src/x86/avx512f.rs
crates/core_arch/src/x86/avxneconvert.rs
crates/core_arch/src/x86/bt.rs
crates/core_arch/src/x86/f16c.rs
crates/core_arch/src/x86/gfni.rs
crates/core_arch/src/x86/rtm.rs
crates/core_arch/src/x86/sse2.rs
crates/core_arch/src/x86_64/adx.rs
crates/core_arch/src/x86_64/avx512f.rs
crates/core_arch/src/x86_64/bt.rs
crates/stdarch-verify/src/lib.rs
crates/stdarch-verify/tests/arm.rs
crates/stdarch-verify/tests/mips.rs
crates/stdarch-verify/tests/x86-intel.rs

This PR fixes many broken links to the Intel Intrinsics Guide. It also adds functionality in `stdarch-verify` to check for mistakes in documentation.

Documentation Fixes in x86 intrinsics

---

crates/core_arch/src/wasm32/relaxed_simd.rs

It looks like LLVM requires that `simd128` is active to use these intrinsics and `relaxed-simd` isn't implicitly enabling them. This is probably something to fix at the LLVM layer as well but for now enable both the `simd128` feature as well as the `relaxed-simd` feature to fix things on our side.
This is done to help fix the test failure in #117468

wasm32: Add `simd128` to enabled features for relaxed intrinsics

---

crates/core_arch/src/wasm32/relaxed_simd.rs

This reverts https://github.com/rust-lang/stdarch/pull/1610.
The idea was to use this as a workaround until LLVM addresses it (see https://github.com/llvm/llvm-project/issues/98502).
It turned out that LLVM is likely to see this as something that should be fixed in the frontend, which has now been done in https://github.com/rust-lang/rust/pull/117468.
Cc @alexcrichton.

Revert "wasm32: Add `simd128` to enabled features for relaxed intrinsics"

---

crates/core_arch/src/x86/avx.rs
crates/core_arch/src/x86/avx512bw.rs
crates/core_arch/src/x86/avx512dq.rs
crates/core_arch/src/x86/avx512f.rs
crates/core_arch/src/x86/avx512vbmi2.rs

This PR removes most uses of inline asm in x86 stdarch
- masked load/stores
- expand-loads
- fp-class
This also removes some redundant `sse` target features from `avx` intrinsics

Use LLVM intrinsics instead of inline asm whereever possible

---

crates/core_arch/src/x86/avx2.rs
crates/core_arch/src/x86/bmi1.rs
crates/core_arch/src/x86/sse2.rs
crates/core_arch/src/x86/sse41.rs
crates/core_arch/src/x86/sse4a.rs
crates/core_arch/src/x86/tbm.rs
crates/core_arch/src/x86_64/tbm.rs

As per the FCP in rust-lang/rust#126936, this PR stabilizes the 13 new intrinsics.

Stabilize `simd_x86_updates`

---

crates/core_arch/src/wasm32/mod.rs
crates/core_arch/src/wasm32/relaxed_simd.rs

This moves the stabilization of Wasm's relaxed SIMD to Rust v1.82.
Related https://github.com/rust-lang/rust/pull/117468.
Thanks @sayantn for pointing this out in https://github.com/rust-lang/rust/pull/117468#issuecomment-2241656878.

Move Wasm's relaxed SIMD to Rust v1.82

---

crates/core_arch/Cargo.toml
crates/core_arch/missing-x86.md
crates/core_arch/src/lib.rs
crates/core_arch/src/x86_64/amx.rs
crates/core_arch/src/x86_64/mod.rs
crates/stdarch-verify/src/lib.rs
crates/stdarch-verify/tests/x86-intel.rs

As mentioned in [x86_amx_intrinsics](https://github.com/rust-lang/rust/issues/126622)
Completed AMX Intrinsics:
`amx-tile`
- _tile_loadconfig
- _tile_storeconfig
- _tile_loadd
- _tile_release
- _tile_stored
- _tile_stream_loadd
- _tile_zero
`amx-int8`
- _tile_dpbssd
- _tile_dpbsud
- _tile_dpbusd
- _tile_dpbuud
`amx-bf16`
- _tile_dpbf16ps
`amx-fp16`
- _tile_dpfp16ps
`amx-complex`
- _tile_cmmimfp16ps
- _tile_cmmrlfp16ps

initial commit to enable amx

---

crates/core_arch/src/x86/sse2.rs

I stumbled upon this while [reading the docs](https://doc.rust-lang.org/beta/core/arch/x86/fn._mm_unpackhi_pd.html).

Fix markdown list in docs

---

crates/core_arch/src/x86_64/macros.rs
crates/core_arch/src/x86_64/sse2.rs

Fixes #1541 by using `vps!`. This bypassed all CI tests because this only shows up for `gnux32` target. https://github.com/rust-lang/rust/pull/128608#issuecomment-2267099257

Fix `_mm_stream_si64`

---

crates/core_arch/src/mod.rs

This PR should be merged after rust-lang/rust#126704 gets merged and the nightly is available.

Remove the `dummy` function added in #1592

---

crates/core_arch/src/x86/mod.rs

The previous description was slightly implicit and at times misleading or wrong (i.e. with regards to alignment).
This is more precise.

Clarify the layout documentation for x86 SIMD types.

---

crates/core_arch/src/arm/dsp.rs
crates/core_arch/src/arm/simd32.rs
crates/core_arch/src/lib.rs
crates/core_arch/src/macros.rs
crates/core_arch/src/powerpc/vsx.rs
crates/core_arch/src/simd.rs
crates/core_arch/src/x86/fma.rs
crates/core_arch/src/x86/mod.rs

Avoids needing to import `crate::intrinsics::simd::simd_shuffle` in each file where `simd_shuffle!` is used and fixes loongarch64.

 Use full path to refer `simd_shuffle` intrinsic from `simd_shuffle!` macro

---

crates/core_arch/src/nvptx/mod.rs
crates/core_arch/src/nvptx/packed.rs

This implements parts of the `f16x2` intrinsics as discussed in https://github.com/rust-lang/rust/issues/125440#issuecomment-2128911257
It's unfortunately not possible to test that these intrinsics produce the correct instructions with the current test infrastructure. This was discussed on [zulip](https://rust-lang.zulipchat.com/#narrow/stream/208962-t-libs.2Fstdarch/topic/Running.20.23.5Bassert_instr.5D.20on.20a.20no_std.20target.20.28nvptx.29)
I have created assembly tests in my own branch of `rust-lang` repo that verifies the correct instructions are used. I have added `#[assert_instr]` attributes nonetheless. I'm not sure if it's desirable to follow up on `rust-lang` with a PR including the tests or not?

NVPTX: Add f16 SIMD intrinsics

---

crates/core_arch/src/aarch64/mod.rs
crates/core_arch/src/aarch64/mte.rs
crates/stdarch-verify/src/lib.rs
crates/stdarch-verify/tests/arm.rs

Adds intrinsic functions to `core_arch::aarch64` for MTE, as per the ACLE:
- __arm_mte_create_random_tag
- __arm_mte_increment_tag
- __arm_mte_exclude_tag
- __arm_mte_set_tag
- __arm_mte_get_tag
- __arm_mte_ptrdiff
These are unavailable without the `mte` target feature.

Add MTE intrinsics

---

crates/core_arch/src/macros.rs

See https://github.com/rust-lang/rust/issues/128738 for context.

simd_shuffle: pass the idx argument as a vector

---

crates/core_arch/src/macros.rs
crates/core_arch/src/x86/fma.rs
crates/core_arch/src/x86_64/avx.rs
crates/core_arch/src/x86_64/avx512f.rs
crates/core_arch/src/x86_64/sse2.rs
crates/core_arch/src/x86_64/sse41.rs

https://github.com/rust-lang/stdarch/pull/1630 did this for simd_shuffle, let's also do this for the other macros. Macros depending on imports in the modules where they are used is not a good style.

simd_extract, simd_insert: use absolute path in macro

---

.github/workflows/main.yml

Currently `NORUN=1` like `aarch64-apple-darwin`, that should change after https://github.com/rust-lang/stdarch/issues/1206.

Add Mac Catalyst to CI

---

crates/std_detect/src/detect/mod.rs
crates/std_detect/src/detect/os/darwin/aarch64.rs
crates/std_detect/tests/cpu-detection.rs
crates/stdarch-test/src/disassembly.rs
triagebot.toml

This was originally added in https://github.com/rust-lang/stdarch/pull/1516.
I have tested this in the simulator and on the device I had lying around, a 1st generation iPad Mini (which isn't Aarch64, but shows that the `sysctlbyname` calls still work even there, even if they return false).
`sysctlbyname` _should_ be safe to use without causing rejections from the app store, as its usage is documented in:
https://developer.apple.com/documentation/kernel/1387446-sysctlbyname/determining_instruction_set_characteristics
Also, the standard library will use `sysctl` soon anyhow, see https://github.com/rust-lang/rust/pull/129019, so _if_ the standard library starts getting rejected by Apple, it won't be entirely `stdarch`'s fault.

Enable Aarch64 feature detection on all Apple/Darwin targets

---

crates/std_detect/src/detect/os/freebsd/auxvec.rs
crates/std_detect/tests/cpu-detection.rs

[elf_aux_info](https://man.freebsd.org/elf_aux_info(3)) is a function that does the equivalent of our current sysctl-based archauxv, available in on FreeBSD 12.0+ (https://github.com/freebsd/freebsd-src/commit/0b08ae2120cdd08c20a2b806e2fcef4d0a36c470) and 11.4+ (backport by https://github.com/freebsd/freebsd-src/commit/03444a7d439755189e4dc8ccd56403bbaef3d6b0).
FreeBSD 11 support in std has been removed in Rust 1.75 (https://github.com/rust-lang/rust/pull/114521), so we can safely use this function.
(By the way, not directly related to this PR, but OpenBSD will provide the same function in the next release (7.6): https://github.com/openbsd/src/commit/ef873df06dac50249b2dd380dc6100eee3b0d23d)
Tested on powerpc64/powerpc64le FreeBSD 14.

std_detect: Use elf_aux_info on FreeBSD

---

crates/std_detect/src/detect/os/linux/mips.rs

https://github.com/rust-lang/stdarch/blob/b1edbf90955cb9b057a323f761e2c19edb591e6f/crates/std_detect/src/detect/os/linux/mips.rs#L18
This currently refers arm64 hwcap.h, but this file is for mips. (The values that used in this file is correct and just a link is wrong.)

std_detect: Fix link in mips.rs

---

crates/std_detect/src/detect/arch/aarch64.rs
crates/std_detect/src/detect/os/linux/aarch64.rs
crates/std_detect/tests/cpu-detection.rs

LLVM 20 split out what used to be called b16b16 and correspond to aarch64 FEAT_SVE_B16B16 into sve-b16b16 and sme-b16b16.
Add sme-b16b16 as an explicit feature and update the detection accordingly.

std_detect: Add sme-b16b16 as an explicit aarch64 target feature

---

crates/core_arch/src/x86/avx512vbmi2.rs

A very counterintuitive choice on Intel's part - the `shld` intrinsics pack its arguments like `a || b`, but the `shrd` intrinsics pack its arguments like `b || a`, and that was probably the cause of this bug.

Fix rust-lang/rust#130365

---

crates/core_arch/src/x86/xsave.rs
crates/core_arch/src/x86_64/xsave.rs

Ignore XSTATE_BV (state-component bitmap) that occupies the first byte of the XSAVE Header
(at offset 512 bytes from the start). The value may change, for more information see the following chapter:
13.7 OPERATION OF XSAVE - Intel® 64 and IA-32 Architectures Software Developer’s Manual.
Tested on `AMD Ryzen 9 7900X 12-Core Processor`.

Ignore `XSTATE_BV` when comparing `XTEST` XsaveArea

---

crates/core_arch/src/x86/avx512dq.rs
crates/core_arch/src/x86/avx512f.rs
crates/core_arch/src/x86/avx512fp16.rs
crates/core_arch/src/x86/f16c.rs
crates/core_arch/src/x86/sse41.rs
crates/core_arch/src/x86_64/avx512f.rs
crates/core_arch/src/x86_64/avx512fp16.rs

Before this change, one of the options is wrongly rendered (apparently anything single word after `:`):

Add space in order to fix rendering of Rounding options

---

crates/intrinsic-test/src/format.rs
crates/intrinsic-test/src/main.rs
crates/intrinsic-test/src/types.rs
crates/intrinsic-test/src/values.rs
crates/std_detect/src/detect/cache.rs
crates/stdarch-gen-loongarch/src/main.rs
crates/stdarch-test/src/disassembly.rs
crates/stdarch-test/src/lib.rs
crates/stdarch-verify/src/lib.rs

Minor linting

---

Cargo.toml
crates/core_arch/Cargo.toml

I am not certain why some crates are missing - it might be by accident or on purpose, so feel free to reject.  This makes sure no crate is missed by accident, and also removed the non-existent `wasm-assert-instr-tests` crate.
P.S. Also, added some crate-level lints, but perhaps these should be added to all crates in the workspace?

Add all crates to workspace

---

crates/std_detect/src/detect/arch/aarch64.rs
crates/std_detect/src/detect/os/linux/aarch64.rs
crates/std_detect/tests/cpu-detection.rs

Add feature detection for aarch64 FEAT_PAuth_LR.
There is currently no Linux cpuinfo support so the OS-specific lines are commented out.

std_detect: Add pauth-lr aarch64 target feature

---

crates/core_arch/src/lib.rs
crates/core_arch/src/wasm32/simd128.rs

We shouldn't need these feature gates any more, that was just an attempt at a transition that didn't quite work out.

cleanup wasm const fn

---

crates/core_arch/src/powerpc/altivec.rs

Like the name suggests, this converts to unsigned integers rather than signed. I assume this was copy pasted from `vec_cts`.

core_arch: powerpc: Fix documentation for vec_ctu

---

crates/core_arch/src/wasm32/mod.rs

Discovered in rust-lang/rust#132416. Before, it was outputting a `nounwind` attribute on `unwind::wasm::_Unwind_RaiseException`, which was definitely incorrect.

Use C-unwind abi for the llvm.wasm.throw intrinsic

---

.github/workflows/main.yml
ci/run.sh

Previous changes in Rust and LLVM have caused stdarch to be broken in debug (e.g. like those fixed in earlier PRs such as rust-lang/stdarch#1503) - this PR adds debug builds to the CI so that these breakages can be caught earlier.

ci: add debug testing

---

crates/std_detect/src/detect/arch/aarch64.rs
crates/std_detect/src/detect/arch/arm.rs
crates/std_detect/src/detect/arch/powerpc.rs
crates/std_detect/src/detect/arch/powerpc64.rs
crates/std_detect/src/detect/arch/riscv.rs
crates/std_detect/src/detect/arch/x86.rs
crates/std_detect/src/detect/macros.rs

This PR adds:
- the ability to declare a feature without cfg checking
- and mark every feature with missing corresponding target feature cfgs as such
This is a prerequisites to https://github.com/rust-lang/rust/pull/132577 which wants to enable reporting of the `unexpected_cfgs` lint in *external macros* and is unfortunately triggering on the macros call generated by stdarch, like `is_x86_feature_detected!`, ...
I have computed the list of missing target feature cfgs by comparing:
- `rg "[ ]+@feature: .*: \"(.*)\";" -r '$1' --no-filename crates/std_detect/src/detect/ | sort | uniq`
- with `tests/ui/check-cfg/well-known-values.stderr`[^1] (from the main Rust repo)
([actual.txt](https://github.com/user-attachments/files/17637673/actual.txt), …

Avoid using unexpected cfgs in user code

---

crates/core_arch/src/x86/avx512fp16.rs

These functions read from a pointer, so `readonly` has to be used instead of `nomem`.

Fix `asm!` options for `_mm_mask_load_sh` and `_mm_maskz_load_sh`

---

ci/run.sh

Looks like this was forgotten to be re-enabled when https://github.com/rust-lang/rust/issues/112460 was fixed

remove test --skip that references a long-closed issue

---

.github/workflows/main.yml
crates/core_arch/src/arm/dsp.rs
crates/core_arch/src/arm/simd32.rs

These were previously defined using vector types which is incorrect. Instead, `{u}int{8x4,16x2}_t` are aliases for `i32` and `u32`.
This also fixes CI since these types don't need to be passed in NEON registers and this was triggering a newly added compiler warning.

Fix types for ARM SIMD32 intrinsics

---

crates/core_arch/src/riscv_shared/p.rs

Fixes rust-lang/rust#129593.
Currently the P extension is still unratified, so there is no support for it in the upstream LLVM for now, and thus no LLVM built-in functions or serialization of instructions are provided.
This PR implements quick fixes to some of the instructions to fix them causing compilation failures (see issue rust-lang/rust#129593). Calling it a "quick fix" because ideally we could replace all `.insn` with LLVM built-in functions in the future when LLVM supports the P extension.
This PR also adds `assert_instr(unknown)` to each function so that we can at least make sure they compile. Since there is no serialization yet, the stdout of `assert_instr` is like
```
---- core_arch::riscv_shared::p::assert_kabs16_unkno1wn stdout ----
disassembly for …
```

Fix RISC-V Packed SIMD intrinsics compilation

---

CONTRIBUTING.md

Recommend using `run-docker.sh` instead of `run.sh` in `CONTRIBUTING.md`

---

crates/std_detect/src/detect/macros.rs

Enables the test that couldn't be enabled to the upstream PR not yet being merged, it is now done.
Follow up to https://github.com/rust-lang/stdarch/pull/1667

Enable `without cfg check` test in `std_detect`

---

crates/core_arch/src/simd.rs
crates/core_arch/src/wasm32/simd128.rs
crates/core_arch/src/x86/avx.rs
crates/core_arch/src/x86/avx2.rs
crates/core_arch/src/x86/avx512bf16.rs
crates/core_arch/src/x86/avx512bitalg.rs
crates/core_arch/src/x86/avx512bw.rs
crates/core_arch/src/x86/avx512cd.rs
crates/core_arch/src/x86/avx512dq.rs
crates/core_arch/src/x86/avx512f.rs
crates/core_arch/src/x86/avx512fp16.rs
crates/core_arch/src/x86/avx512vbmi.rs
crates/core_arch/src/x86/avx512vbmi2.rs
crates/core_arch/src/x86/avx512vnni.rs
crates/core_arch/src/x86/avx512vpopcntdq.rs
crates/core_arch/src/x86/gfni.rs
crates/core_arch/src/x86/sse.rs
crates/core_arch/src/x86/sse2.rs
crates/core_arch/src/x86/sse41.rs
crates/core_arch/src/x86/ssse3.rs

This PR adds a dedicated `ZERO` constant for the internal SIMD types and uses it intead of current idioms such as `splat(0)` or `setzero_pd().as_<type>()`. The result is improved code generation in non-optimized builds as well as a small line count reduction.

Rework SIMD zeroing

---

crates/std_detect/src/detect/macros.rs

The first rule of the `features` macro looks like this:
```
macro_rules! features {
(
@TARGET: $target:ident;
@CFG: $cfg:meta;
@MACRO_NAME: $macro_name:ident;
@MACRO_ATTRS: $(#[$macro_attrs:meta])*
$(@BIND_FEATURE_NAME: $bind_feature:tt; $feature_impl:tt; $(#[$deprecate_attr:meta];)?)*
$(@NO_RUNTIME_DETECTION: $nort_feature:tt; )*
$(@FEATURE: #[$stability_attr:meta] $feature:ident: $feature_lit:tt;
$(without cfg check: $feature_cfg_check:literal;)?
$(implied by target_features: [$($target_feature_lit:tt),*];)?
$(#[$feature_comment:meta])*)*
) => {
```
Notice all the `tt` specifiers. They are used because they are forwarded to another macro. Only `ident`, `lifetime`, and `tt` specifiers can be forwarded this way.
But there is an exception: `$feature_lit:tt`, which was added recently. In …

Fix the `features` macro.

---

crates/core_arch/src/lib.rs

It is not currently used, and given that coordinating unstable feature changes with a submodule is painful, it'd be better if we wouldn't use it in the future either. :)  (At least until https://github.com/rust-lang/stdarch/issues/1655 is resolved.)

remove rustc_allow_const_fn_unstable feature gate

---

crates/core_arch/src/x86/avx512f.rs

Simiarly to other functions for `mm` and `mm256` register widths, the first argument should be a pointer to the pointer type. See e.g. `_mm256_store_si256` function.

Fix signature of `_mm512_store{u,}_si512`.

---

.github/workflows/main.yml
crates/core_arch/src/wasm32/simd128.rs

This is a resubmission of #1609 which was ruled optional but not necessary at the time but it's now necessary. These weren't originally applied as they weren't allowed in a `const` context but that's no longer applicable. At the same time though be sure to add some small tests to ensure that these intrinsics can be used in a `const` context.

wasm: Add missing `#[target_feature]` to simd ctors

---

crates/core_arch/src/x86/sse2.rs

The documentation incorrectly stated that the function loads 16 bits of integer data.  This commit corrects the documentation to accurately reflect that the function loads  64 bits (8 bytes) of integer data from memory into a new vector.
closes rust-lang/rust#133062

Fix incorrect documentation for _mm_loadu_si64 function

---

crates/core_arch/src/wasm32/mod.rs

Tracking issue: https://github.com/rust-lang/rust/issues/133908
The recently added [`wasm32v1-none` target](https://doc.rust-lang.org/nightly/rustc/platform-support/wasm32v1-none.html) comes without `std`. This has caused some `f32` and `f64` methods to not be available for this target:
- [`f32/f64::ceil()`](https://doc.rust-lang.org/1.82.0/std/primitive.f32.html#method.ceil)
- [`f32/f64::floor()`](https://doc.rust-lang.org/1.82.0/std/primitive.f32.html#method.floor)
- [`f32/f64::trunc()`](https://doc.rust-lang.org/1.82.0/std/primitive.f32.html#method.trunc) and [`f32/f64::fract()`](https://doc.rust-lang.org/1.82.0/std/primitive.f32.html#method.fract)
- [`f32/f64::round_ties_even()`](https://doc.rust-lang.org/1.82.0/std/primitive.f32.html#method.round_ties_even)
- …

Add numeric instructions for Wasm not available in `core`

---

crates/core_arch/src/x86/avx2.rs
crates/core_arch/src/x86/avx512bf16.rs
crates/core_arch/src/x86/avx512f.rs
crates/core_arch/src/x86/avx512fp16.rs
crates/core_arch/src/x86/avxneconvert.rs
crates/core_arch/src/x86/sse2.rs
crates/core_arch/src/x86/sse41.rs
crates/core_arch/src/x86_64/amx.rs
crates/stdarch-verify/tests/x86-intel.rs

- Remove redundant target features - these were due to the inline asm requirement, which was removed with implied target features
- Use `core::intrinsics::fmaf16` in avx512fp16 intrinsics
- Add instruction assertions for AMX - `windows-gnu`, `apple-darwin` and `ios-macabi` targets are problematic as usual

Small fixes and cleanups

---

crates/core_arch/src/x86/fxsr.rs
crates/core_arch/src/x86/xsave.rs
crates/core_arch/src/x86_64/fxsr.rs
crates/core_arch/src/x86_64/xsave.rs

Remove buffers in tests for `{f,}xsave{c,}{64,}`

---

crates/core_arch/src/wasm32/mod.rs

Caught in https://github.com/rust-lang/rust/pull/134333.
While trying to figure out why this what not caught in the CI, I was unable to reproduce the error locally, `cargo doc --target wasm32-unknown-unknown` doesn't seem to do the trick. Maybe something to do with how `stdarch` interacts with `core` I don't understand.

Fix Wasm `f*_sqrt()` doc

---

crates/core_arch/src/x86/avx512bw.rs
crates/core_arch/src/x86/avx512f.rs

Fixing a small oversight.
Fixes: rust-lang/rust#133067

Fix the bug in CMPINT intrinsics with `IMM3=7`

---

crates/std_detect/src/detect/os/darwin/aarch64.rs

This reflects the currently available set of sysctl values as of macOS 15, on 2024-12-21.  Features not (yet) exposed by `is_aarch64_feature_detected` have been left in comments to document their existence for the future.
The only other changes this pull request makes are to align `pmull` and `aes` requirements, enable `pacg` as well as (the existing) `paca` when FEAT_PAuth is available, and sort and organize the various parts of the code for easier future extension.

Expand feature detection on AArch64 Darwin

---

crates/std_detect/README.md
crates/std_detect/src/detect/arch/mod.rs
crates/std_detect/src/detect/arch/s390x.rs
crates/std_detect/src/detect/mod.rs
crates/std_detect/src/detect/os/linux/auxvec.rs
crates/std_detect/src/detect/os/linux/mod.rs
crates/std_detect/src/detect/os/linux/s390x.rs
crates/std_detect/src/lib.rs
crates/std_detect/tests/cpu-detection.rs
crates/std_detect/tests/macro_trailing_commas.rs

tracking issue: https://github.com/rust-lang/rust/issues/135413
relevant issue: https://github.com/rust-lang/rust/issues/130869
this PR adds the `is_s390x_feature_detected` macro.
Is an ACP needed here? 
Below is a bunch of context.
This PR uses only the `getauxval` function. That is sufficient for the current feature flags.
Based on the official documents, the `stfl` instruction can/should be used to test for "[Facility Indications]". Unfortunately, it appears that this instruction can only be executed by the kernel, and in any case stores its result at address `200`, that users cannot read. Bummer.
There is also the `stfle` instruction, that provides more facility indications. We can actually use that from user space, e.g.
```rust
struct ExtendedFacilityList([u64; 4]);
impl …
```

add `is_s390x_feature_detected`

---

ci/docker/s390x-unknown-linux-gnu/Dockerfile
ci/run.sh
crates/core_arch/src/lib.rs
crates/core_arch/src/mod.rs
crates/core_arch/src/s390x/macros.rs
crates/core_arch/src/s390x/mod.rs
crates/core_arch/src/s390x/vector.rs
crates/simd-test-macro/src/lib.rs

adds `vector_add` and some general infrastructure to write more intrinsics for s390x.

add `vec_add` for `s390x`

---

crates/core_arch/src/x86/eflags.rs
crates/core_arch/src/x86/f16c.rs
crates/core_arch/src/x86/rdtsc.rs
crates/core_arch/src/x86/rtm.rs
crates/core_arch/src/x86/sse.rs
crates/core_arch/src/x86/sse41.rs
crates/core_arch/src/x86/xsave.rs
crates/core_arch/src/x86_64/tbm.rs
crates/core_arch/src/x86_64/xsave.rs
crates/std_detect/tests/cpu-detection.rs
crates/std_detect/tests/x86-specific.rs
crates/stdarch-verify/tests/x86-intel.rs

Remove the following tests in `sse.rs` due to UB
- `test_mm_comieq_ss_vs_ucomieq_ss`
- `test_mm_getcsr_setcsr_1`
- `test_mm_getcsr_setcsr_2`
- `test_mm_getcsr_setcsr_underflow`
Move all x86 std_detect tests to `x86-specific.rs` to reduce duplication

Fix some test naming, and refactor `stdarch-verify` in general

---

crates/core_arch/missing-x86.md
crates/core_arch/src/lib.rs
crates/core_arch/src/x86/kl.rs
crates/core_arch/src/x86/mod.rs
crates/std_detect/src/detect/arch/x86.rs
crates/std_detect/src/detect/os/x86.rs
crates/std_detect/tests/x86-specific.rs
crates/stdarch-test/src/disassembly.rs
crates/stdarch-test/src/lib.rs
crates/stdarch-verify/tests/x86-intel.rs

This is an effort towards rust-lang/rust#134813
`_mm_loadiwkey` is only allowed to be called from CPL0, so we are skipping testing it.

Add keylocker (`kl` and `widekl`) intrinsics and runtime feature detection

---

crates/core_arch/src/s390x/macros.rs
crates/core_arch/src/s390x/vector.rs

weird detail: `vec_and` is not implemented for `vector double`, but `vec_nand` is (and so on for the other operators). Not sure why that is, but uses that do need more flexibility can either transmute or use the `Simd` machinery.

S390x vector bitwise operations

---

.cirrus.yml
crates/core_arch/src/lib.rs

The 13.3 image is no longer provided by Google Cloud.

Update CI to FreeBSD 13.4

---

crates/core_arch/src/wasm32/simd128.rs

The wasm-specific intrinsics have been removed in https://github.com/llvm/llvm-project/pull/109405, use the generic ones instead.

Update wasm sub sat intrinsics for LLVM 20

---

crates/core_arch/src/x86/avx512f.rs

fix redundant transmutations
```
warning: this transmute could be performed safely
--> crates/core_arch/src/x86/avx512f.rs:29273:5
|
29273 |     transmute(r)
|     ^^^^^^^^^^^^ help: replace `transmute`: `i8::cast_unsigned(r)`
```
(many ([24](https://github.com/rust-lang/rust/pull/136083#issuecomment-2654467759)) such cases, this one is a transmute of `i8` -> `__mmask8`)

change redundant transmutations of sign to `cast_unsigned`

---

crates/core_arch/src/powerpc/altivec.rs
crates/core_arch/src/powerpc/macros.rs
crates/core_arch/src/simd.rs

These are available now, and much easier to support for miri and the gcc/cranelift backends then target-specific intrinsics.

powerpc: use more target-independent llvm intrinsics (`min`, `max`, `round`, `countlz`)

---

ci/run.sh
crates/core_arch/src/s390x/macros.rs
crates/core_arch/src/s390x/vector.rs

S390x float rounding

---

crates/core_arch/src/riscv32/zk.rs
crates/core_arch/src/riscv64/zk.rs
crates/core_arch/src/riscv_shared/zb.rs
crates/core_arch/src/riscv_shared/zk.rs

ACP: https://github.com/rust-lang/libs-team/issues/494

mark riscv intrinsics as safe

---

crates/std_detect/src/detect/arch/s390x.rs
crates/std_detect/src/detect/os/linux/s390x.rs

tracking issue: https://github.com/rust-lang/rust/issues/130869
follow-up to https://github.com/rust-lang/stdarch/pull/1699
with https://github.com/rust-lang/rust/pull/135630 merged, we can now also check for these facilities at runtime.
I am now using the `stfle` instruction to get the facilities. From what I can tell [`AT_HWCAP` ](https://github.com/torvalds/linux/blob/b62cef9a5c673f1b8083159f5dc03c1c5daced2f/arch/s390/include/asm/elf.h#L129-L152) does not include a bit for the `vector-packed-decimal` facility. Also the `stfle` version is just shorter, and I like that the factility bit index is now actually used.
@uweigand previously [said](https://github.com/rust-lang/rust/pull/135630#issuecomment-2598872726) that using the `stfle` instruction is safe because LLVM only supports CPUs …

`s390x_is_feature_detected!`: detect more features

---

crates/core_arch/src/powerpc/altivec.rs

quick followup to https://github.com/rust-lang/stdarch/pull/1713
I'm tracking down missed `simd_` usages with 
```
rg --pcre2 'llvm\.(?!x86|s390|aarch64|loongarch|arm|mips|riscv|org|nvvm|wasm|ppc)' .
```

powerpc: use `simd_ceil` and `simd_floor`

---

crates/core_arch/src/aarch64/neon/generated.rs
crates/core_arch/src/arm_shared/neon/generated.rs
crates/stdarch-gen-arm/spec/neon/aarch64.spec.yml
crates/stdarch-gen-arm/spec/neon/arm_shared.spec.yml
crates/stdarch-gen-arm/src/context.rs
crates/stdarch-gen-arm/src/expression.rs
crates/stdarch-gen-arm/src/intrinsic.rs

This removes the casting on unsigned LLVM intrinsics which broke a PR updating stdarch; https://github.com/rust-lang/rust/pull/136831

fix - neon type signed unsigned conversions

---

crates/core_arch/src/x86/mod.rs

The function calls in these doctests were switched to safe in https://github.com/rust-lang/stdarch/pull/1714 which broke these tests. This unblocks updating upstream.

Fix doctests failing due to unused_unsafe

---

crates/core_arch/src/wasm32/mod.rs

Updates the code to use the new intrinsic name introduced in https://github.com/rust-lang/rust/pull/136543 (which for now adds compatibility hacks to keep stdarch working).
This would all be a lot less work if stdarch were a proper subtree instead of a terrible submodule. :(

wasm: update for rintf intrinsic rename

---

crates/core_arch/src/powerpc/altivec.rs

I had hoped to also replace the implementation of
```rust
#[inline]
#[target_feature(enable = "altivec")]
#[cfg_attr(test, assert_instr(vnmsubfp))]
pub unsafe fn vec_vnmsubfp(a: vector_float, b: vector_float, c: vector_float) -> vector_float {
simd_neg(simd_fma(a, b, simd_neg(c)))
}
```
but that does not optimize for earlier versions of powerpc apparently https://godbolt.org/z/zvWfra8PT

powerpc: use the `simd_fma` intrinsic for `vec_madd`

---

crates/core_arch/src/powerpc/altivec.rs

another place where the general LLVM implementation can be used instead of the target-specific one.
https://llvm.org/docs/LangRef.html#llvm-fshl-intrinsic
This is another candidate for inclusion in `intrinsics::simd`, although I don't see how we could have a fallback MIR implementation for this one so the backends would need to implement it.

powerpc: use `llvm.fshl` for `vec_rl`

---

crates/core_arch/src/macros.rs
crates/core_arch/src/s390x/macros.rs
crates/core_arch/src/s390x/vector.rs

I'm not really sure how big these PRs should/could be. The commits are all separate, so I could break it up if that's easier.
The `as_{mut_}array` methods were added in preparation for https://github.com/rust-lang/compiler-team/issues/838, and are currently only used in tests.

s390x: add more intrinsics

---

crates/core_arch/src/x86/sse41.rs

Hopefully unblocks https://github.com/rust-lang/rust/pull/136831. Strangely, this doctest does not seem to be executed in stdarch CI, or the warning does not cause an error here.

fix unnecessary unsafe error in doctest

---

crates/core_arch/src/aarch64/neon/generated.rs
crates/core_arch/src/lib.rs
crates/intrinsic-test/missing_aarch64.txt
crates/intrinsic-test/src/main.rs
crates/stdarch-gen-arm/spec/neon/aarch64.spec.yml
intrinsics_data/arm_intrinsics.json

These intrinsics have been excluded from the tests because they require a Clang version with LLVM 20, and QEMU does not yet support the famax or famin instructions.

Feat - Aarch64 FEAT_FAMINMAX

---

crates/core_arch/src/aarch64/neon/generated.rs
crates/intrinsic-test/missing_aarch64.txt
crates/intrinsic-test/src/main.rs
crates/stdarch-gen-arm/spec/neon/aarch64.spec.yml
intrinsics_data/arm_intrinsics.json

This PR implements most of the FEAT_LUT intrinsics. However, some vluti2q_laneq intrinsics are missing due to an LLVM intrinsic selection issue; `rustc-LLVM ERROR: Cannot select: intrinsic %llvm.aarch64.neon.vluti2.laneq`
Tracking issue for `stdarch_neon_feat_lut`; https://github.com/rust-lang/rust/issues/138050

feat - FEAT_LUT neon instrinsics

---

ci/docker/x86_64-unknown-linux-gnu-emulated/Dockerfile

This is to combat the spurious CI failures in emulated run. Also helps with updatability and compatibility - it will work even if Intel changes the link

Update SDE mirror to ci-mirrors.rust-lang.org

---

crates/core_arch/src/s390x/macros.rs
crates/core_arch/src/s390x/vector.rs

well, final for now. I'm waiting on some changes to the `intrinsics::simd` insert and extract functions for some of the final intrinsics, and there are a couple very new intrinsics that even qemu will not run yet, so those will come when the tooling is there.
A bunch of optimization improvements to s390x have just been merged into LLVM, so when those are available (with the llvm 21 upgrade I assume) we should revisit some of the llvm comments and add/enable more instruction test cases.

s390x: final batch of intrinsics

---

crates/std_detect/src/detect/arch/riscv.rs

RISC-V runtime feature detection macro (`std::arch::is_riscv_feature_detected`) is stabilized on [Rust 1.78.0](https://doc.rust-lang.org/1.78.0/std/arch/macro.is_riscv_feature_detected.html), not [Rust 1.76.0](https://doc.rust-lang.org/1.76.0/std/arch/macro.is_riscv_feature_detected.html).

Fix: stabilized version of RISC-V feature macro

---

crates/std_detect/src/detect/arch/loongarch.rs
crates/std_detect/src/detect/os/linux/loongarch.rs

This patch adds new target features for LoongArch v1.1:
* div32
* lam-bh
* lamcas
* ld-seq-sa
* scq

std_detect: Add target features for LoongArch v1.1

---

crates/core_arch/src/x86/avx.rs
crates/core_arch/src/x86/avx512f.rs
crates/core_arch/src/x86/avx512fp16.rs
crates/core_arch/src/x86/sse.rs
crates/core_arch/src/x86/sse2.rs

also slightly expand their docs

use consistent wording around the 'undefined' intrinsics

---

crates/std_detect/src/detect/arch/x86.rs

These were causing compilation failures while stabilizing avx512, will be FCP'd soon, together with the rest of AVX512. So for a little while, any feature gate (except for `avx512_target_feature`) works

Temporary fix: change the feature gate of VEX variants

---

crates/std_detect/src/detect/os/windows/aarch64.rs

Windows now supports detecting SVE-related features.
Windows SDK:
mingw-w64:
https://github.com/mingw-w64/mingw-w64/commit/f97814b9602d62cec180aae9e0a0bb5198e7289d

std_detect: Support detecting more features on aarch64 Windows

---

crates/core_arch/src/x86/sse42.rs

to fix the `unsafe_op_in_unsafe_fn` lint.
Without this doctests for libcore fail on my machine.

sse42: Add unsafe blocks around unsafe function calls

---

crates/core_arch/src/x86/mod.rs

A 512-bit register is f64x8, not f64x4. Likely a copy-paste error from the _m256d documentation, which seems correct.

Minor correction to __m512d documentation.

---

crates/std_detect/src/detect/os/linux/riscv.rs

This error occurs when the RISC-V "A" Extension is being tested.
```rust
(b'a' - b'a')
```
This expression is detected as an error.

silence `clippy::eq_op` while checking

---

crates/core_arch/src/core_arch_docs.md
crates/core_arch/src/s390x/vector.rs

adds a link to the module docs, and uses the official intrinsic names as the title for the docs. I'm not sure what to do with the additional documentation, I've left it where i added it before, but really it's not our job to document these functions so we can also remove that text?

s390x: documentation fixes

---

ci/build-std-detect.sh
crates/std_detect/README.md
crates/std_detect/src/detect/os/linux/auxvec.rs

Similar to https://github.com/rust-lang/stdarch/pull/1375 (for `*-linux-gnu*`) and https://github.com/rust-lang/stdarch/pull/1406 (for `*-android*`), but for `-linux-{musl,ohos}*`:
* `*-linux-musl*` targets ([at least since Rust 1.15](https://github.com/rust-lang/rust/blob/1.15.0/src/ci/docker/x86_64-musl/build-musl.sh#L15)) use musl newer than [musl 1.1.0 that added `getauxval`](https://git.musl-libc.org/cgit/musl/tree/WHATSNEW?h=v1.1.0#n1197)
* `*-linux-ohos*` targets use a [fork of musl 1.2](https://gitee.com/openharmony/docs/blob/master/en/application-dev/reference/native-lib/musl.md)
On musl with static linking, there is a known problem that `getauxval` is not always available, independent of version requirements: https://github.com/rust-lang/rust/issues/89626
However, this seems to …

std_detect: Always avoid dlsym on *-linux-{musl,ohos}* targets

---

crates/core_arch/src/lib.rs

allows [unnecessary transmutes](https://github.com/rust-lang/rust/pull/136083) for `core_arch` to fix the issue in https://github.com/rust-lang/rust/pull/139009#issuecomment-2756647289
continuation of #1711

allow unnecessary transmutes in core_arch

---

crates/std_detect/src/detect/arch/riscv.rs

rust-lang/rust#138823 added five new extensions as compiler target features.
This commit reflects that fact and now checks static target features on `std::arch::is_riscv_feature_detected!` as well.
*   `Zicsr`
*   `Zicntr`
*   `Zihpm`
*   `Zifencei`
*   `Zihintpause`

RISC-V: check `cfg` (batch 1)

---

crates/std_detect/src/detect/arch/riscv.rs
crates/std_detect/src/detect/arch/x86.rs
crates/std_detect/src/detect/macros.rs

The stdarch update is currently giving doc errors, which #1767 fixes. But then it will give unknown cfg errors due to the recently added amx and riscv target features, so this pr temporarily disables those checks. Revert after the bump is successful

Disable cfg check for the recently-merged target features to allow stdarch update

---

ci/dox.sh
crates/core_arch/src/x86/avx512fp16.rs

there appears to have been some broken doc links here, which are inhibiting my stdarch update
this pr fixes those broken doc links.

fix broken intra doc links

---

crates/std_detect/src/detect/arch/riscv.rs

This PR updates the RISC-V definition file (`arch/riscv.rs`; mainly its documentation) for various parts (better links, indentation, more consistency on the extension naming and its capitalization).
This is a subset of upcoming PR but separate for being:
1. independent from the rest and
2. probably unarguable.
This PR consists of four commits:
1. Improve extension consistency (capitalization)
2. Move ratified extensions and make some clarification changes (by sorting or raising / lowering indentation)
3. Changing the ISA manual link ([before](https://github.com/riscv/riscv-isa-manual/) / [after](https://riscv.org/specifications/ratified/))  
while GitHub is a good place to browse the latest draft, it's hard to determine which is the ratified specification.  So, I think a page in RISC-V …

RISC-V: Tidying (batch 2025-04-11)

---

crates/std_detect/README.md
crates/std_detect/src/detect/arch/riscv.rs
crates/std_detect/src/detect/cache.rs
crates/std_detect/src/detect/mod.rs
crates/std_detect/src/detect/os/linux/riscv.rs
crates/std_detect/src/detect/os/riscv.rs
crates/std_detect/tests/cpu-detection.rs

This PR implements full `riscv_hwprobe`-based feature detection on newer Linux kernel and implements OS-independent extension implication logic to make extension handling easier.
This PR is a superset of #1769.
This PR is based on #1762 by @taiki-e.  Commits with @taiki-e's code (with or without modification) are marked by `Co-Authored-By`.
While the OS-independent logic in this PR uses iterators, I confirmed that LLVM is smart enough to optimize them into a series of bit-manipulation operations (multi-feature masking then multi-feature enablement).
The only reason why I originally made this PR as a draft is, I was not sure where to put new OS-independent RISC-V extension implication logic (`imply_features()`).
@taiki-e: suggested the path like `src/detect/os/riscv.rs`.
@taiki-e's …

RISC-V: `riscv_hwprobe`-based feature detection on Linux / Android

---

crates/std_detect/src/detect/os/linux/riscv.rs

Because the current lowest requirements to run the Linux kernel on RISC-V is RV{32,64}IMA (with 32 general purpose registers) plus some features, RV32E (with only 16 GPRs) is not currently supported.
Since it's not sure whether current implemented method will work for future Linux versions even if the minimum requirements are lowered, the support for RV32E (to be more specific, an attempt to do that) is removed for now.
Since Rust doesn't have any RV32E + Linux targets, it should be safe to do that and we can safely revert this:
*   If the method removed by this commit is confirmed working when the minimum requirements of the Linux kernel are lowered and is a preferred method for feature detection and
*   When an RV32E(something) + Linux target is going to be added to Rust.

std_detect: Remove RV32E support attempt on Linux (RISC-V)

---

crates/std_detect/src/detect/os/linux/auxvec.rs

This reverts commit 85572dc298f5222902c9b200cebf5d045e769a83.
This has been done in https://github.com/rust-lang/stdarch/pull/1421 due to libc issue that lacking getauxval on 32-bit Android, but libc issue has been fixed in libc 0.2.172 (https://github.com/rust-lang/libc/pull/4338).

Revert "std_detect: Do not use libc::getauxval on 32-bit Android"

---

crates/core_arch/src/x86/avx512f.rs
crates/core_arch/src/x86/avx512vbmi2.rs
crates/core_arch/src/x86/gfni.rs
crates/core_arch/src/x86_64/avx512f.rs
crates/stdarch-verify/tests/x86-intel.rs

For some intrinsics Intel specifies the pointer type as `void*` or `void const*`, but as Rust doesn't have void pointers, we need to choose a convention. This PR adds checks to ensure that convention.
This also fixes quite a few intrinsics (mainly in avx512vbmi2 and avx512f) that were not adhering to the conventions. The convention was chosen to maintain compatibility with SSE and AVX

Add checks for void pointer types to ensure consistency

---

crates/core_arch/src/s390x/vector.rs

This uses the `simd_extract_dyn` and `simd_insert_dyn` intrinsics (added in https://github.com/rust-lang/rust/pull/137447) to implement the four remaining s390x vector functions.

add `vec_extract`, `vec_insert`, `vec_promote` and `vec_insert_and_zero`

---

crates/core_arch/src/lib.rs
crates/core_arch/src/mod.rs

im not sure why the `#![allow]` in `lib.rs` doesnt take effect, but for some reason it doesnt: https://github.com/rust-lang/rust/pull/136083#issuecomment-2804984503
this might fix that? im not sure

attempt to `#[allow(unnecessary_transmutes)]` in neon

---

CONTRIBUTING.md

The `impl-period` tag has not been used with any current or previous issues. Therefore, I am removing the unnecessary reference to this tag from the CONTRIBUTING.md file

Remove impl_tag from CONTRIBUTING.md file

---

crates/core_arch/src/wasm32/atomic.rs
crates/core_arch/src/wasm32/memory.rs
crates/core_arch/src/wasm32/relaxed_simd.rs
crates/core_arch/src/wasm32/simd128.rs

See https://github.com/rust-lang/rust/pull/139809 for context.
Currently this crate uses a mix of "C" and "unadjusted", sometimes even for the same target -- no idea why. I would assume it should be "unadjusted" everywhere when importing an LLVM intrinsic? I don't want to make any sweeping changes in this PR though so this only touches wasm.
Cc @alexcrichton

use 'unadjusted' ABI for wasm LLVM intrinsics

---

.github/workflows/main.yml
ci/run-docker.sh
crates/core_arch/src/powerpc/altivec.rs

Two changes to tests were needed
`vrfin -> xvrspic` (changed in https://github.com/rust-lang/stdarch/pull/1713) 
- with older cpu types, it generates the same instruction https://godbolt.org/z/v7fW1fcrW
- but with newer ones, the new instruction is emitted https://godbolt.org/z/sYf5cKax8
So I think that means that this is fine? At least on s390x the rounding mode is not even relevant, this might be the case for powerpc too?
`vmaddfp -> xvmaddasp` (changed in https://github.com/rust-lang/stdarch/pull/1734)
That is just what C generates too now https://godbolt.org/z/5M8oT6fox
cc @lu-zero

run `powerpc64le` `assert_instr` on CI

---

ci/dox.sh
crates/core_arch/src/x86/avx512fp16.rs

- Re-enable `dox` CI for `armv7-unknown-linux-gnueabihf`
- Remove workarounds for llvm/llvm-project#98306

Remove the workarounds for some resolved issues

---

crates/core_arch/src/x86/avx.rs
crates/core_arch/src/x86/avx512f.rs
crates/core_arch/src/x86/avx512fp16.rs
crates/core_arch/src/x86/mod.rs
crates/core_arch/src/x86/sse.rs
crates/core_arch/src/x86/sse2.rs
crates/core_arch/src/x86/test.rs
crates/core_arch/src/x86_64/avx512fp16.rs

This does the required fixes to stdarch for rust-lang/rust#140389.
Also changes the tests for the same reason.
Related: llvm/llvm-project#136209, #1781, https://github.com/rust-lang/rust/pull/138940#issuecomment-2826131769

Fix errors in decoupling `avx512vl` and `avx512dq` from `avx512fp16`

---

crates/std_detect/src/detect/arch/riscv.rs

Reverts #1779.
This is due to a CI failure (technically broken HTML with duplicate IDs) caused by this commit (visibly fine but invalid per the HTML specification and detected by the LinkCheck tool on the Rust CI process).
The author independently working on a rustdoc enhancement to enable writing multiple references to a single footnote (rust-lang/rust#140434).
Once that change makes it to the stage0 compiler (the next beta), the original change will be acceptable again (postponed for possibly the version 1.89 cycle).
*   #1779 (RISC-V platform guide v1)
*   #1789 (RISC-V platform guide v2; will be merged once multiple references to a single footnote is made acceptable)
*   rust-lang/rust#140389 (CI failure mainly caused by 1779)  
To pass the CI on the Rust side, 1779 should be reverted …

Revert "std_detect: RISC-V platform guide documentation" (#1779)

---

crates/core_arch/missing-x86.md
crates/core_arch/src/arm_shared/neon/generated.rs
crates/core_arch/src/x86/sha.rs
crates/core_arch/src/x86/sse.rs
crates/stdarch-gen-arm/spec/neon/arm_shared.spec.yml
crates/stdarch-verify/src/lib.rs
crates/stdarch-verify/tests/x86-intel.rs

This PR implements all the SHA512, SM3 and SM4 intrinsics (rust-lang/rust#126624).
This also fixes a issue in stdarch-verify where it was silently not verifying most intrinsics as they were marked safe as part of `target_feature_11`.

Implement SHA512, SM3 and SM4 intrinsics

---

crates/std_detect/src/detect/os/x86.rs

The target feature `avx512f` implies `avx2`, `fma` and `f16c` in rustc, but Intel only guarantees that `avx2` will be there when `avx512f` is present, nothing about `fma` or `f16c`. This is correct behavior by rustc, and is based on how the assembler decides what encoding to use, VEX vs EVEX. So this PR simply requires that `fma` and `f16c` be present when enabling any AVX512 target features, to match exactly with rustc behavior.
Related:
- rust-lang/rust#138940
- rust-lang/rust#140389
- llvm/llvm-project#136209
- rust-lang/rust#111137

Require `fma` and `f16c` for `avx512f` in `std_detect`

---

crates/core_arch/src/x86/avx512f.rs
crates/core_arch/src/x86/avx512fp16.rs
crates/core_arch/src/x86/macros.rs

fixes: rust-lang/rust#140352
The avx512f errors were because the Intrinsics Guide was changed in v3.4 (see the discussion in the upstream issue), the avx512fp16 errors were just mistakes. These were all the errors I was able to find via a script, there might be more.

Fix errors in incorrect SAE and ROUNDING parameters

---

.github/workflows/main.yml
ci/docker/aarch64_be-unknown-linux-gnu/Dockerfile
ci/run-docker.sh
ci/run.sh
crates/core_arch/src/aarch64/neon/generated.rs
crates/core_arch/src/arm_shared/neon/table_lookup_tests.rs
crates/intrinsic-test/src/main.rs
crates/simd-test-macro/src/lib.rs
crates/std_detect/src/detect/os/linux/aarch64.rs
crates/std_detect/src/detect/os/linux/auxvec.rs
crates/stdarch-gen-arm/spec/neon/aarch64.spec.yml
crates/stdarch-test/src/lib.rs

Fixes issues that were surfaced through; https://github.com/rust-lang/stdarch/pull/1776#issuecomment-2817342718
I've not hooked this up to the ci as it seems there is a PR in tow that will do that; https://github.com/rust-lang/stdarch/pull/1785

fix - aarch64_be tests

---

.cirrus.yml
.github/workflows/main.yml
ci/docker/riscv32gc-unknown-linux-gnu/Dockerfile
ci/run.sh
crates/core_arch/src/aarch64/mte.rs
crates/core_arch/src/aarch64/neon/mod.rs
crates/std_detect/tests/macro_trailing_commas.rs
crates/stdarch-test/src/disassembly.rs

This PR adds CI support `riscv32gc-unknown-linux-gnu`
Fixes spurious segfaults in Cirrus CI
Adds support for running the `aarch64-pc-windows-msvc` runners in the new `windows-11-arm` runners

Add RISCV32 to CI, and use `windows-11-arm` runners for `aarch64-msvc` run

---

crates/std_detect/src/detect/arch/x86.rs

This PR stabilizes the runtime detection of the following target features
- `avxvnni`
- `avxifma`
- `avxvnniint8`
- `avxvnniint16`
- `avxneconvert`

Stabilize runtime detection of VEX variants of avx512

---

crates/core_arch/src/lib.rs
crates/core_arch/src/powerpc/altivec.rs
crates/intrinsic-test/src/intrinsic.rs
crates/intrinsic-test/src/main.rs
crates/std_detect/tests/x86-specific.rs
examples/connect5.rs

and enabling it causes errors on CI

`avx512_target_feature` is now stable on nightly

---

crates/core_arch/src/s390x/vector.rs

@uweigand and I discussed this, and this seemed like the better implementation.
Fundamentally, the condition code is a second return value. In C, a pointer is used because it just does not support multiple return values, but in rust we do. Hence, we decide to mirror LLVM (and not C) here by returning a tuple.

s390x vector: use a tuple to return the condition code

---

crates/std_detect/src/detect/arch/riscv.rs
crates/std_detect/src/detect/arch/x86.rs

Since the bootstrap compiler of Rust is bumped to the commit rust-lang/rust@5dadfd5c417f0b66816cb7ca662859e2c8751fb3 (version 1.88.0-beta.3 2025-05-11), some features should be safe to enable `cfg` checks.
This is a superset of the revert of #1768.
RISC-V Features:
*   "zicsr"
*   "zicntr"
*   "zihpm"
*   "zifencei"
*   "zihintntl"
*   "zihintpause"
*   "zimop"
*   "zicboz"
*   "zicond"
*   "ztso"
*   "zfa"
*   "zca"
*   "zcb"
*   "zcmop"
*   "b"
x86 Features:
*   "amx-avx512"
*   "amx-fp8"
*   "amx-movrs"
*   "amx-tf32"
*   "amx-transpose"

Check cfg on features that stage0 compiler support

---

crates/core_arch/src/x86_64/cmpxchg16b.rs

This is in preparation for https://github.com/rust-lang/rust/pull/141700.
Exposing `atomic_compare_exchange` just landed on master so we may have to wait for the next nightly before this can land here.

cmpxchg16b: use atomic_compare_exchange from libcore

---

ci/run.sh
crates/core_arch/src/aarch64/neon/generated.rs
crates/core_arch/src/arm_shared/neon/generated.rs
crates/core_arch/src/loongarch64/mod.rs
crates/core_arch/src/powerpc/altivec.rs
crates/core_arch/src/s390x/vector.rs
crates/core_arch/src/x86/avx.rs
crates/core_arch/src/x86/avx2.rs
crates/core_arch/src/x86/avx512bf16.rs
crates/core_arch/src/x86/rdtsc.rs
crates/stdarch-gen-arm/spec/neon/aarch64.spec.yml
crates/stdarch-gen-arm/spec/neon/arm_shared.spec.yml

see https://github.com/rust-lang/rust/pull/140763#issuecomment-2912252256 for context
This PR also starts checking for IR validity in tests, it is almost free, but adds a lot of confidence as we are dealing with LLVM intrinsics

Fix uses of invalid LLVM intrinsics

---

crates/std_detect/src/detect/os/linux/riscv.rs

As the author confirmed as in <https://lists.infradead.org/pipermail/linux-riscv/2025-May/070844.html>, runtime detection of the `Zicntr` extension (as in the Linux kernel 6.15) is currently (and technically) redundant on the current base IMA behavior (although can be meaningful if new base behavior is added).
This commit implies the `Zicntr` extension from the base IMA behavior.
Because I'm preparing `riscv_hwprobe` + Linux kernel 6.15 support PR and it depends on whether this change is acceptable, I consider this PR has higher priority than my other PRs (#1797 and #1798).

RISC-V: Linux: Imply `Zicntr` from the IMA base behavior

---

crates/intrinsic-test/src/arm/compile.rs
crates/intrinsic-test/src/arm/json_parser.rs
crates/intrinsic-test/src/arm/mod.rs
crates/intrinsic-test/src/arm/types.rs
crates/intrinsic-test/src/common/argument.rs
crates/intrinsic-test/src/common/cli.rs
crates/intrinsic-test/src/common/compile_c.rs
crates/intrinsic-test/src/common/gen_c.rs
crates/intrinsic-test/src/common/gen_rust.rs
crates/intrinsic-test/src/common/intrinsic_helpers.rs
crates/intrinsic-test/src/common/write_file.rs
crates/stdarch-gen-arm/src/big_endian.rs
crates/stdarch-gen-arm/src/context.rs
crates/stdarch-gen-arm/src/expression.rs
crates/stdarch-gen-arm/src/fn_suffix.rs
crates/stdarch-gen-arm/src/intrinsic.rs
crates/stdarch-gen-arm/src/load_store_tests.rs
crates/stdarch-gen-arm/src/main.rs
crates/stdarch-gen-arm/src/typekinds.rs
crates/stdarch-gen-arm/src/wildstring.rs
crates/stdarch-gen-loongarch/src/main.rs
crates/stdarch-test/src/lib.rs
crates/stdarch-verify/src/lib.rs
examples/connect5.rs

In the development of `stdarch`, we encounter many warnings (mainly from Clippy; currently 133 as counted by Rust Analyzer and 132 as counted by `cargo clippy`) and hid real warnings we need to take care of.
However, the author found that source of such changes are mainly from old Rust code (which does not know newer coding styles) and decided to deal with it by this PR.
I allowed `clippy::collapsible_if` for now (to be reviewed) because it's just nested `if`s.
I allowed `clippy::obfuscated_if_else` because a candidate to fix this issue looked more complex than before.
I allowed `clippy::manual_range_contains` (as suggested by @Amanieu) because *fixing* the warning will complicate the code.
Other than that, I mostly used suggestions generated by Clippy.
In …

Coding style modernization to deal with Clippy warnings

---

crates/std_detect/src/detect/arch/riscv.rs
crates/std_detect/src/detect/os/linux/riscv.rs
crates/std_detect/src/detect/os/riscv.rs
crates/std_detect/tests/cpu-detection.rs

This commit adds support for `riscv_hwprobe` on the Linux kernel 6.15. It adds feature detection of 8 extensions (4 of them are new in this).
Existing RISC-V Extensions:
1.  `Zicntr`
2.  `Zihpm`
3.  `Zalrsc`
4.  `Zaamo`
New RISC-V Extensions:
5.  `Zicbom`
6.  `Zfbfmin`
7.  `Zvfbfmin`
8.  `Zvfbfwma`
Note: four new extensions are already added to beta (cf. rust-lang/rust#140507) and checking `cfg` should be okay.

RISC-V: Linux 6.15 `riscv_hwprobe` support

---

crates/core_arch/src/aarch64/neon/generated.rs
crates/core_arch/src/aarch64/neon/mod.rs
crates/core_arch/src/arm_shared/neon/generated.rs
crates/core_arch/src/wasm32/simd128.rs
crates/core_arch/src/x86/avx512dq.rs
crates/core_arch/src/x86/avx512fp16.rs
crates/stdarch-gen-arm/spec/neon/aarch64.spec.yml
crates/stdarch-gen-arm/spec/neon/arm_shared.spec.yml

- Use rust intrinsics for more ARM intrinsics
- Fix incorrect intrinsic names (these were autoupgraded by LLVM, so didn't result in invalid IR)
- Remove uses of deprecated type-specific pointers, LLVM only supports opaque pointers now.
@folkertdev is it okay to replace the `llvm.{u,s}{max,min}` calls with something like `simd_select(simd_gt(a, b), a, b))`? I am just worried if it will optimize well
edit: seems like it is not a problem actually https://godbolt.org/z/6r1javWc6

Fix some more uses of LLVM intrinsics

---

crates/std_detect/Cargo.toml

Since [1], this will come automatically from `rustc-std-workspace-core` and the crates.io dependency should no longer be specified.
[1]: https://github.com/rust-lang/rust/pull/141993

Remove `compiler-builtins` from `rustc-dep-of-std` dependencies

---

triagebot.toml

Adds checking of PR descriptions to avoid relative issue links (without repository prefix) and mentions in commits.
I didn't enable checking of relative issue links in commits, see discussion in https://github.com/rust-lang/compiler-builtins/pull/956.
We should also add a `[no-merges]` policy, but I haven't yet added the josh sync tooling here, so we don't know the PR title prefix that we will use, so we can do that later.

Add triagebot config for subtree syncs

---

crates/core_arch/src/lib.rs
crates/std_detect/src/detect/arch/s390x.rs
crates/std_detect/src/detect/os/linux/s390x.rs

tracking issue: https://github.com/rust-lang/rust/issues/130869
I didn't add feature detection yet in https://github.com/rust-lang/stdarch/pull/1826. 
The implementation follows the information in https://github.com/rust-lang/rust/issues/135413#issuecomment-2886439455, in particular that `HWCAP` is used to check for the `vector` feature because it needs kernel support, and `stfle` is used for the other features because they only need hardware support.
cc @uweigand @taiki-e

s390x: z17 target feature detection

---

crates/core_arch/src/powerpc/macros.rs
crates/core_arch/src/s390x/macros.rs
crates/core_arch/src/s390x/vector.rs
crates/core_arch/src/wasm32/simd128.rs
crates/core_arch/src/x86_64/cmpxchg16b.rs

And some various other things reported by clippy.
extracted from https://github.com/rust-lang/rust/pull/143477

use `is_multiple_of` to check if an addr is aligned

---

crates/core_arch/src/x86/kl.rs
crates/core_arch/src/x86/mod.rs
crates/core_arch/src/x86/sha.rs
crates/std_detect/src/detect/arch/x86.rs

These were left as `CURRENT_RUSTC_VERSION` in the submodule.

Update stabilization version of certain x86 intrinsics to 1.89

---

Cargo.lock
crates/core_arch/Cargo.toml
crates/core_arch/src/lib.rs
crates/simd-test-macro/src/lib.rs

Instead of `core_arch` loading the `is_XYZ_feature_enabled` macros from the local `std_detect` crate, they are loaded from `::std::arch` instead. This means that nothing in this repository will depend on `std_detect` anymore (except for tests, these will be ported later). The downside is that `core_arch` will need to wait for nightly std bumps to see changes in the detection macros, but I assume that should be rare.
This is one of the steps required to move `std_detect` fully into `rust-lang/rust`.

Remove `std_detect` dev dependency in `core_arch`

---

crates/std_detect/src/detect/os/linux/riscv.rs

Originally, we used an array of `riscv_hwprobe` directly and indexed using raw numbers, making correspondence between the index and the query key less obvious.
We also frequently used `out[idx].key != -1` to test whether the key is supported by the `riscv_hwprobe` system call (on the Linux kernel version we are testing) but we'd better to integrate with an operation to retrieve the value.
This commit improves the ergonomics of feature querying by:
1.  Utilizing macros to
1.  enable indexing by identifier names and
2.  encapsulate accesses to the `riscv_hwprobe` array to query and
2.  New method `riscv_hwprobe::get()` returning `Option<u64>`, integrating availability checking and value retrieval.
It also removes `has_ima` for now because it's redundant if we only need to test for single …

std_detect: RISC-V Linux: Ergonomic querying with `riscv_hwprobe`

---

crates/core_arch/src/arm_shared/neon/generated.rs
crates/stdarch-gen-arm/spec/neon/arm_shared.spec.yml

cc https://github.com/rust-lang/stdarch/issues/1659
use our own simd splat to generate these, cutting down on platform-specific intrinsics.

use `splat` for the aarch64/arm dup intrinsics

---

crates/core_arch/src/arm_shared/neon/generated.rs
crates/stdarch-gen-arm/spec/neon/arm_shared.spec.yml

turns out floats are hard and our current instruction tests don't catch the error if `fmin` is expected but `fminmn` is actually used.

aarch64: use `core::intrinsics::simd` for integer min/max

---

Cargo.lock
crates/intrinsic-test/src/arm/config.rs
crates/intrinsic-test/src/arm/mod.rs
crates/intrinsic-test/src/common/cli.rs
crates/intrinsic-test/src/common/compare.rs
crates/intrinsic-test/src/common/gen_rust.rs
crates/intrinsic-test/src/main.rs

Let's see what this does on CI. It uses `runner` also for running the rust programs, so that they can be run outside of the docker container (assuming qemu and clang etc.)

`intrinsic-test`: use runner also for rust

---

.github/workflows/rustc-pull.yml

This CI workflow will run the https://github.com/rust-lang/josh-sync tool on Mondays and Thursdays. It will try to do a pull (sync stdarch changes from rust-lang/rust into this repository). When it runs, three things can happen:
- There are no rustc changes to be pulled, the bot does nothing.
- There are some new changes to be pulled. In that case, the bot will either open or update an existing PR titled "Rustc pull update" on this repository with the changes. After the PR is merged, we should ideally do the opposite sync (push) manually.
- The pull fails (usually because of a merge conflict), or the bot determines that a pull PR has been opened for more than a week without being merged. In that case, it will post a ping to https://rust-lang.zulipchat.com/#narrow/channel/208962-t-libs.2Fst …

Add rustc-pull CI automation workflow

---

crates/core_arch/src/aarch64/neon/generated.rs
crates/core_arch/src/arm_shared/neon/generated.rs
crates/stdarch-gen-arm/spec/neon/aarch64.spec.yml
crates/stdarch-gen-arm/spec/neon/arm_shared.spec.yml

cc https://github.com/rust-lang/stdarch/pull/1858 https://github.com/rust-lang/stdarch/issues/1659

`aarch64`: use more of `intrinsics::simd` for min/max

---

Cargo.lock
crates/intrinsic-test/src/arm/compile.rs
crates/intrinsic-test/src/arm/mod.rs
crates/intrinsic-test/src/common/compile_c.rs
crates/intrinsic-test/src/common/gen_c.rs

Preparation for combining the C files. That is the biggest speedup, so I want to do that first to make later refactorings less painful.

`intrinsic-test`: streamline c compilation

---

crates/intrinsic-test/src/arm/intrinsic.rs
crates/intrinsic-test/src/arm/json_parser.rs
crates/intrinsic-test/src/arm/types.rs
crates/intrinsic-test/src/common/argument.rs
crates/intrinsic-test/src/common/intrinsic_helpers.rs

1. Moved the return type of IntrinsicType::from_c to Rust<Self, String> from Result<Box<Self>, String>
2. Implemented DerefMut for ArmIntrinsicTest struct
This PR is part 2 of the changes that were originally made in the x86 extension PR rust-lang/stdarch#1814 for intrinsic-test, and is intended to unblock the speedup efforts that are being made in PRs rust-lang/stdarch#1856 , rust-lang/stdarch#1862 and rust-lang/stdarch#1863.

`intrinsic-test`: Implemented DerefMut for ArmIntrinsicTest

---

Cargo.toml
crates/intrinsic-test/src/arm/mod.rs
crates/intrinsic-test/src/common/argument.rs
crates/intrinsic-test/src/common/compare.rs
crates/intrinsic-test/src/common/compile_c.rs
crates/intrinsic-test/src/common/gen_c.rs
crates/intrinsic-test/src/common/write_file.rs

There are 3 main changes
- emit the arguments (the arrays of inputs) inside of the test function, and rename the test function from `main` to `run_{intrinsic_name}`.
- generate number-of-cores files, and evenly divide all intrinsics over these files. Each file now has the functions for running many different intrinsic tests
- generate a `main` that is just a gigantic switch to select the right test to run
Parts of this are still inefficient, and for the full effect the rust side also needs work, but I suspect this is the biggest win (if not, it's actually cargo, we'll see I guess), and sort of a manageable change to review (hopefully).

`intrinsic-test`: combine C files for faster compilation

---

crates/core_arch/src/x86/sse2.rs

Like any other non-temporal instructions this has additional safety requirements due to the mismatch with the Rust memory model. It is vital to know when using this instruction.
---
This is a case where some form of safety property system would grow on me. If downstream users of this intrinsic instruction failed to reason about sfence they will not get any warnings about this safety-requirements bug fix.

Add non-temporal note for maskmoveu_si128

---

crates/core_arch/src/loongarch64/lasx/generated.rs
crates/core_arch/src/loongarch64/lasx/types.rs
crates/core_arch/src/loongarch64/lsx/generated.rs
crates/core_arch/src/loongarch64/lsx/types.rs
crates/stdarch-gen-loongarch/src/main.rs

loongarch: Use unified data types for SIMD intrinsics

---

crates/intrinsic-test/src/arm/argument.rs
crates/intrinsic-test/src/arm/json_parser.rs
crates/intrinsic-test/src/arm/mod.rs
crates/intrinsic-test/src/common/argument.rs

1. Moved the `type_and_name_from_c` function of `Argument<T>` to the architecture-specific `Argument<ArmArchitecture>` struct, since this specific functionality exists only to serve how ARM intrinsics are defined.
Example:
```JS
{
"SIMD_ISA": "Neon",
"name": "__crc32b",
// The below values (of "arguments") would be passed into the `type_and_name_from_c` function
"arguments": [
"uint32_t a",
"uint8_t b"
],
"return_type": {
"value": "uint32_t"
},
},
```
This PR is part of the changes that were originally made in the x86 extension PR rust-lang/stdarch#1814 for intrinsic-test, and is intended to accomodate the changes made in PRs  rust-lang/stdarch#1862 and rust-lang/stdarch#1863.
cc: @folkertdev @Amanieu

Feat: updated Argument<T> type for functional compatibility with other architectures

---

crates/intrinsic-test/src/arm/mod.rs
crates/intrinsic-test/src/common/gen_rust.rs

1. Added support for the case when the `--generate-only` flag is passed. This helps with generating the Rust and C artifacts even if the compilation environment is not supported
This PR is part of the changes that were originally made in the x86 extension PR rust-lang/stdarch#1814 for intrinsic-test, and is intended to accomodate the changes made in PRs  rust-lang/stdarch#1862 and rust-lang/stdarch#1863.
cc: @folkertdev @Amanieu

`intrinsic-test`: bringing back support for  --generate-only flag

---

crates/intrinsic-test/src/arm/intrinsic.rs
crates/intrinsic-test/src/arm/json_parser.rs
crates/intrinsic-test/src/arm/mod.rs
crates/intrinsic-test/src/arm/types.rs
crates/intrinsic-test/src/common/intrinsic_helpers.rs
crates/intrinsic-test/src/common/mod.rs

1. Changed from `IntrinsicType::target` to `ArmIntrinsicType::target` since its usage is highly architecture-dependent.
2. Changed the structure of `ArmIntrinsicType` from 
```Rust
pub struct ArmIntrinsicType(pub IntrinsicType);
```
to 
```Rust
pub struct ArmIntrinsicType {
pub data: IntrinsicType,
pub target: String,
}
```
3. Moved `arm::chunk_info` to `common::chunk_info`.
4. Removed `from_c` in `IntrinsicTypeDefinition` trait. 
r? @folkertdev 
cc: @Amanieu

`intrinsic-test`: Cleaning the `IntrinsicType` struct and related functionalities

---

crates/intrinsic-test/src/arm/compile.rs
crates/intrinsic-test/src/common/compile_c.rs

`intrinsic-test`: use `IntoIterator` for the `add_flags` methods 

---

crates/core_arch/src/lib.rs
crates/core_arch/src/s390x/vector.rs
crates/core_arch/src/x86/avx512f.rs
crates/core_arch/src/x86/avx512fp16.rs
crates/core_arch/src/x86_64/avx512f.rs

This fixes a number of issues after the LLVM upgrade:
* Drop no longer needed feature gates (unrelated, just needed to work with current nightly)
* Use intrinsics for some operations on s390x, as these are no longer recognized after https://github.com/rust-lang/rust/pull/145144 (fixed upstream by https://github.com/llvm/llvm-project/pull/153557).
* Add missing avx512vl features to tests using assert_eq_m128h. This avoid a selection failure (github.com/llvm/llvm-project/issues/153570), but is also necessary for correctness.
* Added some more avx512vl features to tests to work around another selection failure (https://github.com/llvm/llvm-project/issues/154492). These should get removed once the issue is fixed.
* Adjusted immediate for vrndscalepd tests to ensure they actually use scaled …

Fix CI after LLVM upgrade

---

crates/core_arch/src/arm_shared/neon/generated.rs
crates/stdarch-gen-arm/spec/neon/arm_shared.spec.yml

The idea behind this is that e.g. miri and cranelift don't know all of the llvm intrinsics (and adding them is possible but a lot of extra work). Using the generic simd function means logic only needs to be implemented once for all targets.
The `simd_saturating_*` functions generate the same instructions for the saturating add/sub operations https://godbolt.org/z/zc35doTc6

use `simd_saturating_{add, sub}` on neon

---

Cargo.lock
crates/intrinsic-test/src/arm/config.rs
crates/intrinsic-test/src/arm/intrinsic.rs
crates/intrinsic-test/src/arm/mod.rs
crates/intrinsic-test/src/arm/types.rs
crates/intrinsic-test/src/common/gen_c.rs
crates/intrinsic-test/src/common/gen_rust.rs
crates/intrinsic-test/src/common/intrinsic.rs
crates/intrinsic-test/src/common/intrinsic_helpers.rs
crates/intrinsic-test/src/common/mod.rs
crates/intrinsic-test/src/main.rs

Most of the tricky logic of `SupportedArchitectureTest` is now in the trait, making it a lot easier, and shorter, to define new variants. That should make the x86 work a lot simpler.
best reviewed commit-by-commit I think.
cc @madhav-madhusoodanan

`intrinsic-test`: make `build_{c, rust}_file` generic

---

crates/core_arch/src/aarch64/neon/generated.rs
crates/core_arch/src/arm_shared/neon/generated.rs
crates/stdarch-gen-arm/spec/neon/aarch64.spec.yml
crates/stdarch-gen-arm/spec/neon/arm_shared.spec.yml

Fixes: rust-lang/stdarch#1904 
This is the correct behavior according to the [Intrinsics Guide](https://developer.arm.com/architectures/instruction-sets/intrinsics/vreinterpret_s16_s8), which specifies that these should compile to `NOP`. Also, GCC and Clang matches this behavior.
I am a bit surprised that this didn't get caught in the AArch64_BE `intrinsic_test` run!

Remove big-endian swizzles from `vreinterpret`

---

crates/core_arch/src/riscv64/mod.rs
crates/core_arch/src/riscv_shared/mod.rs

This commit performs various improvements (better register allocation, less register clobbering on the worst case and better readability) of RISC-V inline assembly use cases.
Note that it does not change the `p` module (which defines the "P" extension draft instructions but very likely to change).
1.  Use `lateout` as possible.  
Unlike `out(reg)` and `in(reg)` pair, `lateout(reg)` and `in(reg)` can share the same register because they state that the late-output register is written after all the reads are performed. It can improve register allocation.
2.  Add `preserves_flags` option as possible.  
While RISC-V doesn't have _regular_ condition codes, RISC-V inline assembly in the Rust language assumes that some registers (mainly vector state registers) may be overwritten by default. By …

RISC-V: Improvements of inline assembly uses

---

crates/core_arch/src/x86/avx512bw.rs
crates/core_arch/src/x86/avx512dq.rs
crates/core_arch/src/x86/avx512f.rs

The `_kshiftri_mask32`, `_kshiftri_mask64`, `_kshiftli_mask32` and `_kshiftli_mask64` intrinsics in `core_arch::x86` module do not handle a critical edge case when the shift amount exceeds the bit-length of the input argument. 
EDIT: updated the 8-bit and 16-bit versions of the same.
For `_kshiftri_mask32` and `_kshiftli_mask32` intrinsics, when the shift amount (passed as a const-generic argument) exceeds 32, the shift amount applied to the argument becomes `shift % 32`.
Similar is the case with the 8-bit, 16-bit and 64-bit variants of the same.
[Godbolt link for the 32-bit variant with minimal replication](https://godbolt.org/z/oKea3d55f).
[Godbolt link for the 64-bit variant with minimal replication](https://godbolt.org/z/EbGhh7eo8).
When the shift amount exceeds 32 (for the 32-bit …

`core_arch::x86` : Fix the implementation of `_kshift` instructions

---

crates/core_arch/src/x86/avx2.rs
crates/core_arch/src/x86/avx512bw.rs
crates/core_arch/src/x86/avx512f.rs
crates/core_arch/src/x86/avx512vbmi2.rs

The x86 shift intrinsics do an overflowing shift (i.e. 0 in case of shift larger than type size), instead of wrapping shift (i.e. shift amount is taken modulo type size). So, we can't use `simd_sh{l,r}` here.
Also, `simd_funnel_sh{l,r}` doc says its UB for the shift amount to be greater than or equal to the type size. So, and them with `T::BITS - 1` to ensure soundness (LLVM is clever enough to sees through it, there is no codegen impact)

Fix mistake in #1928

---

crates/core_arch/src/x86/avx512fp16.rs

I somehow missed these in rust-lang/stdarch#1928

Use SIMD intrinsics for `vfmaddsubph` and `vfmsubaddph`

---

ci/docker/x86_64-unknown-linux-gnu/Dockerfile
crates/core_arch/src/x86/xsave.rs
crates/core_arch/src/x86_64/xsave.rs

It turns out that MSVC was right, and we were wrong (such a weird thing to say).
Our `xsave` tests used a fixed-size 2560 byte buffer for saving all register data. But the problem is that the required size for xsave is not fixed, it depends on the CPU. This piece of code is ancient, and when it was written the authors calculated this limit based on the typical size. But currently, the maximum size required for xsave can be as high as 11892 bytes (heck on my laptop it is 2696 bytes, if anyone wants to try it out the code is in [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2024&gist=98d5ba7f35621ded6d71e191ae5cb999)), for our SDE run it is 11008 bytes (which also explains why these tests were disabled in the `x86_64-unknown-linux-gnu` run, due to such a huge …

Fix xsave segfaults

---

crates/core_arch/src/x86/avx.rs
crates/core_arch/src/x86/avx512f.rs
crates/core_arch/src/x86/sse.rs
crates/core_arch/src/x86/sse2.rs
crates/core_arch/src/x86/sse4a.rs
crates/core_arch/src/x86_64/sse2.rs

- Use inline asm for `_mm_stream_{ss,sd}`
- Add `_mm_sfence` calls in tests, without it the tests are technically UB

Fixes for non-temporal intrinsics

---

crates/core_arch/src/riscv_shared/mod.rs

While many intrinsics use `.insn` to generate raw machine code from numbers, all ratified instructions can be symbolic using `.option` directives.
By saving the assembler environment with `.option push` then modifying the architecture with `.option arch`, we can temporarily enable certain extensions (as we use `.option pop` immediately after the target instruction, surrounding environment is completely intact in this commit; *almost* completely intact in general).
This PR (part 1) modifies the `pause` *hint* intrinsic to use symbolic *instruction* because we want to expose it even if the Zihintpause extension is unavailable on the target.
----
This is the technique as the author used in rust-lang/rust#146798.

RISC-V: Use symbolic instructions on inline assembly (part 1)
