TODO.md
src/x86/avx2.rs
src/x86/mod.rs

First batch of AVX2 functions, with tests. I've tried to emulate all the style conventions, let me know if I have missed some.

Start of AVX2 functions

---

TODO.md
src/x86/avx.rs
src/x86/avx2.rs
src/x86/mod.rs

I got a start on the avx functions so if I can talk another person to come help they will have an easy template to get started.

Start on AVX

---

TODO.md
src/x86/avx2.rs

This represents all of the 'low hanging fruit' in avx2, the remaining functions are all tricky, so my commits will slow down, and/or I may need to bug you a bit with questions on the rest.
Alternatively I could move on to the low hanging fruit in avx.rs,  let me know what you would prefer!

avx2 lhf complete

---

src/macros.rs

Helped me locally at least! Curious what you think.

Add `fmt::LowerHex` to integer simd for debugging

---

src/macros.rs

Avoids function calls in release builds!

Add #[inline] to cast methods

---

TODO.md
src/x86/ssse3.rs

Implementing `_mm_shuffle_epi8`.

---

TODO.md
src/x86/sse.rs

I have added the `_mm_unpackhi_ps` function to `sse.rs`. This is my first pull request. Appreciate your feedback.

Added _mm_unpackhi_ps function

---

src/x86/avx2.rs
src/x86/sse.rs
src/x86/sse41.rs
src/x86/ssse3.rs

Also a few other assorted modules

Add AVX2 instruction assertiosn

---

src/x86/avx.rs

These pass their tests and should be good to go

Add vroundps, vceilps, vfloorps, vsqrtps, vsqrtpd

---

src/arm/v8.rs

[arm] fix aarch64 cls intrinsic

---

src/x86/sse2.rs

_mm_cvtsd_si32 
_mm_cvtsd_ss 
_mm_cvtss_sd 
_mm_cvttpd_epi32
_mm_cvttsd_si32

added sse2 

---

src/x86/sse.rs

This boils down to using LLVMs [`prefetch`][1] intrinsic. The regular [`_mm_prefetch`][2] intrinsic takes a constant int as a second parameter, so I used the same API.
[1]: https://llvm.org/docs/LangRef.html#llvm-prefetch-intrinsic
[2]: https://gist.github.com/anonymous/25d752fda8521d29699a826b980218fc#file-intel-intrinsics-3-3-15-xml-L2280

Implement _mm_prefetch

---

src/lib.rs
src/x86/sse42.rs

- Add more examples to `_mm_cmpistri`
- Add basic docs to `_mm_cmpestri`
- Cleanup lib docs

[Docs] Add more docs to the sse4.2 cmpstr fns

---

.appveyor.yml
ci/run.sh

Need to bring codegen units back to only one for now

Attempt to fix CI

---

src/x86/sse.rs

Implements SSE `_mm_store*` intrinsics and `_mm_move_ss`

Add SSE _mm_store* intrinsics and _mm_move_ss

---

ci/run.sh
src/x86/avx2.rs

Just needed some `constify_imm8!` treatment
Closes #59

Uncomment _mm256_mpsadbw_epu8

---

examples/nbody.rs

Ports @huonw 's nbody example from the old simd library.

[example] nbody

---

src/x86/avx2.rs

_mm256_cvtepi8_epi16
_mm256_cvtepi8_epi32
_mm256_cvtepi8_epi64
_mm256_cvtepi16_epi32
_mm256_cvtepi16_epi64
_mm256_cvtepi32_epi64

avx2: signed extensions

---

src/x86/avx2.rs

Add AVX2 unpack intrinsics using LLVM shuffles.

avx2: add _mm256_unpack{hi,lo}_epi{8,16,32,64}

---

src/x86/runtime.rs

[runtime-detection-x86] detect avx and avx2 only if osxsave is true

---

src/x86/sse41.rs

Unfortunately, pmulld is not supported by llvm.
This is a PR for https://github.com/rust-lang-nursery/stdsimd/issues/40 tracking issue.

[x86][sse4.1] Add phminposuw & pmul* instructions

---

src/lib.rs

[nvptx] enable nvptx only when all other targets are disabled

---

coresimd/src/x86/i586/avx2.rs

- _mm256_shufflehi_epi16
- _mm256_shufflelo_epi16
- _mm256_inserti128_si256
- _mm256_extracti128_si256
- _mm256_permute2x128_si256
- _mm256_permute4x64_pd
- _mm256_permutevar8x32_ps

[avx2] add shuffle, insert/extract i128, permute*

---

coresimd/src/x86/i586/avx.rs

`nontemporal_store` related intrinsics.
AVX is complete.

avx: _mm256_stream_si256, _mm256_stream_pd, _mm256_stream_ps

---

.travis.yml
ci/docker/powerpc-unknown-linux-gnu/Dockerfile
ci/docker/powerpc64-unknown-linux-gnu/Dockerfile
ci/docker/powerpc64le-unknown-linux-gnu/Dockerfile
ci/dox.sh
src/lib.rs

This PR adds three build-bots for powerpc and fixes a build issue. 
I have two branches (altivec / core_auxval) that build on this.

[ci] powerpc/powerpc64/powerpc64le

---

coresimd/src/x86/i586/sse2.rs
coresimd/src/x86/i686/sse2.rs

sse2: implements last remaining intrinsics

---

coresimd/src/x86/i686/mmx.rs
coresimd/src/x86/i686/sse.rs
coresimd/src/x86/i686/ssse3.rs
stdsimd-test/src/lib.rs

Right now it's 30 which is a bit high, most of the intrinsics requiring all
these instructions ended up needing to be fixed anyway.

Lower the instruction limit to 20

---

coresimd/src/x86/i586/avx2.rs

Migrate the `i586::avx2` module to vendor types

---

coresimd/x86/avx2.rs
coresimd/x86/mod.rs
coresimd/x86/sse.rs
coresimd/x86/sse41.rs
coresimd/x86/sse42.rs
crates/coresimd/src/lib.rs

The boilerplate just gets more and more ugly...

Tweak doctests to pass in libstd as well

---

crates/stdsimd/tests/cpu-detection.rs
stdsimd/arch/detect/aarch64.rs

Run-time feature detection for new AArch64 features

---

coresimd/ppsv/api/fmt.rs

add missing fmt implementations

---

coresimd/x86/mod.rs
coresimd/x86/sha.rs
crates/stdsimd/tests/cpu-detection.rs
stdsimd/arch/detect/arch/x86.rs
stdsimd/arch/detect/os/x86.rs

Add support for Intel SHA extensions.

---

coresimd/arm/neon.rs

fix vrsqrt on arm neon

---

.travis.yml

This'll fix the wasm target on CI

Pin `wabt` to a working revision

---

coresimd/x86/mod.rs

Unstabilize some more #[doc(hidden)] items

---

crates/assert-instr-macro/src/lib.rs
crates/simd-test-macro/src/lib.rs
examples/nbody.rs

Avoid the combinatorial explosion once we add support for additional
architectures and simd flavours.

Use cfg_if for the nbody example

---

coresimd/arm/neon.rs

Small spelling fix

---

stdsimd/mod.rs

Always point to {target_name}/.../{target_name}/index.html

Fix some links

---

coresimd/ppsv/api/masks_reductions.rs
coresimd/ppsv/api/mod.rs
coresimd/ppsv/api/swap_bytes.rs
coresimd/ppsv/codegen/mod.rs
coresimd/ppsv/codegen/swap_bytes.rs
coresimd/simd_llvm.rs

We could add some `llvm.bswap` implementations (https://godbolt.org/g/jH2FCR suggests it might be better).
Testing could be better.

add swap_bytes/to_le/to_be

---

coresimd/arm/dsp.rs

Just add:
- `usad8`: Sum of 8-bit absolute differences
- `usad8a`: Sum of 8-bit absolute differences and constant (usad8(a, b) + c)

ARM  ARM DSP/SIMD32: Sum of 8-bit absolute differences

---

coresimd/powerpc/altivec.rs

I'm wondering if we couldn't just use a single `target_feature` at module level.

One more instruction and further refinements

---

crates/stdsimd-test/src/lib.rs

Add environment variable STDSIMD_ASSERT_INSTR_LIMIT to control the instruction limit

Add environment variable STDSIMD_ASSERT_INSTR_LIMIT

---

stdsimd/arch/detect/arch/aarch64.rs

Needed for https://github.com/rust-lang/rust/pull/56407

Add missing docs

---

.travis.yml

Allow powerpc-unknown-linux-gnu build job to fail

---

crates/core_arch/src/x86/avx2.rs
crates/core_arch/src/x86/sse41.rs
crates/core_arch/src/x86/sse42.rs

Doc tests should use std

---

crates/std_detect/src/detect/arch/aarch64.rs
crates/std_detect/src/detect/arch/arm.rs
crates/std_detect/src/detect/arch/mips.rs
crates/std_detect/src/detect/arch/mips64.rs
crates/std_detect/src/detect/arch/powerpc.rs
crates/std_detect/src/detect/arch/powerpc64.rs
crates/std_detect/src/detect/arch/x86.rs
crates/std_detect/tests/macro_trailing_commas.rs

Add detect macros should support trailing commas (Fix #443)

---

crates/std_detect/src/detect/arch/aarch64.rs
crates/std_detect/src/detect/arch/arm.rs
crates/std_detect/src/detect/arch/mips.rs
crates/std_detect/src/detect/arch/mips64.rs
crates/std_detect/src/detect/arch/powerpc.rs
crates/std_detect/src/detect/arch/powerpc64.rs
crates/std_detect/src/detect/arch/x86.rs

allow_internal_unstable requires feature names

---

crates/core_arch/src/x86/bmi1.rs
crates/core_arch/src/x86/cpuid.rs
crates/core_arch/src/x86/sse.rs
crates/core_arch/src/x86/tbm.rs
crates/core_arch/src/x86_64/bmi.rs
crates/std_detect/src/detect/os/linux/mips.rs
crates/stdsimd-verify/tests/arm.rs

Sorry, just a few more I forgot to include! Not big at all.
r? @gnzlbg

A few more cosmetic improvements

---

.travis.yml
ci/docker/aarch64-unknown-linux-gnu/Dockerfile
ci/docker/arm-unknown-linux-gnueabihf/Dockerfile
ci/docker/armv7-unknown-linux-gnueabihf/Dockerfile
ci/docker/i586-unknown-linux-gnu/Dockerfile
ci/docker/i686-unknown-linux-gnu/Dockerfile
ci/docker/mips-unknown-linux-gnu/Dockerfile
ci/docker/mips64-unknown-linux-gnuabi64/Dockerfile
ci/docker/mips64el-unknown-linux-gnuabi64/Dockerfile
ci/docker/powerpc-unknown-linux-gnu/Dockerfile
ci/docker/powerpc64-unknown-linux-gnu/Dockerfile
ci/docker/powerpc64le-unknown-linux-gnu/Dockerfile
ci/docker/s390x-unknown-linux-gnu/Dockerfile
ci/docker/x86_64-unknown-linux-gnu/Dockerfile

Fixes https://github.com/rust-lang-nursery/stdsimd/issues/669

Modernize Docker images

---

.travis.yml

This isn't ready, just a draft, but this is the easiest way to see what the CI itself is gonna do, so here we go.

Fixing the GBA in the build script again

---

.appveyor.yml
.travis.yml

They have been failing for too long. No idea what's going on.

Disable assert_instr tests on Windows

---

crates/core_arch/src/x86/sse4a.rs

Improve docs of SSE4a stream intrinsics

---

crates/stdsimd-verify/src/lib.rs

The patch was pushed when you merged the open set :)

Use find_map to make clippy happy

---

ci/docker/powerpc64-unknown-linux-gnu/Dockerfile
ci/docker/powerpc64le-unknown-linux-gnu/Dockerfile
crates/core_arch/src/powerpc/altivec.rs
crates/core_arch/src/simd.rs

Here a larger set with additional macros to reduce the number of lines of code.

Altivec update

---

crates/core_arch/src/lib.rs
crates/core_arch/src/powerpc/altivec.rs

Altivec update 2

---

crates/core_arch/src/wasm32/mod.rs

Tracking issue: https://github.com/rust-lang/rust/issues/61119

Stabilize `unreachable`.

---

crates/core_arch/src/mod.rs

Needed for https://github.com/rust-lang/rust/pull/60938 to land

Adjust #[doc(include)] paths for rustdoc change

---

crates/assert-instr-macro/src/lib.rs
crates/core_arch/src/lib.rs
crates/core_arch/src/powerpc/altivec.rs
crates/stdsimd-test/src/lib.rs

r? @alexcrichton 
This is enough to fix the libcore build, all tests are still failing though.

Fix libcore build

---

.travis.yml
crates/core_arch/src/macros.rs
crates/core_arch/src/powerpc/altivec.rs

- vec_cmple
- vec_cmplt
- vec_expte
- vec_floor

Altivec update (again)

---

crates/core_arch/src/x86/sse2.rs

Make the _mm_movemask_epi8 test a non palindrome

---

ci/azure.yml
crates/std_detect/Cargo.toml
crates/std_detect/src/detect/macros.rs
crates/std_detect/src/detect/mod.rs

Privacy fixes and env override disabled by default

---

README.md

Add the github Action badge

---

ci/docker/wasm32-unknown-unknown/wasm-entrypoint.sh

Addresses rust-lang/rust#31036

Convert posix scripts to bash

---

crates/simd-test-macro/src/lib.rs

Rust bug: https://github.com/rust-lang/rust/issues/72545

Fix CI issues caused by updated nightly

---

crates/core_arch/src/x86/avx512f.rs

Fix AVX512f comparison comments

---

crates/core_arch/src/aarch64/neon/mod.rs
crates/core_arch/src/arm/neon/mod.rs

This should be the correct version of all the absolute value operations on the integer types.

[Neon] Absolute Value fns

---

.github/workflows/main.yml

Should be fixed after landing rust-lang/rust#75316

Re-enable wasi on CI

---

crates/core_arch/src/simd_llvm.rs

Remove old TODO

---

crates/core_arch/src/x86/mod.rs

Fix another "stdimd" typo

---

crates/assert-instr-macro/build.rs
crates/assert-instr-macro/src/lib.rs
crates/core_arch/src/x86/avx2.rs
crates/core_arch/src/x86/avx512f.rs
crates/core_arch/src/x86/avx512ifma.rs
crates/core_arch/src/x86/fma.rs
crates/core_arch/src/x86/fxsr.rs
crates/core_arch/src/x86/rtm.rs
crates/core_arch/src/x86/sse.rs
crates/core_arch/src/x86/xsave.rs
crates/core_arch/src/x86_64/avx512f.rs
crates/core_arch/src/x86_64/fxsr.rs
crates/core_arch/src/x86_64/xsave.rs
crates/core_arch/tests/cpu-detection.rs
crates/std_detect/tests/cpu-detection.rs
crates/std_detect/tests/macro_trailing_commas.rs
crates/stdarch-gen/src/main.rs
crates/stdarch-verify/src/lib.rs
crates/stdarch-verify/tests/arm.rs
crates/stdarch-verify/tests/mips.rs
crates/stdarch-verify/tests/x86-intel.rs
examples/hex.rs

Part of https://github.com/rust-lang/rust/pull/77351 (but doesn't block that PR, so feel free to close this if you don't like clippy).

Fix some clippy lints

---

crates/core_arch/src/x86/sse41.rs

Replace <c> element by markdown inline code

---

crates/core_arch/src/x86/avx512vnni.rs
crates/core_arch/src/x86/mod.rs
crates/stdarch-verify/tests/x86-intel.rs

dpwssd_epi32: mm512,mm256,mm
dpwssds_epi32: mm512,mm256,mm
dpbusd_epi32: mm512,mm256,mm
dpbusds_epi32: mm512,mm256,mm

avx512vnni

---

crates/core_arch/avx512f.md
crates/core_arch/src/simd.rs
crates/core_arch/src/x86/avx512f.rs
crates/core_arch/src/x86/mod.rs
crates/core_arch/src/x86_64/avx512f.rs

abs_epi32,epi64: mm256,mm
add_epi32,epi64,ps,pd: mm256,mm
sub_epi32,epi64,ps,pd: mm256,mm
mul_epi32,epu32: mm256,mm
mul_ps,pd: mm256,mm; mullo_epi32: mm256,mm
div_ps,pd: mm256,mm

Avx512f_avx512vl

---

.github/workflows/main.yml
crates/core_arch/avx512f.md
crates/core_arch/src/x86/avx512f.rs
crates/core_arch/src/x86_64/avx512f.rs

unpacklo_epi32,epi64,ps,pd: mm256,mm
unpackhi_epi32,epi64,ps,pd: mm256,mm
mask_blend_epi32,epi64,ps,pd: mm256,mm; broadcast_f32x4: mm256
broadcast_i32x4: mm256; broadcast_i32,i64,ps,pd: mm256,mm
shuffle_epi32, mm256,mm; shuffle_ps,pd: mm256,mm
shuffle_i32x4,i64x2,f32x4,f64x2: mm256

Avx512f avx512vl

---

crates/core_arch/avx512f.md
crates/core_arch/src/x86/avx512bw.rs
crates/core_arch/src/x86/avx512f.rs
crates/core_arch/src/x86_64/avx512f.rs

Fix permute_ps,pd
Fix permutex_epi64,pd
use macro to remove repeat code(avx512f,avx512bw)
move convert out of macro

Fix_avx512f,bw

---

crates/core_arch/src/x86/avx.rs

* _mm256_extractf128_ps
* _mm256_extractf128_pd
* _mm256_extractf128_si256
* _mm256_insertf128_ps
* _mm256_insertf128_pd
* _mm256_insertf128_si256

Convert _mm256_{insert,extract}f128_{ps,pd,si256} to const generics

---

crates/core_arch/src/x86/avx.rs
crates/core_arch/src/x86/avx512f.rs
crates/core_arch/src/x86_64/avx512f.rs

* _mm256_permute_pd
* _mm256_permute_ps
* _mm_mask_permute_pd
* _mm_maskz_permute_pd
* _mm_permute_pd
* _mm_permute_ps

Convert _mm{256,_mask,}_permute_p{d,s} to const generics

---

crates/core_arch/src/mips/msa.rs
crates/core_arch/src/mips/msa/macros.rs

Blocked on #1028 
cc #1022
I'm gonna go on vacation in a next few days for a long time. If anyone want to pick this, feels free.

2/3 mips: Convert *const(1) to const generics

---

crates/core_arch/src/x86/cpuid.rs

It is sometimes reserved by LLVM.

Avoid using ebx as an asm! operand

---

crates/core_arch/src/aarch64/neon/generated.rs
crates/core_arch/src/arm/neon/generated.rs
crates/stdarch-gen/neon.spec
crates/stdarch-gen/src/main.rs

This PR add vqshl, vqshrn, vqshrun neon instructions

add vqshl, vqshrn, vqshrun neon instructions

---

crates/std_detect/src/detect/macros.rs

Move cfg!(target_feature) directly into is_*_feature_detected!()

---

crates/core_arch/src/aarch64/neon/generated.rs
crates/core_arch/src/arm_shared/neon/generated.rs
crates/core_arch/src/lib.rs
crates/stdarch-gen/neon.spec
crates/stdarch-gen/src/main.rs
crates/stdarch-test/src/lib.rs

This PR completes the vmla and vmls instructions.
Use `bench_black_box` feature to avoid compilation failure.

Add vmla_n, vmla_lane, vmls_n, vmls_lane neon instructions

---

crates/core_arch/src/aarch64/neon/generated.rs
crates/core_arch/src/arm_shared/neon/generated.rs
crates/stdarch-gen/neon.spec
crates/stdarch-gen/src/main.rs
crates/stdarch-verify/tests/arm.rs

This PR adds vqrdmulh, vqrdmlah, vqrdmlsh neon instructions.

Add vqrdmulh, vqrdmlah, vqrdmlsh neon instructions

---

crates/core_arch/src/wasm32/atomic.rs
crates/core_arch/src/wasm32/memory.rs
crates/core_arch/src/wasm32/simd128.rs

Add doc aliases for all wasm intrinsics

---

crates/core_arch/src/aarch64/neon/generated.rs
crates/core_arch/src/arm_shared/neon/generated.rs
crates/core_arch/src/arm_shared/neon/mod.rs
crates/stdarch-gen/neon.spec

Add vqmovn neon instructions

---

crates/core_arch/src/aarch64/neon/generated.rs
crates/core_arch/src/arm_shared/neon/generated.rs
crates/core_arch/src/lib.rs
crates/stdarch-gen/neon.spec
crates/stdarch-test/src/lib.rs

Complete vmfa and vfms instructions and correct the wrong implementations.

Add vfma and vfms neon instructions

---

crates/core_arch/src/wasm32/simd128.rs

First change them all to unsigned since they're just returning bits, and
then also change them to the smallest-size integer which fits the return
value (`u16` for `i8x16_bitmask` and `u8` for everything else). This
suffers from an LLVM codegen bug for now, but it will hopefully get
fixed in the not too distant future.

wasm: Change `*_bitmask` return values

---

crates/core_arch/src/x86/bt.rs
crates/core_arch/src/x86_64/bt.rs

FCP is complete: https://github.com/rust-lang/rust/issues/59414#issuecomment-826072554

Stabilize `simd_x86_bittest` feature

---

crates/core_arch/src/lib.rs

Remove unused wasm feature

---

crates/core_arch/MISSING.md
crates/core_arch/src/aarch64/neon/generated.rs
crates/core_arch/src/aarch64/neon/mod.rs
crates/core_arch/src/arm_shared/neon/generated.rs
crates/stdarch-gen/neon.spec
crates/stdarch-gen/src/main.rs
crates/stdarch-verify/tests/arm.rs

This PR completes armv8 instructions.

complete armv8 instructions

---

crates/std_detect/src/detect/os/freebsd/auxvec.rs

Also see https://github.com/rust-lang/rust/pull/91284

Support riscv64gc-unknown-freebsd

---

crates/core_arch/src/x86/avx.rs

It will be needed for https://github.com/rust-lang/rust/pull/94529.

Replace unused doc comment with code comment

---

ci/docker/aarch64-unknown-linux-gnu/Dockerfile
ci/docker/armv7-unknown-linux-gnueabihf/Dockerfile
ci/docker/riscv64gc-unknown-linux-gnu/Dockerfile
crates/core_arch/src/x86/avx512bw.rs

Update ubuntu 21.10 docker containers to 22.04

---

CONTRIBUTING.md

fix target name in contributing.md

---

crates/core_arch/src/x86/sse.rs

Remove workaround for old LLVM issue

---

crates/core_arch/src/aarch64/neon/mod.rs

Fix typo in LLVM intrinsic names

---

crates/core_arch/src/powerpc/altivec.rs
crates/core_arch/src/powerpc/vsx.rs

At least locally this is needed to let the test pass.

Unbreak powerpc64 tests

---

crates/std_detect/src/detect/os/linux/auxvec.rs

Discovered on powerpc64 where it crashes since it has more than 32 entries.
Thanks to @dodomorandi, @nappa85 and the rest of @rust-italia for assisting at the debugging session.
Ideally we could avoid the second allocation by using array_chunks() and from_ne_bytes but it isn't an hot path.

std_detect: Unbreak auxv_from_file

---

crates/core_arch/src/x86/avx.rs
crates/core_arch/src/x86/avx2.rs
crates/core_arch/src/x86/avx512bw.rs
crates/core_arch/src/x86/sse2.rs
crates/stdarch-test/src/disassembly.rs

I'm not sure why the vpbroadcast tests are failing, they work fine in isolation:  https://rust.godbolt.org/z/oGnxGbb4E
Fixes #1408

Fix CI tests

---

crates/core_arch/src/x86/sse.rs

this PR is needed for https://github.com/rust-lang/rust/pull/110189, see https://github.com/rust-lang/rust/pull/110189#issuecomment-1504298677

x86: remove unnecessary parens

---

crates/core_arch/src/powerpc/mod.rs

Remove the altivec and vsx guards

---

ci/run.sh
crates/core_arch/src/powerpc/altivec.rs

- Fix vec_ld signature
- Add vec_ldl and vec_lde

Altivec load instructions

---

crates/core_arch/src/powerpc/altivec.rs

Altivec convert float

---

crates/core_arch/src/powerpc/altivec.rs
crates/core_arch/src/powerpc/macros.rs

Altivec permutes

---

crates/core_arch/src/x86/avx512bitalg.rs
crates/core_arch/src/x86/avx512bw.rs
crates/core_arch/src/x86/avx512f.rs
crates/core_arch/src/x86/sse.rs
crates/core_arch/src/x86/sse2.rs
crates/core_arch/src/x86/sse41.rs
crates/core_arch/src/x86_64/avx512f.rs
crates/std_detect/src/detect/os/x86.rs

Remove unneeded transmutes

---

crates/std_detect/README.md
crates/std_detect/src/detect/arch/loongarch.rs
crates/std_detect/src/detect/arch/mod.rs
crates/std_detect/src/detect/mod.rs
crates/std_detect/src/detect/os/linux/auxvec.rs
crates/std_detect/src/detect/os/linux/loongarch.rs
crates/std_detect/src/detect/os/linux/mod.rs
crates/std_detect/src/lib.rs

Add run-time feature detection for LoongArch.

std_detect: Add support for LoongArch

---

crates/core_arch/src/powerpc/altivec.rs
crates/core_arch/src/simd_llvm.rs

Altivec shifts

---

crates/core_arch/src/powerpc/altivec.rs

Altivec stores

---

crates/core_arch/src/powerpc/altivec.rs

More altivec

---

crates/core_arch/src/powerpc/altivec.rs
crates/core_arch/src/powerpc/macros.rs
crates/core_arch/src/powerpc/mod.rs
crates/core_arch/src/powerpc64/mod.rs
crates/core_arch/src/powerpc64/vsx.rs

VSX len load and stores

---

crates/intrinsic-test/src/json_parser.rs

intrinsic-test: Suppress a warning about dead code

---

crates/core_arch/src/powerpc/vsx.rs

Altivec even odd merge

---

crates/stdarch-gen-arm/src/main.rs

Minor lints for stdarch-gen-arm/src/main.rs

---

crates/stdarch-gen-arm/src/main.rs

Minor nits in the code, like usage of `&Option<str>`  -- see https://www.youtube.com/watch?v=6c7pZYP_iIE

Improve stdarch-gen-arm a bit

---

crates/core_arch/src/lib.rs
crates/core_arch/src/wasm32/simd128.rs

This is in preparation for https://github.com/rust-lang/rust/pull/131349

avoid rustc_const_stable on internal function

---

crates/core_arch/src/s390x/macros.rs
crates/core_arch/src/s390x/vector.rs

`s390x`: add `vec_sub`, `vec_mul`, `vec_min`, `vec_max`, `vec_abs` and `vec_splats`

---

crates/core_arch/src/x86/gfni.rs
crates/core_arch/src/x86/vaes.rs
crates/core_arch/src/x86/vpclmulqdq.rs

closes #1809
~CI fails because connection of `archive.ubuntu.com` time out.~

mark gfni, vaes, vpclmulqdq intrinsics as safe

---

crates/simd-test-macro/src/lib.rs

tests: neon is arm

---

Cargo.lock
crates/intrinsic-test/Cargo.toml
crates/stdarch-gen-arm/Cargo.toml

This removes few unused deps and bumps serde_with to drop few dupes too.

drop few unused deps

---

crates/core_arch/src/x86/avx512f.rs
crates/core_arch/src/x86_64/avx512f.rs

Remove some llvm workarounds
