src/x86/mod.rs
src/x86/sse41.rs

Add bindings for _mm_blendv_epi8

---

.appveyor.yml
.travis.yml
Cargo.toml
assert-instr/Cargo.toml
assert-instr/assert-instr-macro/Cargo.toml
assert-instr/assert-instr-macro/build.rs
assert-instr/assert-instr-macro/src/lib.rs
assert-instr/src/lib.rs
src/lib.rs
src/x86/sse.rs

This commit adds a procedural macro which can be used to test instruction
generation in a lightweight way. The intention is that all functions are
annotated with:
#[cfg_attr(test, assert_instr(maxps))]
fn foo(...) {
// ...
}
and then during `cargo test --release` it'll assert the function `foo` does
indeed generate the instruction `maxps`. This only activates tests in optimized
mode to avoid debug mode inefficiencies, and it uses a literal invocation of
`objdump` and some parsing to figure out what instructions are inside each
function. Finally it also uses the `backtrace` crate to figure out the symbol
name of the relevant function and hook that up to the output of `objdump`.
I added a few assertions in the `sse` module to get some feedback, but curious
what y'all think of this!

Add assertions correct instructions are generated

---

.appveyor.yml
Cargo.toml
assert-instr/assert-instr-macro/src/lib.rs
assert-instr/src/lib.rs
src/arm/mod.rs
src/arm/v6.rs
src/arm/v7.rs
src/arm/v8.rs
src/lib.rs
src/x86/bmi2.rs

This adds ARM's `rev`, `rbit`, `clz` and `cls` intrinsics. 
The `cls` intrinsic currently generates bad code due to an LLVM bug, I've filled issue #30 to track it.
Closes #35 .

[arm] bitwise manipulation instructions

---

.travis.yml
assert-instr/src/lib.rs
ci/docker/aarch64-unknown-linux-gnu/Dockerfile
ci/docker/arm-unknown-linux-gnueabihf/Dockerfile
ci/docker/armv7-unknown-linux-gnueabihf/Dockerfile
ci/docker/i686-unknown-linux-gnu/Dockerfile
ci/docker/x86_64-unknown-linux-gnu/Dockerfile
ci/run-docker.sh
ci/run.sh
examples/play.rs
examples/types.rs
examples/wat.rs
src/arm/v6.rs
src/arm/v7.rs
src/arm/v8.rs
src/x86/bmi.rs
src/x86/bmi2.rs
src/x86/tbm.rs

This commit adds CI for a few more targets:
* i686-unknown-linux-gnu
* arm-unknown-linux-gnueabihf
* armv7-unknown-linux-gnueabihf
* aarch64-unknown-linux-gnu
The CI here is structured around using a Docker container to set up a test
environment and then QEMU is used to actually execute code from these platforms.
QEMU's emulation actually makes it so we can continue to just use `cargo test`,
as processes can be spawned from QEMU like `objdump` and files can be read (for
libbacktrace). Ends up being a relatively seamless experience!
Note that a number of intrinsics were disabled on i686 because they were failing
tests, and otherwise a few ARM touch-ups were made to get tests passing.
Closes #13
Closes #33

Add CI for more platforms

---

assert-instr/src/lib.rs

There's a lot of trickery in this crate which expands to a lot of code, so in
addition to asserting that we find the right instruction, let's assert we find
a small function as well (as these should all be just one or so instructions
anyway).

Assert that diassembly is "small"

---

Cargo.toml
tests/cpu-detection.rs

Make sure we agree with the `cupid` crate

Add a test for x86 runtime support

---

TODO.md
assert-instr/src/lib.rs
src/x86/sse.rs

Squashing commits from #39 .
@alexcrichton The shuffle intrinsic involves a macro that expands for each shuffle mask (8 bits -> 256 cases). Thus I have removed the `probably_only_one_instruction` flag from the `assert-instr` macro. Let me know if this is fine or whether we should find another solution.

Added _mm_unpacklo_ps, _mm_movehl_ps, _mm_movelh_ps and _mm_shuffle_ps

---

.appveyor.yml
.travis.yml
examples/play.rs
src/arm/v7.rs
src/lib.rs
src/x86/abm.rs
src/x86/avx.rs
src/x86/avx2.rs
src/x86/bmi.rs
src/x86/bmi2.rs
src/x86/sse.rs
src/x86/sse2.rs
src/x86/sse41.rs
src/x86/sse42.rs
src/x86/ssse3.rs
src/x86/tbm.rs
stdsimd-test/simd-test-macro/src/lib.rs

... and also add missing assert_instr tests.
I'm somewhat expecting CI for i686 to fail. I think a few of the vendor intrinsics lower to different instructions on i686 vs x86_64.

add unsafe to every vendor intrinsic

---

src/x86/avx.rs
src/x86/sse.rs
stdsimd-test/assert-instr-macro/Cargo.toml
stdsimd-test/assert-instr-macro/src/lib.rs

Some intrinsics need to be invoked with constant arguments to get the right
instruction to get generated, so this commit enhances the `assert_instr` macro
to enable this ability. Namely you pass constant arguments like:
#[assert_instr(foo, a = b)]
where this will assert that the intrinsic, when invoked with argument `a` equal
to the value `b` and all other arguments passed from the outside, will generate
the instruction `foo`.
Closes #49

Enhance `#[assert_instr]` with constant arguments

---

src/x86/sse2.rs
src/x86/sse41.rs
src/x86/sse42.rs

This commit switches the remaining "wrapper" tests to assert_instr with
constant parameters. This form of test is necessary when a vendor
intrinsic requires an immediate constant value to optimize properly into
the intended CPU instruction.

x86: remove remaining wrapper tests

---

src/x86/sse2.rs

`_mm_cvtepi32_ps` has been implemented, but `_mm_cvtps_epi32` is missing.
Use the implementation of `_mm_cvtepi32_ps` as a guide for implementing
`_mm_cvtps_epi32`.

[x86] Add _mm_cvtps_epi32 (cvtps2dq) function

---

src/x86/sse2.rs

i am not a hundred percent sure if the last three test are what we really want here, just looks weird that it "defaults" to `i32::MIN` but maybe that's supposed to happen, can't really find docs about that behavior.

added support for _mm_cvtpd_epi32 / cvtpd2dq

---

src/v256.rs
src/x86/avx.rs
src/x86/sse2.rs

In clang's  [avxintrin.h](https://github.com/llvm-mirror/clang/blob/master/lib/Headers/avxintrin.h#L528-L532) this intrinsics are implemented with a cast to an **unsigned** type but in [sse2.rs](https://github.com/rust-lang-nursery/stdsimd/blob/master/src/x86/sse2.rs#L1382), for example, similar instructions use a **signed** type. Does this make a difference? Should I change for the sake of consistency?
Also, llvm emits the wrong instruction for the double precision intrinsics (see Issue #71), so the `assert_instr` test is changed to the emitted instruction, as suggested on the gitter chat, to please the tests.

Add vandpd, vandps, vorpd and vorps for AVX

---

src/x86/avx.rs

It looks like there is no llvm compiler intrinsic for these isntructions, so I mimicked the implementation in https://github.com/llvm-mirror/clang/blob/master/lib/Headers/avxintrin.h#L166-L201
I have inspected the resulting binary with `objdump -d`, and I get
```
0000000000028eb0 <_ZN7stdsimd3x863avx13_mm256_div_pd17hfb622e668096388cE>:
28eb0:       55                      push   %rbp
28eb1:       48 89 e5                mov    %rsp,%rbp
28eb4:       c5 fd 5e c1             vdivpd %ymm1,%ymm0,%ymm0
28eb8:       5d                      pop    %rbp
28eb9:       c3                      retq   
28eba:       66 0f 1f 44 00 00       nopw   0x0(%rax,%rax,1)
```
which seems ok.

avx: add _mm256_div_pd, _mm256_div_ps

---

src/lib.rs
src/x86/sse42.rs

- Implement
- _mm_cmpistrm
- _mm_cmpistri
- _mm_cmpistrz
- _mm_cmpistrc
- _mm_cmpistrs
- _mm_cmpistro
- _mm_cmpistra
- _mm_cmpestrm
- _mm_cmpestrz
- _mm_cmpestrc
- _mm_cmpestrs
- _mm_cmpestro
- _mm_cmpestra
- Add documentation to _mm_cmpestri
- Add missing constants
- Fix typo in lib docs
I'm working on getting sse4.2 covered, but I figured this was a nice chunk to start with. Comments and critiques are welcomed!

Implement the sse4.2 string comparison intrinsics

---

src/x86/sse42.rs

- Implement
- `_mm_crc32_u8`
- `_mm_crc32_u16`
- `_mm_crc32_u32`
- `_mm_crc32_u64`
- `_mm_cmpgt_epi64`

[x86] Implement sse4.2 crc32 functions

---

src/x86/avx.rs

Fix a grammatical error, use a list instead of using a code block or nothing,
and add the LLVM immediate reference.

Improve _mm256_round_* docs

---

src/x86/sse.rs
stdsimd-test/assert-instr-macro/src/lib.rs

Looks like all we needed to do was generate new function names!

Enable multiple #[assert_instr] attributes

---

.travis.yml
ci/docker/i586-unknown-linux-gnu/Dockerfile
src/x86/avx.rs
src/x86/sse.rs
src/x86/sse2.rs
src/x86/sse42.rs

The i586 targets on x86 are defined to be 32-bit and lacking in sse/sse2 unlike
the i686 target which has sse2 turned on by default. I was mostly curious what
would happen when turning on this target, and it turns out quite a few tests
failed!
Most of the tests here had to do with calling functions with ABI mismatches
where the callee wasn't `#[inline(always)]`. Various pieces have been updated
now and we should be passing all tests.
Only one instruction assertion ended up changing where the function generates a
different instruction with sse2 ambiently enabled and without it enabled.

Add an i586 builder

---

src/x86/sse.rs

This implements SSE intrinsics:
- `_mm_set_ss`
- `_mm_set1_ps`
- `_mm_set_ps1`
- `_mm_set_ps`
- `_mm_setr_ps`
- `_mm_setzero_ps`

Implement SSE _mm_set* intrinsics

---

src/x86/sse.rs

This implements SSE instructions:
- `_mm_loadh_pi`
- `_mm_loadl_pi`
- `_mm_load_ss`
- `_mm_load1_ps`
- `_mm_load_ps1`
- `_mm_load_ps`
- `_mm_loadu_ps`
- `_mm_loadr_ps`
I also added some experimental doctests, but I can't get them to run. (That is, I can't get them to fail by adding `assert!(false)`. They are being compiled, though)

Implement SSE _mm_load* instructions

---

src/x86/sse42.rs

- Add docs for the _SIDD_EQUAL_RANGES mode
Sorry! Forgot about `_SIDD_EQUAL_RANGES` :smile:

[x86] sse4.2 add docs for _SIDD_EQUAL_RANGES

---

src/x86/sse.rs
stdsimd-test/simd-test-macro/src/lib.rs

This adds a strange macro, which I've replaced with a function, because it
seems there are not many better alternatives.
Also adds a test, and `#[allow(non_snake_case)]` to `#[simd_test]`.

Add _MM_TRANSPOSE4_PS pseudo-macro.

---

src/x86/sse.rs

Implement SSE bitwise AND, OR, AND-NOT, and XOR.
Implement all variants of `_mm_cmp*_ss`.

Implement bitwise SSE ops & _mm_cmp*_ss 

---

src/x86/sse.rs

Implements the following SSE intrinsics:
* `_mm_cmp{eq,lt,le,gt,ge,neq,nlt,nle,ngt,nge,ord,unord}_ps`
* `_mm_comi{eq,lt,le,gt,ge,neq}_ss`
* `_mm_ucomi{eq,lt,le,gt,ge,neq}_ss`

SSE Comparison instructions

---

src/x86/sse2.rs

please take a closer look at  [_mm_set_pd](https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=_mm_set_pd&expand=4625) and 
[_mm_setr_pd](https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=_mm_setr_pd&expand=4625,4703)  i am really not a 100% sure and that was the result of the supposedly first mistake [here '_mm_set_pd'](https://github.com/rust-lang-nursery/stdsimd/pull/122/commits/db9cf0d3bcee06a12985971137809a96bc1f91fc) and [here '_mm_setr_pd'](https://github.com/rust-lang-nursery/stdsimd/pull/122/commits/49659a6991b01bbe407d8d42816d8f61ce551eee).

fixed _mm_set_pd and _mm_setr_pd by reversing order

---

src/x86/avx2.rs

If this looks ok, I'll do the other avx2 blends.

avx2: _mm_blend_epi32

---

.travis.yml
ci/docker/x86_64-unknown-linux-gnu-emulated/Dockerfile
ci/run-docker.sh
stdsimd-test/simd-test-macro/src/lib.rs
stdsimd-test/src/lib.rs

This commit adds a new builder on CI for running tests in Intel's own emulator
and also adds an assertion that on this emulator no tests are skipped due to
missing CPU features by accident.
Closes #92

Add CI in Intel's instruction emulator

---

src/x86/avx2.rs

Implement
- `_mm_broadcastb_epi8`
- `_mm256_broadcastb_epi8`
- `_mm_broadcastd_epi32`
- `_mm256_broadcastd_epi32`
- `_mm_bradcastq_epi64`
- `_mm256_broadcastq_epi64`
- `_mm_broadcastsd_pd`
- `_mm256_broadcastsd_pd`
- `_mm256_broadcastsi128_si256`
- `_mm_broadcastss_ps`
- `_mm256_broadcastss_ps`
- `_mm_broadcastw_epi16`
- `_mm256_broadcast2_epi16`

WIP - [x86] Implement avx2 broadcast intrinsics

---

src/x86/sse.rs

Implements:
- `_mm_cvtss_si32` 
- `_mm_cvt_ss2si`
- `_mm_cvtss_si64`
- `_mm_cvttss_si32`
- `_mm_cvtt_ss2si`
- `_mm_cvttss_si64`
- `_mm_cvtsi32_ss`
- `_mm_cvt_si2ss`
- `_mm_cvtsi64_ss`
- `_mm_cvtss_f32`
Note that the following related instructions are currently blocked by https://github.com/rust-lang-nursery/stdsimd/issues/74
- `_mm_cvtps_pi32`
- `_mm_cvt_ps2pi`
- `_mm_cvttps_pi32`
- `_mm_cvtt_ps2pi`
- `_mm_cvtpi32_ps`
- `_mm_cvt_pi2ps`

Add some SSE _mm_cvt* instructions

---

src/x86/avx.rs
src/x86/macros.rs
src/x86/sse.rs

Hi,
I have run the tests and five of them failed. I checked the Intel Intrinsics Guide and it said that these specific instructions returns approximated values while the tests don't take the error into account. I have Ryzen 1700X. I guess all of test runs until now could be done on Intel CPUs where it could possibly always return those hardcoded specific values.
I also haven't known how to cleanly make the compare, so I have added an extra macro. It is basically copy-paste of [this](https://github.com/ashleygwilliams/assert_approx_eq/blob/master/src/lib.rs) since I didn't want to add new dependencies.

x86: fixed testing equality of floating point numbers

---

src/x86/avx2.rs

Please merge #152 before this one for better granulity. I have based this PR on my previous one, because they can't be automatically merged.

x86: implemented _mm{,256}_maskstore_epi{32,64}

---

src/x86/sse41.rs

Hi,
I was basing mainly on [clang](https://clang.llvm.org/doxygen/smmintrin_8h_source.html) and, obviously, Intel Intrinsics Guide. Tests for `_mm_round_*` does not cover all possible roundings for all intrinsics. Furthermore, I haven't added docs, just left some TODOs.

x86: implemented roundings for SSE4.1

---

.appveyor.yml
.travis.yml
examples/nbody.rs
examples/play.rs
examples/types.rs
examples/wat.rs
src/lib.rs
src/macros.rs
src/simd_llvm.rs
src/v128.rs
src/v256.rs
src/v512.rs
src/v64.rs
src/x86/avx.rs
src/x86/avx2.rs
src/x86/bmi.rs
src/x86/macros.rs
src/x86/mod.rs
src/x86/runtime.rs
src/x86/sse.rs
src/x86/sse2.rs
src/x86/sse3.rs
src/x86/sse41.rs
src/x86/sse42.rs
src/x86/ssse3.rs
tests/cpu-detection.rs

[ci] enable clippy

---

src/x86/sse2.rs

`_mm_cvtsd_f64`, `_mm_cvtsd_si64x` and `_mm_cvttsd_si64x`.
See #40.

Add SSE2 trivial aliases and conversions.

---

src/x86/avx2.rs

From the Intel intrinsics manual (emphasis mine):
> Compute the absolute value of packed 16-bit integers in a, and store the
> *unsigned* results in dst.

Fix mm256_round_epi* return types

---

src/lib.rs
src/x86/sse2.rs
src/x86/sse41.rs

Fixes formatting and clippy issues due to latest changes.

[ci] fix formatting and clippy

---

src/x86/sse41.rs

Added pmin* instructions. Created 2 test cases for instructions with signed arguments - just in case :)
Also removed (a copy-paste typo?) ",87" in line 211.

[x86][sse4.1] Add pmin* instructions

---

stdsimd-test/assert-instr-macro/src/lib.rs

The syn API changed in the following commit breaking our builds: https://github.com/dtolnay/syn/commit/c6b55bcbe4627a9293b9354b3d76a7db8bf7d6dd 
This commit fixes it by using the new API.

syn API breaking change

---

src/macros.rs
src/simd_llvm.rs
src/v128.rs
src/v256.rs
src/v512.rs
src/v64.rs

Implements missing `std::ops` and adds test for all operators of all vector types.
Blocked on https://github.com/rust-lang/rust/pull/45804

Implement missing std::ops

---

src/lib.rs
src/x86/avx2.rs

- _mm256_cvtepu16_epi32
- _mm256_cvtepu16_epi64
- _mm256_cvtepu32_epi64
- _mm256_cvtepu8_epi16
- _mm256_cvtepu8_epi32
- _mm256_cvtepu8_epi64
An intermediate `u8x4` type is needed for the cast in `_mm256_cvtepu8_epi64`, so I defined one inline just like it's signed counterpart. I see there might be some overlap with other open PR's (regarding the `u8x4`), but this seemed like the best route to take for now given the context and the desire to define these just like they are in `avx2intrin.h`.

[avx2] add _mm_256_cvtepu{8,16,32}_epi{16,32,64}

---

Cargo.toml
ci/run.sh
src/lib.rs
src/macros.rs
src/nvptx/mod.rs
src/x86/mod.rs
src/x86/runtime.rs
src/x86/sse.rs
src/x86/sse2.rs

`stdsimd` does currently not compile as is with `#![no_std]`. 
This PR adds the "nostd" crate feature that enforces `#![no_std]` and ci test to cover this.
The only dependency `stdsimd` has on `std` is `std::os::raw::c_void`, which I've worked around by c&p `c_void` into the `x86` module. 
Once we merge ARM run-time feature detection it will also get a dependency on `std::fs`.  The plan is then to split stdsimd into a core component, and a std component.
---
The `nvptx` intrinsics are always available independently of the architecture, but one can only call them from an `nvptx` kernel.

add nvptx vendor intrinsics and initial no_std support

---

.travis.yml
Cargo.toml
ci/docker/aarch64-unknown-linux-gnu/Dockerfile
ci/run-docker.sh
ci/run.sh
src/lib.rs
src/macros.rs
src/runtime/aarch64.rs
src/runtime/arm.rs
src/runtime/bit.rs
src/runtime/cache.rs
src/runtime/linux/cpuinfo.rs
src/runtime/linux/mod.rs
src/runtime/macros.rs
src/runtime/mod.rs
src/runtime/x86.rs
src/x86/cpuid.rs
src/x86/ia32.rs
src/x86/mod.rs
src/x86/runtime.rs
src/x86/xsave.rs
stdsimd-test/simd-test-macro/src/lib.rs
tests/cpu-detection.rs

This PR implements:
- the `xsave` intrinsics,
- the `__readeflags`/`__writeeflags` intrinsics,
- the `cpuid` intrinsics (except for GCC's `__get_cpuid_max`, Issue #174 ), and
- run-time feature detection for `xsave` and `AVX-512`,
and fixes one bug:
- the `CPUID` instruction was used before testing whether the CPU supported it.
Note that the `has_cpuid` intrinsic does not exist in GCC nor Clang (it is a sub-set of GCC's `__get_cpuid_max`) but I've included it because we can make it a no-op on `x86_64` which is what most folks are targeting nowadays, which is useful for our own run-time feature detection support and for cpuid crates like @shepmaster's cupid.
This PR does arguably a lot of stuff. We need the `EFLAGS` intrinsics to properly refactor `cpuid` into its own intrinsic. We need …

XSAVE, CPUID, Runtime AVX-512 and ARM support

---

Cargo.toml
ci/run.sh
src/nvptx/mod.rs
src/x86/i386/eflags.rs
src/x86/i386/mod.rs
src/x86/i586/abm.rs
src/x86/i586/avx.rs
src/x86/i586/avx2.rs
src/x86/i586/bmi.rs
src/x86/i586/bmi2.rs
src/x86/i586/cpuid.rs
src/x86/i586/mod.rs
src/x86/i586/sse.rs
src/x86/i586/sse2.rs
src/x86/i586/sse3.rs
src/x86/i586/sse41.rs
src/x86/i586/sse42.rs
src/x86/i586/ssse3.rs
src/x86/i586/tbm.rs
src/x86/i586/xsave.rs
src/x86/i686/mod.rs
src/x86/i686/sse2.rs
src/x86/i686/sse41.rs
src/x86/i686/sse42.rs
src/x86/mod.rs
src/x86/x86_64/mod.rs
src/x86/x86_64/sse.rs
src/x86/x86_64/sse2.rs
src/x86/x86_64/sse42.rs

This PR refactors the x86 module into `i386`, `i586`, `i686` and `x86_64`. Most of the intrinsics that were previously `x86_64` only can now be used on `i686` as well.

refactor the x86 module

---

src/lib.rs
src/macros.rs
src/runtime/cache.rs
src/runtime/linux/cpuinfo.rs
src/runtime/x86.rs
src/x86/i586/avx.rs
src/x86/i586/cpuid.rs
src/x86/i586/sse.rs
src/x86/i586/sse2.rs
src/x86/i586/sse41.rs

This is more idiomatic for no-std-compatible crates where imports are
unconditionally rewritten to `core` and then only when necessary `std` is pulled
in explicitly.

Unconditionally flag as `#![no_std]`

---

Cargo.toml
src/nvptx/mod.rs
src/runtime/x86.rs
tests/cpu-detection.rs

Upgrade to cupid 0.0.5 and cleanup duplicated code in x86 run-time

---

src/x86/i586/avx2.rs

I'm having some issues compiling stdsimd on my avx2 machine (#201). I'll fix the tests and add the remaining gather intrinsics once I resolve that.

Add AVX2 gathers

---

coresimd/src/x86/i586/sse2.rs
coresimd/src/x86/x86_64/sse2.rs

`nontemporal_store` related intrinsics.

sse2: _mm_stream_*

---

src/runtime/aarch64.rs
src/runtime/arm.rs
src/runtime/linux/auxvec.rs
src/runtime/linux/cpuinfo.rs
src/runtime/linux/mod.rs
src/runtime/mod.rs
src/runtime/powerpc64.rs

The arm32 variant is not tested due a small hardware failure.

non-x86 runtime detection updates

---

coresimd/src/macros.rs
coresimd/src/x86/i586/avx.rs
coresimd/src/x86/i586/sse2.rs
coresimd/src/x86/i586/sse41.rs
coresimd/src/x86/i686/sse41.rs

- Adds `extract_unchecked` + `replace_unchecked` + `len` (#222 )
- Fixes the return types + uses `extract_unchecked` for:
- _mm_extract_epi8
- _mm_extract_epi16
- _mm256_extract_epi8
- _mm256_extract_epi16
- Minor changes to the other `extract_epi*` intrinsics for style consistency
These should now zero-extend the extracted int and behave appropriately. An old typo makes these a bit confusing, See [this](https://reviews.llvm.org/D20468) llvm issue.

Add `unchecked` methods, fix _mm_extract_epi* return types

---

coresimd/src/arm/neon.rs
coresimd/src/arm/v7.rs
coresimd/src/macros.rs
coresimd/src/runtime/x86.rs
coresimd/src/v128.rs
coresimd/src/x86/i586/avx.rs
coresimd/src/x86/i586/avx2.rs
coresimd/src/x86/i586/sse.rs
coresimd/src/x86/i586/sse2.rs
coresimd/src/x86/i586/sse3.rs
coresimd/src/x86/i586/sse41.rs
examples/nbody.rs
examples/play.rs
src/lib.rs
src/runtime/linux/auxvec.rs
src/runtime/linux/cpuinfo.rs
src/runtime/mod.rs
src/runtime/powerpc64.rs
stdsimd-test/src/lib.rs

After this rustfmt works again and the builds are green.
Hopefully we will be able to use it reliably some day soon. There have been some improvements upstream:
- `rustfmt` already lets us fix a particular version
-  we can install this version using `cargo install rustfmt-nightly --version x.y.z.`
-  but for that we need a particular nightly compiler.
It is easy to hardcode this on travis, but as a user this is still a pain to set up.

Fix rustfmt

---

coresimd/src/x86/i686/sse4a.rs

The endianness was reversed.
cc #249

fix sse4a _mm_stream_{ss, sd} tests and docs

---

.travis.yml
Cargo.toml
ci/run.sh
coresimd/src/x86/i586/abm.rs
coresimd/src/x86/i586/avx.rs
coresimd/src/x86/i586/avx2.rs
coresimd/src/x86/i586/bmi.rs
coresimd/src/x86/i586/bmi2.rs
coresimd/src/x86/i586/sse.rs
coresimd/src/x86/i586/sse2.rs
coresimd/src/x86/i586/sse41.rs
coresimd/src/x86/i586/sse42.rs
coresimd/src/x86/i586/xsave.rs
coresimd/src/x86/i686/mmx.rs
coresimd/src/x86/i686/sse.rs
coresimd/src/x86/i686/sse2.rs
coresimd/src/x86/i686/sse41.rs
coresimd/src/x86/i686/ssse3.rs
coresimd/src/x86/x86_64/mod.rs
coresimd/src/x86/x86_64/sse2.rs
coresimd/src/x86/x86_64/sse41.rs
coresimd/src/x86/x86_64/xsave.rs
stdsimd-test/assert-instr-macro/src/lib.rs
stdsimd-verify/.gitattributes
stdsimd-verify/Cargo.toml
stdsimd-verify/build.rs
stdsimd-verify/src/lib.rs
stdsimd-verify/tests/x86-intel.rs

This commit adds a new crate for testing that the intrinsics listed in this
crate do indeed match the upstream definition of each intrinsic. A
pre-downloaded XML description of all Intel intrinsics is checked in which is
then parsed in the `stdsimd-verify` crate to verify that everything we write
down is matched against the upstream definitions.
Currently the checks are pretty loose to get this compiling but a few intrinsics
were fixed as a result of this. For example:
* `_mm256_extract_epi8` - AVX2 intrinsic erroneously listed under AVX
* `_mm256_extract_epi16` - AVX2 intrinsic erroneously listed under AVX
* `_mm256_extract_epi32` - AVX2 intrinsic erroneously listed under AVX
* `_mm256_extract_epi64` - AVX2 intrinsic erroneously listed under AVX
* `_mm_tzcnt_32` - erroneously had `u32` …

Verify Intel intrinsics against upstream definitions

---

coresimd/src/x86/i586/sse2.rs
coresimd/src/x86/i586/sse3.rs
coresimd/src/x86/i686/ssse3.rs

Missing assert_instr:
- _mm_cvtsi32_si128
- _mm_cvtsi128_si32
- _mm_loadl_epi64
- _mm_storel_epi64
- _mm_move_epi64
- _mm_cvtsd_f64
- _mm_setzero_pd
- _mm_load1_pd
- _mm_load_pd1
- _mm_loaddup_pd
Wrong intrusction used:
- _mm_hsub_pi16

Fix some assert_instr

---

coresimd/src/x86/i686/mmx.rs
coresimd/src/x86/i686/sse.rs

And mmx:
_mm_cmpgt_pi8
_mm_cmpgt_pi16
_mm_unpackhi_pi16
_mm_unpacklo_pi8
_mm_unpacklo_pi16
sse is complete.

sse: _mm_cvtpi16_ps, _mm_cvtpu16_ps, _mm_cvtpi8_ps, _mm_cvtpu8_ps

---

coresimd/src/x86/i586/avx.rs
coresimd/src/x86/i586/avx2.rs

avx and avx2 is complete.
For _mm256_slli_si256 and _mm256_srli_si256, I don't know why Clang does not use the builtin instructions ?

Last missing avx and avx2 intrinsics

---

coresimd/src/x86/i686/mmx.rs
coresimd/src/x86/i686/sse.rs
coresimd/src/x86/i686/sse41.rs
coresimd/src/x86/i686/ssse3.rs
stdsimd-test/src/lib.rs

This adds an assertion with the `assert_instr` macro that intrinsics aren't literally calling one another but rather everything is nice and inlined. This then touches up various intrinsics that accidentally had a `call` instruction in their implementation.

Assert intrinsic implementations are inlined properly

---

coresimd/src/x86/i586/bswap.rs
coresimd/src/x86/i586/sse.rs
coresimd/src/x86/i686/mmx.rs
coresimd/src/x86/i686/sse.rs
coresimd/src/x86/i686/sse2.rs
coresimd/src/x86/i686/sse4a.rs
coresimd/src/x86/i686/ssse3.rs
coresimd/src/x86/macros.rs
coresimd/src/x86/x86_64/sse41.rs
stdsimd-test/assert-instr-macro/src/lib.rs
stdsimd-test/src/lib.rs
stdsimd-verify/build.rs
stdsimd-verify/src/lib.rs
stdsimd-verify/tests/x86-intel.rs

MMX:
- `_mm_cmpgt_pi{8,16,32}`
- `_mm_unpack{hi,lo}_pi{8,16,32}`
SSE (is now complete):
- `_mm_cvtp{i,u}{8,16}_ps`
- add test for `_m_pmulhuw`

Completes SSE and adds some MMX intrinsics

---

coresimd/src/x86/i686/mmx.rs

Regarding Issue #40.
* Implements all x86 MMX intrinsics regarding addition and adds basic unit tests for them.
- `_mm_add_pi{8, 16, 32}`
- `_mm_adds_pi{8, 16}`
- `_mm_adds_pu{8, 16}`

Implement all addition MMX intrinsics

---

coresimd/src/x86/i586/avx.rs
coresimd/src/x86/i586/sse.rs
coresimd/src/x86/i686/sse.rs
examples/nbody.rs

This migrates the entire `i686::sse` module (and touches a few others) to the
vendor types.

Migrate the `i686::sse` module to vendor types

---

coresimd/src/x86/i586/sse42.rs

Move all the casts from `__m128i` to `i8x16` outside the macro invocations so
rustc only has to resolve a few function calls, not thousands!

Make rustc's job a little esaier in sse42

---

coresimd/src/x86/i686/mmx.rs

Implement all MMX subtraction instructions
- `_m_psubb` and `_mm_sub_pi8`
- `_m_psubw` and `_mm_sub_pi16`
- `_m_psubd` and `_mm_sub_pi32`
- `_m_psubsb` and `_mm_subs_pi8`
- `_m_psubsw` and `_mm_subs_pi16`
- `_m_psubusb` and `_mm_subs_pu8`
- `_m_psubusw` and `_mm_subs_pu16`

MMX subtraction instructions

---

coresimd/src/x86/i686/mmx.rs

- `_m_paddb` for `_mm_add_pi8`
- `_m_paddw` for `_mm_add_pi16`
- `_m_paddd` for `_mm_add_pi32`
- `_m_paddsb` for `_mm_adds_pi8`
- `_m_paddsw` for `_mm_adds_pi16`
- `_m_paddusb` for `_mm_adds_pu8`
- `_m_paddusw` for `_mm_adds_pu16`

Implement MMX addition aliases

---

ci/docker/i586-unknown-linux-gnu/Dockerfile
ci/docker/i686-unknown-linux-gnu/Dockerfile
ci/docker/x86_64-unknown-linux-gnu-emulated/Dockerfile
ci/docker/x86_64-unknown-linux-gnu/Dockerfile
coresimd/src/x86/i586/avx.rs
coresimd/src/x86/i586/avx2.rs
coresimd/src/x86/mod.rs
coresimd/src/x86/test.rs

Migrate the `i586::avx` module to vendor types

---

Cargo.toml
coresimd/Cargo.toml

Resolves crates.io badge display issues:

Update links in Cargo.toml to rust-lang-nursery/stdsimd

---

coresimd/src/x86/i586/avx2.rs
coresimd/src/x86/i686/sse4a.rs
coresimd/src/x86/test.rs
stdsimd-verify/src/lib.rs
stdsimd-verify/tests/x86-intel.rs

This commit provides insurance that intrinsics are only introduced with known
canonical types (`__m128i` and such) instead of also allowing `u8x16` for
example.
Closes #263

Update stdsimd-verify for vendor types

---

coresimd/src/x86/i586/sse2.rs
coresimd/src/x86/i686/sse2.rs
coresimd/src/x86/i686/sse41.rs
coresimd/src/x86/x86_64/sse2.rs

They need to be structured *somehow* to be the right bit width but ideally we
wouldn't have the intrinsics rely on the particulars about how they're
represented.

Reduce implicit reliance on structure of __m* types

---

Cargo.toml
examples/hex.rs

This is lifted from an example elsewhere I found and shows off runtime
dispatching along with a lot of intrinsics being used in a bunch.

Add an example of SIMD-powered hex encoding

---

coresimd/src/v128.rs
coresimd/src/v256.rs
coresimd/src/v64.rs
coresimd/src/x86/i586/sse.rs
coresimd/src/x86/i686/mmx.rs
coresimd/src/x86/i686/ssse3.rs
coresimd/src/x86/mod.rs

I believe we're reserving the `simd` module for exclusively the portable types
and their operations, so this commit moves the various x86-specific types from
the portable modules to the `x86` module. Along the way this also adds some doc
blocks for all the existing x86 types.

Move x86-specific types to the `vendor` module

---

coresimd/src/x86/i586/avx.rs
coresimd/src/x86/i586/avx2.rs
coresimd/src/x86/i586/sse.rs
coresimd/src/x86/i586/sse2.rs
coresimd/src/x86/i586/sse3.rs
coresimd/src/x86/i586/sse41.rs
coresimd/src/x86/i586/sse42.rs
coresimd/src/x86/i586/ssse3.rs
coresimd/src/x86/i686/mmx.rs
coresimd/src/x86/i686/sse.rs
coresimd/src/x86/i686/sse2.rs
coresimd/src/x86/i686/sse42.rs
coresimd/src/x86/i686/sse4a.rs
coresimd/src/x86/i686/ssse3.rs
coresimd/src/x86/mod.rs
coresimd/src/x86/test.rs
coresimd/src/x86/x86_64/sse2.rs
coresimd/src/x86/x86_64/sse41.rs

This is mostly just being more conservative with them!

Remove PartialEq impls for x86 types

---

stdsimd-test/assert-instr-macro/src/lib.rs

In rust-lang/rust#47743 the SIMD types in the Rust ABI are being switched to
getting passed through memory unconditionally rather than through LLVM's
immediate registers. This means that a bunch of our assert_instr invocations
started breaking as LLVM has more efficient methods of dealing with memory than
the instructions themselves.
This switches `assert_instr` to unconditionally use a shim that is an `extern`
function which should revert back to the previous behavior, using the simd types
as immediates and testing the same.

Fix tests for a future nightly

---

coresimd/src/lib.rs
coresimd/src/x86/i686/sse.rs
coresimd/src/x86/i686/sse2.rs
coresimd/src/x86/i686/ssse3.rs
coresimd/src/x86/mod.rs

This was historically done as the contents of the `i686` module wouldn't
actually compile on i586 for various reasons. I believe I've tracked this down
to #300 where LLVM refuses to compile a function using the `x86_mmx` type
without actually enabling the `mmx` feature (sort of reasonably so!). This
commit will now compile in both the `i586` and `i686` modules of this crate into
the `i586-unknown-linux-gnu` target, and the relevant functions now also enable
the `mmx` feature if they're using the `__m64` type.
I believe this is uncovering a more widespread problem where the `__m64` isn't
usable outside the context of `mmx`-enabled functions. The i686 and x86_64
targets have this feature enabled by default which is why it's worked there, but
they're not enabled for the i586 target. We'll …

Don't distinguish between i586/i686

---

coresimd/src/lib.rs
coresimd/src/x86/i586/abm.rs
coresimd/src/x86/i586/avx.rs
coresimd/src/x86/i586/avx2.rs
coresimd/src/x86/i586/bmi.rs
coresimd/src/x86/i586/bmi2.rs
coresimd/src/x86/test.rs
coresimd/src/x86/x86_64/abm.rs
coresimd/src/x86/x86_64/avx.rs
coresimd/src/x86/x86_64/avx2.rs
coresimd/src/x86/x86_64/bmi.rs
coresimd/src/x86/x86_64/bmi2.rs
coresimd/src/x86/x86_64/mod.rs
stdsimd-verify/src/lib.rs
stdsimd-verify/tests/x86-intel.rs

Some intrinsics take `i64` or `u64` arguments which typically means that they're
using 64-bit registers and aren't actually available on x86. This commit adds a
check to stdsimd-verify to assert this and moves around some intrinsics that I
believe should only be available on x86_64.
This commit was checked in many places against gcc/clang/MSVC using godbolt.org
to ensure that we're agreeing with what other compilers are doing.
Closes #304

Verify intrinsics don't leak to i686

---

coresimd/src/x86/i586/rdtsc.rs
coresimd/src/x86/x86_64/bswap.rs
coresimd/src/x86/x86_64/mod.rs
stdsimd-verify/src/lib.rs
stdsimd-verify/tests/x86-intel.rs

Looks like intrinsics that weren't listing a target feature were accidentally
omitted from the verification logic, so this commit fixes that!
Along the way I've ended up filing #307 and #308 for detected inconsistencies.

Enable verification of more intrinsics

---

coresimd/src/x86/i586/sse2.rs
coresimd/src/x86/i586/sse41.rs
coresimd/src/x86/i686/sse.rs
stdsimd-verify/tests/x86-intel.rs

We had a few lingering intrinsics which were getting some special
treatment for having different types than what Intel specified. This
commit removes all these cases and reverts to precisely what upstream
Intel mentions (even if it doesn't make the most sense in some cases)

Remove known exceptions to Intel's signatures

---

coresimd/src/lib.rs
coresimd/src/x86/i586/avx.rs
coresimd/src/x86/i586/avx2.rs
coresimd/src/x86/i586/sse.rs
coresimd/src/x86/i586/sse2.rs
coresimd/src/x86/i586/sse41.rs
coresimd/src/x86/x86_64/sse41.rs
stdsimd-test/assert-instr-macro/src/lib.rs

Looks like some instructions changed here and there, so this updates the
assertions (no behavior appears to have changed though)

Fix instruction assertions on LLVM 6

---

coresimd/src/lib.rs
coresimd/src/x86/i586/avx.rs
coresimd/src/x86/i586/avx2.rs
coresimd/src/x86/i586/sse.rs
coresimd/src/x86/i586/sse2.rs
coresimd/src/x86/i586/sse41.rs
coresimd/src/x86/i586/sse42.rs
coresimd/src/x86/i586/ssse3.rs
coresimd/src/x86/i686/aes.rs
coresimd/src/x86/i686/sse.rs
coresimd/src/x86/i686/ssse3.rs
coresimd/src/x86/x86_64/avx.rs
coresimd/src/x86/x86_64/avx2.rs
coresimd/src/x86/x86_64/sse41.rs
stdsimd-verify/src/lib.rs
stdsimd-verify/tests/x86-intel.rs

Support isn't quite in nightly to make this work yet, but using a local build
this gets everything passing again! This also implements native verification
that we have the attribute in the right place

Add #[rustc_args_required_const] annotations

---

coresimd/mod.rs
coresimd/x86/i586/avx2.rs
coresimd/x86/i586/sse.rs
coresimd/x86/i586/sse41.rs
coresimd/x86/i586/sse42.rs
coresimd/x86/mod.rs
crates/coresimd/src/lib.rs
crates/coresimd/tests/cpu-detection.rs
crates/stdsimd/src/lib.rs
crates/stdsimd/tests/cpu-detection.rs
stdsimd/arch/detect/aarch64.rs
stdsimd/arch/detect/arm.rs
stdsimd/arch/detect/powerpc64.rs
stdsimd/arch/detect/x86.rs
stdsimd/mod.rs

To integrate into the standard library this crate needs *at least* a
stability attribute on the macro itself but this commit also beings by
adding unstable attributes to the exported modules as well. This should
help everything be unstable-by-default and we can start iterating from
there in the standard library.
This commit also does away with the `coresimd::vendor` module internal
implementation detail, instead directly creating the `arch` module to
allow easily documenting it in this crate and having the docs show up in
rust-lang/rust.

Start adding stability attributes

---

crates/stdsimd/Cargo.toml
examples/hex.rs
examples/nbody.rs

Make sure the top-level `examples` folder is registered with the
`stdsimd` crate!

Compile examples on CI

---

coresimd/mod.rs
crates/coresimd/src/lib.rs
crates/stdsimd/src/lib.rs
stdsimd/mod.rs

This commit reorganizes some documentation for inclusion into the standard
library, moving the bulk of the docs to the `arch` module and away from the
crate root which won't actually be the end-user interface.

Beef up documentation of `arch` module

---

coresimd/x86/i586/xsave.rs

Looks like LLVM 3.9 doesn't have the intrinsic, and this implementation is
modeled after clang's.

Reimplement `_xgetbv` with inline assembly

---

ci/run.sh
coresimd/aarch64/neon.rs
coresimd/arm/neon.rs

* adds {s,u,f}{min,max}{v,p} AArch64 intrinsics
* adds {vmov}{n,l} ARM intrinsics
Closes #314 (the missing part there are portable shuffles, but I'll open a new issue just for that). 
cc @hsivonen.

adds AArch64's {s,u,f}{min,max}{v,p} and ARM's {vmov}{n,l}

---

crates/stdsimd/src/lib.rs
stdsimd/arch/detect/aarch64.rs
stdsimd/arch/detect/arm.rs
stdsimd/arch/detect/powerpc64.rs
stdsimd/arch/detect/x86.rs

This way if the feature is statically detected then it'll be expanded to `true`
Closes #349

Add `cfg!` clauses to detection macro

---

.travis.yml
coresimd/aarch64/neon.rs
coresimd/ppsv/api/bitwise_reductions.rs
coresimd/ppsv/api/cmp.rs
coresimd/ppsv/codegen/and.rs
coresimd/ppsv/codegen/max.rs
coresimd/ppsv/codegen/min.rs
coresimd/ppsv/codegen/or.rs
coresimd/ppsv/codegen/product.rs
coresimd/ppsv/codegen/sum.rs
coresimd/ppsv/codegen/xor.rs
coresimd/ppsv/v128.rs
coresimd/ppsv/v256.rs
coresimd/ppsv/v32.rs
coresimd/ppsv/v512.rs
coresimd/ppsv/v64.rs
coresimd/x86/mod.rs
crates/coresimd/tests/cpu-detection.rs
crates/stdsimd/tests/cpu-detection.rs
stdsimd/arch/detect/mod.rs
stdsimd/mod.rs

rustfmt-preview is what everybody should be using anyways, it has been available for two months, and I've been using it in other projects via travis-ci with success. AFAICT I haven't had any spurious failures because of it.

Migrate to rustfmt-preview and require rustfmt builds to pass

---

.travis.yml
coresimd/mod.rs
coresimd/wasm32.rs
crates/stdsimd/Cargo.toml
examples/wasm.rs
stdsimd/arch/detect/cache.rs
stdsimd/mod.rs

This exposes access to the `grow_memory` and `current_memory` instructions
provided by wasm in what will hopefully be a stable interface (the stable part
being x86 first in theory).

Add initial wasm memory grow/current intrinsics

---

coresimd/mod.rs
crates/coresimd/src/lib.rs
crates/stdsimd/src/lib.rs
stdsimd/mod.rs

This PR adds the `doc_cfg` feature to coresimd and stdsimd to tell rustdoc about which arch is required for each module. It also uses the `#[cfg(dox)]` configuration flag that the rest of libstd uses to ensure that all four major arch modules are included when rustdoc builds the library. This worked great for coresimd, which now proudly shows all the arch intrinsics. However, when trying to re-export these modules in stdsimd, the cfg(dox) trick doesn't work any more, so instead we mask out these modules and link to libcore. Rather than show the full docs for whatever the native arch of the build environment was, i masked out all of them and stubbed them out.
For a preview, i have [a rendering on my server](https://tonberry.quietmisdreavus.net/simd-std/core/arch/index.html). Here's what …

document all arches when part of std

---

coresimd/ppsv/api/arithmetic_reductions.rs
coresimd/ppsv/api/bitwise_reductions.rs
coresimd/ppsv/api/boolean_reductions.rs
coresimd/ppsv/api/minmax_reductions.rs

I came up with a reproducer for the "failed to select reduction" bugs on AArch64. This PR links the LLVM bug in the appropriate places: https://bugs.llvm.org/show_bug.cgi?id=36796

add llvm bug for reductions on aarch64

---

coresimd/ppsv/api/arithmetic_scalar_ops.rs
coresimd/ppsv/api/bitwise_ops.rs
coresimd/ppsv/api/bitwise_scalar_ops.rs
coresimd/ppsv/api/mod.rs
coresimd/ppsv/api/scalar_shifts.rs
coresimd/ppsv/api/shifts.rs

Today some of the traits are implemented for vectors, and some of them are implemented for scalars:
```rust
let u = i32x4::new(1, 2, 3, 4);
let v = u << 1; // OK
let w = 1 << v; // ERROR
let t = v << v; // ERROR
let u= f32x4::new(1., 2., 3., 4.);
let v = u+ u;  // OK
let w = 1_f32 + v; // ERROR
let t = v + 1_f32; // ERROR
```
This PR fixes these errors for all operators. The implementation is compartmentalized so that we don't need to stabilize all of these at once. For example, we can stabilize (vector, vector) -> vector binary ops first, and decide on (vector, scalar) -> vector and (scalar, vector) -> vector later. 
It is important to be comprehensive with the `std::ops` traits because due to trait coherence users cannot implement them themselves on the portable vector types. Having …

Add std::ops for vector-scalars

---

ci/run.sh
coresimd/aarch64/mod.rs
coresimd/aarch64/neon.rs
coresimd/aarch64/v8.rs
coresimd/arm/mod.rs
coresimd/arm/neon.rs
coresimd/arm/v7.rs
coresimd/macros.rs
coresimd/mod.rs
coresimd/ppsv/mod.rs
coresimd/ppsv/v128.rs
coresimd/ppsv/v256.rs
coresimd/ppsv/v64.rs
coresimd/x86/mod.rs
crates/coresimd/tests/v128.rs
crates/coresimd/tests/v16.rs
crates/coresimd/tests/v256.rs
crates/coresimd/tests/v32.rs
crates/coresimd/tests/v512.rs
crates/coresimd/tests/v64.rs
crates/simd-test-macro/src/lib.rs
examples/nbody.rs
stdsimd/arch/detect/arch/arm.rs

NEON is supported on:
* AArch64
* ARM when built with the `v7` and `neon` features. Building only with `v7` and trying to use run-time feature detection result in bad codegen. This might be a bug?
---
This PR adds ARM/AArch64 NEON architecture-specific vector types:
* ARM:
* 64-bit wide: float32x2_t, int16x4_t, int32x2_t, int64x1_t, int8x8_t, poly16x4_t, poly8x8_t, uint16x4_t, uint32x2_t, uint64x1_t, uint8x8_t
* 128-bit wide: float32x4_t, int16x8_t, int32x4_t, int64x2_t, int8x16_t, poly16x8_t, poly8x16_t, uint16x8_t, uint32x4_t, uint64x2_t, uint8x16_t
* AArch64:
* 64-bit wide: float32x2_t, float64x1_t, int16x4_t, int32x2_t, int64x1_t, int8x8_t, poly16x4_t, poly8x8_t, uint16x4_t, uint32x2_t, uint64x1_t, uint8x8_t
* 128-bit wide: float32x4_t, float64x2_t, int16x8_t, int32x4_t, …

Add arm neon vector types and fixes ARM tests

---

coresimd/macros.rs
coresimd/ppsv/api/bool_vectors.rs
coresimd/ppsv/api/minimal.rs
coresimd/ppsv/api/mod.rs

Remove clone impls of repr(simd) types (derives Clone instead).

---

crates/coresimd/build.rs
crates/simd-test-macro/src/lib.rs

Turns out Cargo doesn't automatically set `TARGET` for rustc invocations so
carry it forward manually from the build script over to the rustc invocation.

Fix default `cargo test` experience

---

crates/coresimd/tests/endian_tests.rs

This PR adds some tests that run for all architecture and check that type-punning via unions from/to arrays/tuples works correctly.

Tests for type punning via unions to/from arrays/tuples

---

crates/coresimd/tests/endian_tests.rs

Using type punning via an union from a vector type to a tuple or array in general currently results in unspecified (and platform-dependent) behavior.
If the array or tuple have the same element type as the vector, this operation just happen to work (e.g. see some of the previous tests). But when the array or tuple types differ, we get unspecified platform-specific behavior (see the new tests). These cases are basically the same as bit-casting between vectors of different number of lanes.
Also I had to use `repr(C)` to force the tuple layout because otherwise I was getting complete garbage. Possibly because the compiler might reorder the tuple fields to reduce padding. In any case, the layout of tuple elements is completely unspecified, and rustc does use this fact to optimize things …

Endian-dependent type-punning from vectors to tuples and arrays

---

coresimd/x86/fxsr.rs
coresimd/x86/mod.rs
coresimd/x86_64/fxsr.rs
coresimd/x86_64/mod.rs

The `fxsr` feature was already whitelisted upstream. If this fails, then it has other issues.

Enable fxsr

---

ci/run.sh
coresimd/ppsv/api/arithmetic_reductions.rs
coresimd/ppsv/api/minmax_reductions.rs
coresimd/ppsv/mod.rs
crates/coresimd/tests/reductions.rs

This PR documents the arithmetic reductions and updates `stdsimd` to the latest changes in the RFC:
* `sum` -> `wrapping_sum`
* `product` -> `wrapping_product`
* `min` -> `min_element`
* `max` -> `max_element`.
Currently there are two open issues that affect computations involving `NaN`s:
* `llvm.experimental.vector.reduce.f{min,max}` do not behave like we'd like with respect to `NaN`s due to https://github.com/rust-lang-nursery/stdsimd/issues/408 (which points to the LLVM bug). Basically, we want these to behave like `min`/`max` for floating point numbers, that is, they should always return a number unless all elements in a vector are `NaN` just like IEEE-754 `{min,max}Num` and `{minimum,maximum}Number` do. Right now, they behave more like `fcmp+select`, producing different results …

Documents arithmetic reduction semantics

---

.travis.yml
ci/run.sh
coresimd/macros.rs
coresimd/ppsv/api/masks_reductions.rs
coresimd/ppsv/codegen/masks_reductions.rs
coresimd/ppsv/codegen/mod.rs
coresimd/ppsv/codegen/wrapping.rs
coresimd/ppsv/mod.rs
crates/assert-instr-macro/src/lib.rs
crates/coresimd/Cargo.toml
crates/coresimd/src/lib.rs
examples/nbody.rs

This commit adds workarounds for the mask reductions: `all` and `any`.
Note:
* not all LLVM bugs have been properly reported yet
* workarounds for 256-bit wide vector masks on armv7 and aarch64 are
not provided in this PR
```asm
all_8x8:
push    rbp
mov     rbp, rsp
movzx   eax, byte, ptr, [rdi, +, 7]
movd    xmm0, eax
movzx   eax, byte, ptr, [rdi, +, 6]
movd    xmm1, eax
punpcklwd xmm1, xmm0
movzx   eax, byte, ptr, [rdi, +, 5]
movd    xmm0, eax
movzx   eax, byte, ptr, [rdi, +, 4]
movd    xmm2, eax
punpcklwd xmm2, xmm0
punpckldq xmm2, xmm1
movzx   eax, byte, ptr, [rdi, +, 3]
movd    xmm0, eax
movzx   eax, byte, ptr, [rdi, +, 2]
movd    xmm1, eax
punpcklwd xmm1, xmm0
movzx   eax, byte, ptr, [rdi, +, 1]
movd    xmm0, eax
movzx   eax, byte, ptr, [rdi]
movd    xmm3, eax
punpcklwd xmm3, xmm0 …
```

Workarounds for all/any mask reductions on x86, armv7, and aarch64

---

coresimd/x86/fma.rs
coresimd/x86/mod.rs

The whole instruction set is implemented, as described [here](https://software.intel.com/sites/landingpage/IntrinsicsGuide/#techs=FMA).
This closes #341.

Add support for x86 FMA extension

---

stdsimd/arch/detect/arch/aarch64.rs
stdsimd/arch/detect/arch/arm.rs
stdsimd/arch/detect/arch/mips.rs
stdsimd/arch/detect/arch/mips64.rs
stdsimd/arch/detect/arch/powerpc64.rs
stdsimd/arch/detect/arch/x86.rs

This is cleaner than just having a #[doc(hidden)] attribute

Make the Feature enum unstable

---

ci/docker/powerpc-unknown-linux-gnu/Dockerfile
ci/run.sh
coresimd/mod.rs
coresimd/powerpc/altivec.rs
coresimd/powerpc/mod.rs
coresimd/powerpc/vsx.rs
coresimd/powerpc64/mod.rs
coresimd/powerpc64/vsx.rs
coresimd/ppsv/mod.rs
crates/assert-instr-macro/src/lib.rs
crates/coresimd/src/lib.rs

This PR adds a single altivec intrinsic and sets up the vsx module for the PowerPC architecture.
Due to issues with `qemu`, the `assert_instr` tests are not run on `powerpc` and `powerpc64` (big endian); they are only run on `powerpc64le`. We should fix that at some point (issue: https://github.com/rust-lang-nursery/stdsimd/issues/448).
The PowerPC C intrinsics use compiler magic to do function overloading in C, such that for example in this case `vec_add(x, y)` corresponds to different functions depending on the types of `x` and `y`. This happens for all (or most) of the `altivec` and `vsx` intrinsics.
To match the C API the `vec_add` intrinsic is implemented as:
```rust
#[inline]
#[target_feature(enable = "altivec")]
pub unsafe fn vec_add<T, U>(a: T, b: U) -> <T as …
```

Initial PowerPC altivec and VSX support

---

coresimd/powerpc/altivec.rs
crates/simd-test-macro/src/lib.rs
crates/stdsimd/tests/cpu-detection.rs
stdsimd/arch/detect/arch/powerpc.rs
stdsimd/arch/detect/error_macros.rs
stdsimd/arch/detect/mod.rs
stdsimd/arch/detect/os/linux/mod.rs
stdsimd/arch/detect/os/linux/powerpc.rs
stdsimd/mod.rs

This PR adds run-time feature detection for 32-bit PowerPC. The backend on Linux is the same as for PowerPC64, so this just adds the feature detection macro for PowerPC, a test, and updates the docs in `stdsimd`. It also re-enables running the tests on 32-bit PowerPC.

add run-time feature detection for powerpc

---

coresimd/powerpc/altivec.rs
coresimd/powerpc64/vsx.rs

This PR makes PowerPC vector types be newtypes instead of type aliases to the portable-vector types. It provides the `from_bits`/`into_bits` methods for convenience.

make powerpc vector types newtypes

---

.travis.yml
ci/run.sh
crates/assert-instr-macro/Cargo.toml
crates/assert-instr-macro/src/lib.rs
crates/coresimd/src/lib.rs
crates/simd-test-macro/Cargo.toml
crates/simd-test-macro/src/lib.rs
crates/stdsimd-test/src/lib.rs
crates/stdsimd-verify/Cargo.toml
crates/stdsimd-verify/src/lib.rs

Update to the latest version of proc_macro2, quote and syn.

Update proc macro2

---

stdsimd/mod.rs

The is_feature_detected! macro was renamed (#346), so "The name of the macro is the same across platforms" is false. Let's just remove that sentence.

Fix outdated docs

---

coresimd/mod.rs
crates/coresimd/src/lib.rs
crates/stdsimd/src/lib.rs
stdsimd/arch/detect/arch/aarch64.rs
stdsimd/arch/detect/arch/arm.rs
stdsimd/arch/detect/arch/mips.rs
stdsimd/arch/detect/arch/mips64.rs
stdsimd/arch/detect/arch/powerpc.rs
stdsimd/arch/detect/arch/powerpc64.rs
stdsimd/arch/detect/error_macros.rs
stdsimd/mod.rs

https://github.com/rust-lang/rust/issues/27731

Make SIMD tracking issue marked for `stdsimd` too

---

coresimd/mod.rs

Should fix https://github.com/rust-lang/rust/issues/50988, but we'll need to run doctests for libcore on a powerpc64 machine to be sure
This applies `#[doc(cfg(...))]` attributes to the internal backing modules so that if doctests are run from these private modules (which they *shouldn't*, but the linked issue implies that they are...), they still have the proper `target_arch` filtering. This will make the docs for these items much more noisy, but i have a plan to patch rustdoc to "reduce" these conditionals, at least for the case being introduced here.

tag private modules with doc(cfg)

---

coresimd/ppsv/api/float_math.rs
coresimd/ppsv/api/mod.rs
coresimd/ppsv/codegen/abs.rs
coresimd/ppsv/codegen/cos.rs
coresimd/ppsv/codegen/fma.rs
coresimd/ppsv/codegen/mod.rs
coresimd/ppsv/codegen/sin.rs
coresimd/ppsv/codegen/sqrt.rs
coresimd/simd_llvm.rs

This adds the following vertical operations to the portable floating-point types: `abs`, `sqrt`, `sqrte`, `rsqrte`, `fma`, `sin`, `cos`.

Portable vertical floating-point mathematical functions

---

stdsimd/arch/detect/arch/aarch64.rs

Well, since I reported it I guess I should do something about it.
~~Note this is a *cough* **breaking change.**~~
**Edit:** Never mind the "breaking change," I mistakenly thought the string I changed was the macro LHS.
---
Closes #442.

"dotprot" -> "dotprod"

---

coresimd/x86/sse.rs

Mimics the macro defined in xmmintrin.h defines a _MM_SHUFFLE macro which is use to generate the mask used for _mm_shuffle and other similar instructions. Fixes issue #475.

Added _MM_SHUFFLE utility function.

---

coresimd/mod.rs

The cfg for the target is already covered a few lines below.
This cfg meant that even with the dox feature enabled, no
documentation for powerpc64 was generated except you were
actually targetting the powerpc64 arch.

Remove stray inconsistent #[cfg]

---

.travis.yml
ci/android-install-ndk.sh
ci/android-install-sdk.sh
ci/android-sysimage.sh
ci/docker/aarch64-linux-android/Dockerfile
ci/docker/arm-linux-androideabi/Dockerfile
ci/docker/x86_64-linux-android/Dockerfile
ci/run-docker.sh
ci/run.sh
ci/runtest-android.rs
crates/stdsimd-test/src/lib.rs
crates/stdsimd/tests/cpu-detection.rs

This PR adds CI for android targets:
* x86_64-linux-android
* arm-linux-androideabi 
* aarch64-linux-android
The `assert_instr` tests are disabled on these via the `STDSIMD_ASSERT_INSTR_IGNORE` environment variable. 
cc @rubdos
---
@alexcrichton  IIUC it is possible to copy the `objdump` binaries of the target into the android emulator, but I did not find a way to pass the emulator any environment variables. One might be able to get those tests to run by hardcoding the paths to `objdump` within the emulator via a `build.rs` script. Since we are already testing these archs in other build bots, I just disabled here this part of the tests.
I've allowed the`x86_64-linux-android` target to fail because of issue: https://github.com/rust-lang-nursery/stdsimd/issues/368

Add CI for android

---

coresimd/ppsv/api/minmax.rs

The `max` methods claimed to return the minimum in one location.

Fix typo in `max` docs

---

coresimd/x86/cpuid.rs

Closes https://github.com/rust-lang/rust/issues/51691

Fix has_cpuid implementation

---

stdsimd/arch/detect/os/x86.rs

Calling xgetbv is safe only if the OS has set osxsave.

---

coresimd/x86/cpuid.rs

Optimize has_cpuid for x86 Rust targets that have cpuid

---

.travis.yml
ci/docker/s390x-unknown-linux-gnu/Dockerfile
coresimd/ppsv/codegen/abs.rs
coresimd/ppsv/codegen/cos.rs
coresimd/ppsv/codegen/fma.rs
coresimd/ppsv/codegen/sin.rs
coresimd/ppsv/codegen/sqrt.rs
crates/coresimd/tests/reductions.rs

This adds CI for s390-unknown-linux-gnu (build only) and fixes the builds by falling back to scalar code for the portable floating-point vector types. 
I've filled #501 to track using the LLVM vector intrinsics directly on `s390x`, and I've filled #503 to track enabling running the tests on CI. 
cc @malbarbo

Adds CI for S390x and fix s390x-unknown-linux-gnu build

---

coresimd/x86/eflags.rs

This deprecates `__{read,write}eflags`.

deprecate read/write eflags

---

coresimd/powerpc/altivec.rs

Typo introduced in 1d6ccad0136cd1ed97dbb83b4975d8feb6fec059

Test vec_mradds and not vec_madds

---

coresimd/x86/sse.rs

Making _MM_SHUFFLE unstable as it turns out some intrinsics take i32 and some u32 which means this helper doesn't return the correct type in all cases.
See #522

Make _MM_SHUFFLE unstable.

---

crates/assert-instr-macro/src/lib.rs
crates/coresimd/src/lib.rs
crates/simd-test-macro/src/lib.rs
crates/stdsimd-test/src/lib.rs
crates/stdsimd-verify/src/lib.rs
crates/stdsimd-verify/tests/x86-intel.rs

The `proc_macro` feature has stabilized in the compiler and usage of it largely
needs to switch to `use_extern_macros` now.
Closes #526

Fix compile on latest nightly

---

.travis.yml
coresimd/arm/cmsis.rs
coresimd/arm/mod.rs

The implementation uses inline assembly and it's pretty much a copy paste of the CMSIS
implementation. Most of these intrinsics are only available on Cortex-M; this initial
implementation doesn't attempt to make the more general intrinsics available on Cortex-A or
Cortex-R.
Should we attempt to make some of these intrinsics available on Cortex-A and Cortex-R *before*
landing this PR? CMSIS provides information about Cortex-A; these intrinsics are available on both
Cortex-M and Cortex-A:
- {enable,disable}_irq
- NOP
- WFI
- WFE
- SEV
- ISB
- DSB
- DMB
But CMSIS doesn't provide any information about Cortex-R.
This PR depends on the "mclass" target feature which PR rust-lang/rust#52120 adds.
r? @gnzlbg
maybe @andre-richter, @Lakier15, or @paoloteti can tell us which of these intrinsics …

add CMSIS / Cortex-M instrinsics

---

ci/run.sh
coresimd/powerpc/mod.rs

We're running into issues updating with rust-lang/rust#52535, so we need to get
this working without `RUSTFLAGS` enabling the `altivec` feature

Fix compile of stdsimd on powerpc with no flags

---

coresimd/arm/dsp.rs
coresimd/arm/mod.rs
crates/stdsimd-test/src/lib.rs

Add few ARM DSP intrinsics:
- Signed saturating add/sub
- Saturating four 8-bit integer add/sub
- Saturating two 8-bit integer add/sub
The intent is mainly to setup the module and to add all the rest in the future.
Listed intrinsics are available on Cortex-M too (`+dsp` is required on some model except on M4).
For now are limited to **v7** only for easy test on CI and also because I can't test on
real hardware (I use/have Cortex-R boards only around)

Add few ARM DSP Intrinsics

---

coresimd/arm/dsp.rs
crates/stdsimd-test/src/lib.rs

This PR add the following DSP intrinsics:
- Quad 8-bit addition/subtraction
- Double 8-bit addition/subtraction
- Saturating Add and Subtract with Exchange and
Saturating Subtract and Add with Exchange, signed
- Select bytes based on GE bits
This patch bump the `assert_instr` limit to 22 (from 20) instead of add a lots of exception for all DSP intrinsics.

ARM DSP: add quad/double add/sub + exchange and select bytes intrinsics

---

coresimd/x86/rdtsc.rs

`cargo test --no-run` and Travis CI raise:
```
error[E0432]: unresolved import
--> crates/coresimd/src/../../../coresimd/x86/rdtsc.rs:62:9
|
62 |     use coresimd::x86::rdtsc;
|        
``` ^^^^^^^^^^^^^^^^^^^^

Fix x86 build on latest nightly

---

coresimd/arm/dsp.rs

Escape '[' and ']' used for arrays and not as Markdown syntax.

ARM DSP: fix intra_doc_link_resolution_failure

---

coresimd/arm/dsp.rs
coresimd/arm/mod.rs

First of this PR restrict everything to Cortex-A/R devices till We found a better way to manage `thumb*` targets.
Then add a set of halving parallel add/sub and multiply add/sub widely used in DSP algorithms: 
- `shsub8`: Signed halving parallel byte-wise subtraction.
- `shsub16`: Signed halving parallel halfword-wise subtraction.
- `shadd8`: Signed halving parallel byte-wise add.
- `shadd16`: Signed halving parallel halfword-wise add.
- `smuad`: Signed dual multiply add.
- `smuadx`: Signed dual multiply add reversed.
- `smusd`: Signed dual multiply subtract.
- `smusdx`: Signed dual multiply subtract reversed.

ARM DSP: Halving parallel add/sub and multiply add/sub

---

coresimd/arm/cmsis.rs
coresimd/arm/mod.rs

This should fix doc generation for the intrinsics added in #518, #529 and #532. Or, at least the docs show up for me when I invoke `cargo rustdoc -p coresimd --open -- --cfg dox`.

generate docs for Cortex-M / Cortex-R intrinsics

---

coresimd/arm/dsp.rs

Add support for `smlad` and `smlsd`.
- `smlad`: Dual 16-bit Signed Multiply with Addition and 32-bit accumulation
- `smlsd`: Dual 16-bit Signed Multiply with Subtraction and 32-bit accumulation

Dual 16-bit Signed Multiply with Addition/Subtraction

---

ci/docker/wasm32-unknown-unknown/Dockerfile
coresimd/wasm32/memory.rs
coresimd/wasm32/mod.rs
crates/coresimd/Cargo.toml
crates/stdsimd-test/Cargo.toml
examples/wasm.rs

The official name of the memory intrinsics has changed to `memory.size` and
`memory.grow`, so let's reflect that with our naming as well! Additionally they
have an argument of which memory to operate on with LLVM and must always be zero
currently.

Rename `wasm32` memory intrinsics

---

crates/coresimd/src/lib.rs

Building `coresimd` is broken on the latest nightlies, due to an unstable feature being renamed. This PR fixes that.

Fix nightly build breakage

---

.appveyor.yml
.travis.yml
ci/run.sh
coresimd/x86/sse2.rs
crates/stdsimd-test/Cargo.toml
crates/stdsimd-test/src/lib.rs
crates/stdsimd-test/src/wasm.rs

The _mm_castX_Y SSE intrinsics are "reinterpreting" casts; LLVM's
simd_cast is a "converting" cast. Replace simd_casts with mem::transmute.
Fixes rust-lang/rust#55249

fix _mm_castsi128_pd and _mm_castpd_si128 impls

---

coresimd/x86/sse2.rs

As I mentioned in the last pull request, I tried this out and found that it does emit `movq` instead of `movdqu`. I believe these epi64 series of instructions really do only touch quadwords, not double quadwords.

just load 64 bits with _mm_loadl_epi64

---

coresimd/x86/avx.rs

These APIs write through the pointer, so the pointer should be `*mut` and not `*const`.
Closes #575 .

[breaking change] fixes unsoundness in avx non-temporal store APIs. 

---

coresimd/nvptx/mod.rs

Rename the NVPTX related intrinsic `llvm.cuda.syncthreads` -> `llvm.nvvm.barrier0` to keep up with changes in LLVM.
This should provide a workaround for https://github.com/rust-lang/rust/issues/54115, although there is also an analogous NVPTX related platform-intrinsic that still references the renamed `llvm.cuda.syncthreads` intrinsic.
Thanks to @rkruppe for pointing me here from the discord.

Rename `llvm.cuda.syncthreads` -> `llvm.nvvm.barrier0`

---

crates/coresimd/Cargo.toml
crates/stdsimd/Cargo.toml

The next version to be released on crates.io will be 0.1.3 (0.1.2 is the last version released).

update authors and version

---

.travis.yml
coresimd/x86/avx.rs
coresimd/x86/avx2.rs
coresimd/x86/fma.rs
coresimd/x86/sse.rs
coresimd/x86/sse2.rs
coresimd/x86/sse41.rs
coresimd/x86_64/sse41.rs

`i686-pc-windows-gnu` is still not working on travis, but everything else should be green.

Fix windows builds & add some travis windows builds

---

coresimd/x86/cpuid.rs

This adds support for the `x86_64-fortanix-unknown-sgx` target. See https://github.com/rust-lang/rust/pull/56066 for details.
CPUID is not supported inside SGX. In the future, I might want to add a way to supply CPUID information from the outside, but that can come later.

Add SGX target

---

coresimd/aarch64/mod.rs
coresimd/arm/mod.rs
coresimd/mips/mod.rs
coresimd/nvptx/mod.rs
coresimd/powerpc/mod.rs
coresimd/wasm32/mod.rs
coresimd/wasm32/simd128.rs
coresimd/x86/mod.rs

I tested this with a local checkout of https://github.com/rust-lang/rust/
Ideally CI would update the submodule and run `cargo +nightly check` inside `src/libstd`.

Fix build when used as a submodule

---

coresimd/x86/avx.rs
coresimd/x86/cpuid.rs
coresimd/x86/sse.rs
coresimd/x86/sse2.rs
crates/coresimd/src/lib.rs

Once MaybeUninit becomes stable we should update these APIs to return MaybeUninit instead if a crater run allow us to do so.
It is trivial to introduce UB with the current APIs:
```rust
unsafe { 
let mut a = _mm_undefined_xy();
foo(&mut a); // UB: reference to uninitialized memory
}
```

Remove all usages of mem::uninitialized

---

coresimd/macros.rs
coresimd/x86/sse.rs

The regresion on i686 codegen has been fixed with the latest LLVM update, but i586 remains broken on these two intrinsics.

Update x86 codegen

---

coresimd/arm/armclang.rs

Ensure we've always got a macro defined!
Closes #603

Fix build of documentation in libstd

---

coresimd/aarch64/crc.rs
coresimd/aarch64/mod.rs

For the `crc32fast` crate: https://github.com/srijs/rust-crc32fast/pull/6

Add AArch64 CRC32 intrinsics

---

coresimd/mod.rs
coresimd/wasm32/memory.rs
coresimd/wasm32/mod.rs

This commit stabilizes the wasm32 memory-related intrinsics, as
specified in rust-lang/rust#56292. The old intrinsics were removed and
the current intrinsics were updated in place, but it's the last breaking
change!

Stabilize wasm32 memory-related intrinsics

---

crates/stdsimd/src/lib.rs
stdsimd/arch/detect/mod.rs
stdsimd/arch/detect/os/aarch64.rs
stdsimd/arch/detect/os/freebsd/aarch64.rs
stdsimd/arch/detect/os/freebsd/mod.rs

On AArch64, FreeBSD does not currently provide `HWCAP` in the ELF auxiliary vector.
Reads of the ID registers are trapped though, and they are accessible in userspace.
- The register reading code could work on other OSes and even bare metal, so it's separated out into its own module.
- Seems like it could also be used on Linux.
- ~~TODO: The OS-dependent code should trap `SIGILL` before calling the reading function, in order to work on older OS versions that didn't expose the registers.~~  I guess it's fine™ to expect that to work.
- ~~TODO: The OS-dependent code should run the reading function on all cores (via thread affinity) and take a union of features, because there are [weird SoCs where cores have unequal features](https://medium.com/@jadr2ddude/a-big-little-problem-a-tale-of-big-li …

Add support for feature detection on FreeBSD/aarch64 (WIP)

---

coresimd/x86/cpuid.rs

Being able to `println!("{:#?}", cpuid_result)` and seeing all the registers in one go is nice to have.

Derive Debug for CpuidResult

---

coresimd/x86/mod.rs

These aren't actually used anywhere yet, but this is likely a first step
in any world! Also note that these types are unstable currently.

Add definitions for AVX-512 types on x86

---

coresimd/wasm32/atomic.rs
coresimd/wasm32/mod.rs

This commit renames the atomic intrinsics for wasm and tweaks them to
match the new naming convention of the memory intrinsics. Apart from
naming the `wake` intrinsic was renamed to `atomic_notify` (reflecting
the upstream rename) as well as updating to take/return unsigned
arguments, also reflecting the upstream spec changes.

Rename the wasm atomic intrinsics

---

.appveyor.yml
coresimd/simd_llvm.rs
coresimd/x86/avx512f.rs

This commit updates stdsimd's codegen to match Clang's for the
`_mm512_abs_epi32` intrinsic (and masked versions) which doesn't use any
LLVM intrinsic calls, but rather raw SIMD operations.
These are built on top of the new `simd_select_bitmask` intrinsic
introduced recently to the compiler!

Match clang for `_mm512_abs_epi32` intrinsics

---

coresimd/aarch64/crc.rs
coresimd/aarch64/neon.rs
coresimd/arm/neon.rs
crates/stdsimd-verify/Cargo.toml
crates/stdsimd-verify/build.rs
crates/stdsimd-verify/src/lib.rs
crates/stdsimd-verify/tests/arm.rs
crates/stdsimd-verify/tests/x86-intel.rs

This commit implements automatic verification of implement ARM/AArch64
intrinsics. Or it's at least a start! This downloads a snapshot of ARM's
[online documentation][docs] and implements necessary logic to parse
that and use it to verify all the intrinsics. Almost everything
checked out A-OK but a few minor tweaks were needed to the neon
intrinsics and the crc ones needed some renaming.
[docs]: https://developer.arm.com/technologies/neon/intrinsics

Implement automatic verification for ARM/AArch64 intrinsics

---

stdsimd/arch/detect/error_macros.rs

Needed by https://github.com/rust-lang/rust/pull/56407

Add missing docs

---

coresimd/x86/avx512f.rs

Needed to make https://github.com/rust-lang/rust/pull/57045 go through

avoid deprecated mem::zeroed

---

.travis.yml
ci/cross/nvptx64-nvidia-cuda.json
ci/docker/nvptx64-nvidia-cuda-cross/Dockerfile
ci/run-docker.sh
ci/run.sh
crates/coresimd/src/lib.rs

This commit adds an nvptx64 build libcore-only test, using xargo. It involved some changes to the travis yml, as well as the CI run scripts. I use a $CROSS_TARGET env variable in the travis yml to force cross compilation on the host $TARGET.
This also disables the "integer_atomics" feature on nvptx/nvptx64. During debugging, I got a strange `unknown feature 'integer_atomics'` error (see bottom of this log: https://travis-ci.org/peterhj/stdsimd-nvptx/jobs/473037366). As the atomic int types aren't currently used w/ nvptx (although there do exist CUDA atomics on both integers and floating points, but they behave somewhat differently than the ones in sync::atomic), so I just disabled "integer_atomics" on the nvptx targets.

Add a build libcore-only nvptx64 test (using xargo)

---

coresimd/x86_64/cmpxchg16b.rs
coresimd/x86_64/mod.rs
crates/coresimd/src/lib.rs
crates/stdsimd-test/src/disassembly.rs
crates/stdsimd-verify/src/lib.rs
crates/stdsimd-verify/tests/x86-intel.rs
stdsimd/arch/detect/arch/x86.rs
stdsimd/arch/detect/os/x86.rs

This intrinsic isn't actually specified by Intel, but it's something
gated with CPUID and can otherwise be a useful thing to have when
building primitives!
There exists an `AtomicU128` type in the standard library but it's only
exposed currently (and it's unstable) when a platform fully supports
128-bit atomics. The x86_64 architecture does not support it *unless*
the `cmpxchg16b` instruction is available, and it isn't always available!
This commit is also a proposal for how we can include support for
128-bit atomics in the standard library on relevant platforms. I'm
thinking that we'll expose this one low-level intrinsic in
`std::arch::x86_64`, and then if desired a crate on crates.io can build
`AtomicU128` from this API.
In any case this is all unstable regardless!

Add a `x86_64::cmpxchg16b` intrinsic

---

coresimd/x86/rdrand.rs
coresimd/x86_64/rdrand.rs
crates/coresimd/src/lib.rs

As suggested [here]!
[here]: https://github.com/rust-lang/rust/pull/57048#issuecomment-449773525

Remove usage of `platform-intrinsics` where `unadjusted` works

---

coresimd/x86/adx.rs
coresimd/x86/mod.rs
coresimd/x86_64/adx.rs
coresimd/x86_64/mod.rs
crates/coresimd/src/lib.rs
crates/stdsimd-verify/tests/x86-intel.rs
stdsimd/arch/detect/arch/x86.rs
stdsimd/arch/detect/os/x86.rs

Add ADX-related intrinsics

---

crates/stdsimd/Cargo.toml

This fixes the broken `wasm32-unknown-unknown` build bot.

enable wasm-bindgen feature of rand dependency

---

coresimd/x86/mmx.rs

These are described in the [Intel Intrinsics Guide](https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=emms&expand=2198,2199) and offer a nicer way of working around the issues mentioned in #621 .

Add MMX _mm_empty and _m_empty intrinsics

---

README.md
ci/dox.sh
crates/core_arch/Cargo.toml
crates/core_arch/LICENSE-APACHE
crates/core_arch/LICENSE-MIT
crates/core_arch/README.md
crates/std_detect/Cargo.toml
crates/std_detect/LICENSE-APACHE
crates/std_detect/LICENSE-MIT
crates/std_detect/README.md

Updates the `core_arch` and `std_detect` versions, readme's, licenses, links, etc. for properly doing releases of these crates. 
It also add instructions about how to publish the crates. After the refactor the only "laborious" step is manually commenting the dev-dependencies due to cargo bug https://github.com/rust-lang/cargo/issues/4242 .

Prepare the crates for doing releases 

---

crates/simd-test-macro/src/lib.rs

After using MMX intrinsics the FPU must be
cleared by using `_mm_empty()` before interfacing
with any x87 code.
This commit makes the simd_test macro automatically do that
when one of the features enabled is "mmx".

Automatically insert emms after running each MMX test

---

README.md

Update travis-ci.org -> travis-ci.com

Update Travis CI urls.

---

ci/cross/nvptx64-nvidia-cuda.json

This commit adds `"merge-functions": "disabled"` and sets the correct datalayout string in the included nvptx64 target spec.

Update the included nvptx64 target spec json

---

crates/core_arch/src/x86/adx.rs
crates/core_arch/src/x86_64/adx.rs

Intended to fix https://github.com/rust-lang/rust/issues/57993. This does make the tests build for me, though a lot of them are failing. Not sure if that's normal or not.

Fix addcarry / subborrow intrinsic names

---

ci/run.sh
crates/assert-instr-macro/src/lib.rs
crates/core_arch/src/core_arch_docs.md
crates/core_arch/src/lib.rs
crates/core_arch/src/wasm32/simd128.rs
crates/core_arch/src/x86/bmi2.rs
crates/core_arch/src/x86/mod.rs
crates/core_arch/src/x86_64/bmi2.rs
crates/stdsimd-test/src/lib.rs
crates/stdsimd-test/src/wasm.rs

* Make all doctests use items from the real `std` rather than this
crate, it's just easier
* Handle debuginfo weirdness by flagging functions as `no_mangle` that
we're looking for instructions within.

Attempt to fix tests on master

---

crates/core_arch/src/x86/avx.rs
crates/core_arch/src/x86/avx512f.rs
crates/core_arch/src/x86/sse.rs
crates/core_arch/src/x86/sse2.rs

This is the stdsimd side of https://github.com/rust-lang/rust/pull/58129.
(Having stdsimd in a separate repo means that what would usually be 1 PR turns into 3...)

MaybeUninit: update to into_initialized

---

ci/dox.sh
crates/core_arch/Cargo.toml
crates/core_arch/build.rs
crates/core_arch/src/mod.rs

cc @RalfJung maybe this fixes the doc issues https://github.com/rust-lang/rust/pull/58373

Fix libcore build

---

crates/std_detect/src/detect/cache.rs
crates/std_detect/src/detect/os/freebsd/mod.rs
crates/std_detect/src/detect/os/linux/auxvec.rs
crates/std_detect/src/detect/os/x86.rs

This changes imports in `std_detect` to edition-agnostic style (This is **not** transition of `std_detect`).
This allows `libstd` to transition to Rust 2018 (https://github.com/rust-lang/rust/pull/58208).
cc https://github.com/rust-lang/rust/issues/58099

Change imports in std_detect to edition-agnostic style

---

.travis.yml

I have no idea what it was for but tests pass without it.

Remove NORUN from Travis for PPC and s390x

---

crates/core_arch/src/lib.rs
crates/core_arch/src/nvptx/mod.rs

This change introduces basic CUDA (`nvptx64-nvidia-cuda` target) syscalls.
Following up discussing and implementation from [libc#1277](https://github.com/rust-lang/libc/pull/1277).
cc @gnzlbg

NVPTX CUDA syscalls

---

crates/std_detect/src/detect/os/aarch64.rs

To comply with deny(intra_doc_link_resolution_failure)`

aarch64: escape square brackets in docs

---

crates/core_arch/src/acle/simd32.rs
crates/stdsimd-test/src/lib.rs

- add `ssub8` and `usub8`
- bump instruction limit to 29
cc @japaric

ACLE/SIMD32: add `ssub8` and `usub8`

---

crates/core_arch/src/acle/dsp.rs
crates/core_arch/src/acle/simd32.rs

Adds:
__smulbb, __smulbt, __smultb, __smultt, __smulwb, __smulwt
__qdbl, __smlabb, __smlabt, __smlatb, __smlatt, __smlawb, __smlawt
and related test-cases.
cc @Amanieu @japaric

ACLE/DSP: implement remaining intrinsics

---

.travis.yml
ci/gba.json
crates/core_arch/src/acle/registers/aarch32.rs

As per [this issue](https://github.com/rust-lang-nursery/stdsimd/issues/702), I've added the required cfg attribute. I'm just going by what @parched said, I don't know if this is the perfect minimum cfg bound myself.

WIP Fix the recent breakage of the `gba` crate

---

crates/core_arch/src/x86/sse2.rs
crates/stdsimd-verify/src/lib.rs
crates/stdsimd-verify/tests/x86-intel.rs

_mm_pause does not require SSE2

---

crates/core_arch/src/x86/avx.rs
crates/core_arch/src/x86/sse.rs
crates/core_arch/src/x86/sse2.rs

Waiting for https://github.com/rust-lang/rust/pull/59284 to land

adjust to MaybeUninit renames

---

crates/core_arch/src/x86/bt.rs
crates/core_arch/src/x86/mod.rs
crates/core_arch/src/x86_64/bt.rs
crates/core_arch/src/x86_64/mod.rs
crates/stdsimd-verify/tests/x86-intel.rs

Closes #553 
---
* ~I don't think the `assert_instr` lines are doing anything so not sure if I'm using them wrong or they just aren't applicable here.~ Ah. It does run on CI.
* I know the API differs slightly than what's prescribed in https://github.com/rust-lang-nursery/stdsimd/issues/553#issuecomment-415708627 but after looking around this feels more consistent.
* Do we want to provide non-reference versions of `bittest`? Not sure if it'd be worth it. 
* What's the policy on stuff like `debug_assert`s for checking invariants? If you test for a bit higher than the total bit size of the operand it runs right off the memory onto whatever is there at the moment.

Add bittest instructions for x86

---

.travis.yml
crates/core_arch/src/mips/msa.rs
crates/stdsimd-verify/mips-msa.h
crates/stdsimd-verify/src/lib.rs
crates/stdsimd-verify/tests/mips.rs

This PR adds automatic-verification of the MIPS MSA intrinsic type signatures
cc @rbirdic @wzssyqa

Automatic verification of MIPS MSA intrinsics

---

crates/stdsimd-verify/src/lib.rs
crates/stdsimd-verify/tests/mips.rs

Looks like MIPS is the first architecture to have verification which
exercises the more flavorful forms of `assert_instr`, so the parsing
code for `assert_instr` needed an update.
Closes #713

Fix verifying instructions for MIPS

---

crates/core_arch/src/acle/dsp.rs
crates/core_arch/src/acle/simd32.rs

rustdoc link failures accidentally got downgraded to a warning some time ago, so these could slip in. I hope I got all of them.

fix rustdoc link failures

---

crates/core_arch/src/simd_llvm.rs
crates/core_arch/src/x86/adx.rs
crates/core_arch/src/x86_64/adx.rs
crates/core_arch/src/x86_64/cmpxchg16b.rs

Probably this should wait for https://github.com/rust-lang/rust/pull/59974

Remove stage0 workarounds

---

crates/core_arch/Cargo.toml
crates/core_arch/src/aarch64/crypto.rs
crates/core_arch/src/acle/dsp.rs
crates/core_arch/src/acle/simd32.rs
crates/core_arch/src/arm/neon.rs
crates/core_arch/src/arm/table_lookup_tests.rs
crates/core_arch/src/lib.rs
crates/core_arch/src/mips/msa.rs
crates/core_arch/src/powerpc/vsx.rs
crates/core_arch/src/x86/avx.rs
crates/core_arch/src/x86/sha.rs
crates/core_arch/src/x86/sse.rs
crates/core_arch/src/x86/sse2.rs
crates/core_arch/src/x86_64/sse2.rs

This sets core_arch to the 2018 edition, meaning that rust-lang/rust cannot be updated until https://github.com/rust-lang/rust/pull/58702 is merged. cc @taiki-e

Enable edition=2018 for core_arch

---

crates/core_arch/src/x86/sse.rs
crates/stdsimd-verify/tests/x86-intel.rs

**DO NOT MERGE**
If CI passes, I'll push this as a branch, and send a PR to rust-lang/rust to schedule a crater run. Depending on how much code this change breaks, we can re-evaluate what to do with issue #522 .

[breaking change]: mask argument type of _mm_shuffle_ps

---

crates/core_arch/src/x86/rdtsc.rs

Closes #559 . 
The bug was reported to Intel (see #559), they haven't answered yet AFAICT, GCC does fix the bug, and so should we. We should do a crater run, and see if the fix is possible. Hopefully most people are just calling the intrinsic followed by `as u64` anyways to workaround this. We'll see.

[breaking change] fix return type of _rdtsc

---

crates/core_arch/src/core_arch_docs.md

Otherwise I get:
```
test src/lib.rs -  (line 114) ... ignored
test src/lib.rs -  (line 58) ... ignored
test src/lib.rs - core_arch::arch (line 114) ... ignored
test src/lib.rs - core_arch::arch (line 58) ... ignored
test src/lib.rs - core_arch::arch (line 212) ... FAILED
test src/lib.rs -  (line 212) ... FAILED
test src/lib.rs -  (line 253) ... ok
test src/lib.rs - core_arch::arch (line 253) ... ok
failures:
---- src/lib.rs - core_arch::arch (line 212) stdout ----
error: unused `#[macro_use]` import
--> src/lib.rs:215:13
|
5 | #[macro_use(is_x86_feature_detected)]
|             ^^^^^^^^^^^^^^^^^^^^^^^
|
note: lint level defined here
--> src/lib.rs:211:9
|
1 | #![deny(warnings)]
|         ^^^^^^^^
= note: #[deny(unused_imports)] implied by #[deny(warnings)]
error: aborting due to previous …
```

Avoid a doctest failure on non-x86

---

ci/docker/x86_64-unknown-linux-gnu-emulated/Dockerfile
crates/core_arch/src/lib.rs
crates/core_arch/src/simd.rs
crates/core_arch/src/x86/f16c.rs
crates/core_arch/src/x86/mod.rs
crates/core_arch/src/x86/rtm.rs
crates/core_arch/tests/cpu-detection.rs
crates/std_detect/src/detect/arch/x86.rs
crates/std_detect/src/detect/os/x86.rs
crates/std_detect/tests/cpu-detection.rs
crates/stdsimd-verify/tests/x86-intel.rs

Note: `avx512f` enables `f16c` - once https://github.com/rust-lang/rust/pull/60191 is merged and available on nightly we can switch these to only requiring the `f16c` target-feature instead.

Implement F16C intrinsics

---

crates/std_detect/src/detect/os/freebsd/arm.rs
crates/std_detect/src/detect/os/freebsd/auxvec.rs
crates/std_detect/src/detect/os/freebsd/mod.rs
crates/std_detect/src/detect/os/freebsd/powerpc.rs

std_detect is missing on these arches.

Add std_detect for FreeBSD armv6, armv7 and powerpc64

---

crates/core_arch/src/lib.rs
crates/core_arch/src/x86/avx.rs
crates/core_arch/src/x86/sse2.rs
crates/stdsimd-verify/src/lib.rs
crates/stdsimd-verify/tests/mips.rs
crates/stdsimd-verify/tests/x86-intel.rs

@alexcrichton this PR makes stdsimd-verify treat mut and const pointer and references differently. We had a breaking changes due to incorrect pointer mutability already (e.g. #576), and I hope this will prevent at least the more obvious ones as the AVX-512 intrinsics get added. 
Two breaking changes are introduced:
* #743 is fixed, which means two API breaking changes to those intrinsics
* `_mm_clflush` had an incorrect API, the pointer should have been a `const` pointer, but it was a `mut` one
I'll propose to merge something like this to stdsimd, and then do a crater run in the PR to rust-lang/rust.

[breaking change] Fix pointer validation in stdsimd-verify

---

crates/std_detect/src/detect/os/linux/powerpc.rs

The power8 feature is defined in hwcap2
It fixes https://github.com/rust-lang-nursery/stdsimd/issues/760

Fix detection of power8

---

crates/std_detect/src/detect/os/freebsd/auxvec.rs

```
error[E0432]: unresolved import `mem`
--> src/libstd/../stdsimd/crates/std_detect/src/detect/os/freebsd/auxvec.rs:45:9
|
45 |     use mem;
|         ^^^ no `mem` external crate
error: aborting due to previous error
For more information about this error, try `rustc --explain E0432`.
error: Could not compile `std`.
```
Tested by @pkubaj in https://reviews.freebsd.org/D20332

Fix build of auxvec.rs on FreeBSD/powerpc64

---

crates/std_detect/src/detect/os/x86.rs

add Hygon Dhyana CPU Vendor ID("HygonGenuine") checking to enable Hygon sse4a/TBM feature
As Hygon Dhyana originates from AMD technology and shares most of the architecture with AMD's family 17h, but with different CPU Vendor ID("HygonGenuine")/Family series number(Family 18h).
for CPUID feature bits, Hygon Dhyana(family 18h) share the same definition with AMD family 17h.
AMD CPUID specification is https://www.amd.com/system/files/TechDocs/25481.pdf.
Related Hygon kernel patch can be found on
http://lkml.kernel.org/r/5ce86123a7b9dad925ac583d88d2f921040e859b.1538583282.git.puwen@hygon.cn

add Hygon Dhyana support to enable sse4a/tbm feature

---

crates/core_arch/src/x86/sse2.rs

Pointed out in https://github.com/rust-lang/rust/issues/62454.

Fix typo in crates/core_arch/src/x86/sse2.rs

---

crates/core_arch/src/x86/sse.rs

Pointed out in https://github.com/rust-lang/rust/issues/62488

Fix typo in `core::arch::x86_64::_mm_prefetch`

---

ci/run.sh
crates/assert-instr-macro/src/lib.rs
crates/core_arch/Cargo.toml
crates/stdsimd-test/Cargo.toml
crates/stdsimd-test/src/disassembly.rs
crates/stdsimd-test/src/lib.rs
crates/stdsimd-test/src/wasm.rs

This fixes the assert_instr tests, at least on macosx. It's WIP because it will need a bit of code golf till it works everywhere else.
I have no idea what was wrong before, nor what was the code actually doing. 
What we do now is the following: dump the binary with the appropriate tool (e.g. objdump), parse the instruction dumps of the shims into a hashset of (function_name -> instructions), and then query this hashset for the shim name. 
I have no idea what was `backtrace` used for. We know the name of the shim we want to disassembly, so there is no need for us to inspect the backtrace AFAICT.

Fix assert_instr tests

---

crates/core_arch/src/arm/neon.rs

Hi,
I wanted to contribute to #148 by adding a family of ARM Neon intrinsics. I started with the `vmvn_{s,u}*` / `vmvnq_{s,u}*` family of intrinsics, which are all included in this PR, including tests.
I just found out that there are also the `vmvn_p8` and `vmvnq_p8` "poly" intrinsics which I did not yet implement. I would most likely want to add them as well before this PR should be merged. But, as this is my first contribution to the Rust standard libraries, I wanted to ask for comments/review first before continuing. So please let me know, if anything could/should be done different/better.
This has been tested locally on a Raspberry Pi 3 B+ for the armv7hf part. All new tests pass, except `assert_vmvn_s8_vmvn`. I might be suffering from some form of #565 , please see my comment over …

Add ARM Neon vmvn_*/vmvnq_* bitwise not intrinsics

---

crates/core_arch/src/mod.rs

This is required for https://github.com/rust-lang/rust/pull/62687 to land, which has to happen before https://github.com/rust-lang/rust/pull/60938 lands, which would be required for the original change to stdarch to land.

Revert PR 769

---

crates/core_arch/src/mod.rs

The same as https://github.com/rust-lang/stdarch/pull/769, needed due to the revert in b881a2d124cb0eea09d137300eb4a35829b517fb, in order to land https://github.com/rust-lang/rust/pull/60938.

Adjust #[doc(include)] paths for rustdoc change

---

crates/core_arch/src/mips/msa.rs
crates/core_arch/src/x86/avx.rs
crates/core_arch/src/x86/sse2.rs

Initiated by https://github.com/rust-lang/rust/issues/62454, this includes many formatting fixes to the intrinsic functions documentation, especially in MIPS MSA.

Fix documentation formatting of core_arch

---

crates/core_arch/src/simd_llvm.rs

Remove simd_rem intrinsic definition

---

crates/core_arch/src/mod.rs

FWIW, in the future we should try to avoid this as I'm assuming we'll break CI trying to land this here (and we can't swap bootstrap compilers in Rust until this lands).

Apply snap of bootstrap compiler in rust-lang/rust

---

crates/std_detect/src/detect/mod.rs

Should address https://github.com/rust-lang/miri/issues/932

Minimal miri support

---

crates/std_detect/src/detect/mod.rs
crates/std_detect/src/detect/os/freebsd/aarch64.rs
crates/std_detect/src/detect/os/freebsd/arm.rs
crates/std_detect/src/detect/os/freebsd/powerpc.rs
crates/std_detect/src/detect/os/linux/aarch64.rs
crates/std_detect/src/detect/os/linux/arm.rs
crates/std_detect/src/detect/os/linux/mips.rs
crates/std_detect/src/detect/os/linux/powerpc.rs
crates/std_detect/src/detect/os/other.rs
crates/std_detect/src/detect/os/x86.rs

All the os-specific code implements a `check_for` and a `detect_features`.
Move the always identical check_for in the mod.rs and use
`os::detect_features` there.

Factor out check_for

---

ci/azure-install-rust.yml
crates/core_arch/src/mips/msa.rs
crates/std_detect/src/detect/arch/aarch64.rs
crates/std_detect/src/detect/arch/arm.rs
crates/std_detect/src/detect/arch/mips.rs
crates/std_detect/src/detect/arch/mips64.rs
crates/std_detect/src/detect/arch/powerpc.rs
crates/std_detect/src/detect/arch/powerpc64.rs
crates/std_detect/src/detect/arch/x86.rs
crates/std_detect/src/detect/macros.rs
crates/std_detect/src/detect/mod.rs
crates/std_detect/src/detect/os/aarch64.rs
crates/std_detect/src/detect/os/freebsd/arm.rs
crates/std_detect/src/detect/os/freebsd/auxvec.rs
crates/std_detect/src/detect/os/freebsd/powerpc.rs
crates/std_detect/src/detect/os/linux/aarch64.rs
crates/std_detect/src/detect/os/linux/arm.rs
crates/std_detect/src/detect/os/linux/auxvec.rs
crates/std_detect/src/detect/os/linux/cpuinfo.rs
crates/std_detect/src/detect/os/linux/mips.rs
crates/std_detect/src/detect/os/linux/powerpc.rs
crates/std_detect/src/detect/os/x86.rs
crates/std_detect/tests/cpu-detection.rs
crates/stdarch-test/src/disassembly.rs
crates/stdarch-test/src/wasm.rs

This PR implements an unstable `features()` function in `std::detect` that returns an iterator over the target features, returning a tuple of the target-feature name, and whether it is enabled or disabled in the current host. 
This can be used to implement a solution to https://github.com/rust-lang/rust/issues/54688 using our own run-time feature detection system.
The refactor required to implement this also allows us to close #667

Add std_detect::detect::features() API that returns iterator of target-features and reject unstable features in feature-detection macros

---

crates/stdarch-test/src/lib.rs

`const_str_as_bytes` has been stabilized in https://github.com/rust-lang/rust/pull/63770.

Remove const_str_as_bytes feature gate

---

crates/std_detect/Cargo.toml
crates/std_detect/src/detect/cache.rs
crates/std_detect/src/detect/mod.rs
crates/std_detect/src/detect/os/freebsd/mod.rs
crates/std_detect/src/lib.rs

Modernizes usage of `cfg_if!` slightly

Remove need for `#[macro_use]` with `cfg-if`

---

crates/core_arch/rustfmt.toml
crates/core_arch/src/simd.rs

Fixes errors like https://travis-ci.com/rust-lang-nursery/packed_simd/jobs/248339096#L367

Replace rustfmt::skip custom inner attribute with rustfmt.toml

---

ci/docker/mipsel-unknown-linux-musl/Dockerfile

We recently added a CDN in front of our CI mirrors as it's faster and
cheaper for us. This switches libc's CI to use it instead of accessing
the underlying bucket directly.
r? @gnzlbg

ci: switch mirrors to use our CDN

---

crates/core_arch/src/simd_llvm.rs

Currently, these have to be special-cased in the promotion logic in `rustc`, as they predate the existence of the attribute. Add the attribute now so we can clean up the special-case later in the compiler.
I'm not sure if there are additional considerations here. Perhaps someone could fill me in if so?

Add `#[rustc_args_required_const]` to `simd_shuffle`

---

crates/std_detect/src/detect/arch/arm.rs
crates/std_detect/src/detect/os/linux/arm.rs
crates/std_detect/tests/cpu-detection.rs

Cortex-A53 etc has 32-bit mode, and it can use crc32 instruction sets even if 32-bit (A32 mode) and CPU is supported. So we should add crc32 detection for arm32.

Add CRC32 detection to arm32

---

crates/core_arch/src/arm/neon.rs

When building on aarch64, the following warning occurs.
```
warning: unused import: `mem::transmute`
--> crates/core_arch/src/arm/neon.rs:3:38
|
3 | use crate::{core_arch::simd_llvm::*, mem::transmute};
|                                      ^^^^^^^^^^^^^^
|
= note: `#[warn(unused_imports)]` on by default
```

Fix unused import: `mem::transmute`

---

crates/std_detect/src/detect/mod.rs
crates/std_detect/src/detect/os/windows/aarch64.rs

Windows has API to detect CPU features for crc32 and ARM crypto extension.

Run-time feature detection for Aarch64 on Windows.

---

.github/workflows/main.yml

According to [the document](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#jobsjob_idsteps), default shell of Windows is PowerShell. But `&&` isn't supported on PowerShell yet.
So we should use multi line run syntax instead.

Don't use `&&` on GitHub Actions.

---

crates/core_arch/src/simd_llvm.rs
crates/core_arch/src/x86/avx.rs
crates/core_arch/src/x86/avx2.rs
crates/core_arch/src/x86/bswap.rs
crates/core_arch/src/x86/fma.rs
crates/core_arch/src/x86/mmx.rs
crates/core_arch/src/x86/mod.rs
crates/core_arch/src/x86/sse.rs
crates/core_arch/src/x86/sse2.rs
crates/core_arch/src/x86/sse41.rs
crates/core_arch/src/x86_64/bswap.rs
crates/stdarch-test/src/lib.rs

I currently only did this for x86. Also I skipped `_mm_sqrt_ps` and some more, as llvm emitted `rsqrtps` combined with a lot of extra instructions instead of `sqrtps`, causing slight rounding errors and non optimal codegen.
cc #788

Use more simd_* intrinsics

---

crates/core_arch/src/simd_llvm.rs

These are needed for rustc to be able to correctly handle stability of constness of intrinsics. Without either `rustc_const_unstable` or `rustc_const_stable` an intrinsic is not const evaluable at all.
related: https://github.com/rust-lang/rust/issues/61495

Add const unstability attributes

---

crates/core_arch/src/simd_llvm.rs
crates/core_arch/src/wasm32/simd128.rs
crates/core_arch/src/x86/mod.rs
crates/std_detect/src/detect/macros.rs

Replace `issue = "0"` with `"none"`
CC: rust-lang/rust#67496

Use issue = "none" instead of "0"

---

.github/workflows/main.yml
crates/core_arch/tests/cpu-detection.rs
crates/std_detect/src/detect/arch/x86.rs
crates/std_detect/src/detect/os/x86.rs
crates/std_detect/tests/cpu-detection.rs
crates/std_detect/tests/x86-specific.rs

As documented in https://software.intel.com/sites/default/files/managed/c5/15//architecture-instruction-set-extensions-programming-reference.pdf

Add Icelake avx512 features

---

crates/std_detect/src/detect/cache.rs

If we observe that the second word is initialized, we can't really
assume that the first is initialized as well. So check each word
separately.
r? @gnzlbg 
I've found this by just looking at the code, and I didn't actually test this (`cargo test --target i686-unknown-linux-gnu` failed with some build.rs error which I haven't looked into).

Fix race condition in feature cache on 32 platforms

---

crates/core_arch/src/x86/sse41.rs

Remove unnecessary parens in `const` assigned value.
CC: [rust-lang/rust#67942](https://github.com/rust-lang/rust/issues/67942)

Remove unnecessary parens.

---

crates/std_detect/src/detect/arch/x86.rs

https://github.com/rust-lang/stdarch/pull/739 added per-feature
stabilization of runtime CPU feature detection. In so doing, it
de-stabilized some detection features that had been stable since Rust
1.27.0, breaking some published crates (on nightly). This commit
re-stabilizes the subset of AVX-512 detection features that were
included in 1.27.0 (that is, the pre-Ice-Lake subset). Other instruction
sets (MMX in particular) remain de-stabilized, pending a decision about
whether should ever stabilize them.
See https://github.com/rust-lang/rust/issues/68905.

re-stabilize the AVX-512 features that were stabilized in Rust 1.27.0

---

crates/std_detect/src/detect/arch/arm.rs
crates/std_detect/src/detect/os/linux/arm.rs
crates/std_detect/tests/cpu-detection.rs

ARM crypto extension is supported on A32 mode.

Add crypto target feature detection to arm32

---

ci/docker/wasm32-unknown-unknown/Dockerfile

See https://github.com/WebAssembly/wabt/pull/1321

Install Python3 to wasm32 CI since wabt removes Python2 support

---

crates/core_arch/src/wasm32/memory.rs
crates/core_arch/src/wasm32/simd128.rs
crates/core_arch/src/x86/sse.rs
crates/core_arch/src/x86_64/sse.rs
crates/std_detect/src/detect/cache.rs

Since it's recommended use use the integer associated constants for new code from Rust 1.43 the docs better mention them instead of the older slightly less recommended versions.
EDIT: Corresponding PR doing the same thing in most of the `rust` repo comes soon. But I thought submodules get their own PRs(?). Please enlighten me to what the procedure is.

Replace module MIN/MAX and min/max_value() with assoc consts

---

crates/core_arch/src/aarch64/crc.rs
crates/core_arch/src/arm/crc.rs
crates/core_arch/src/arm/mod.rs

CRC32 is supported on A32 and T32.

Support crc32 even if on arm32

---

crates/core_arch/src/acle/dsp.rs
crates/core_arch/src/acle/simd32.rs
crates/core_arch/src/arm/neon.rs
crates/core_arch/src/mips/msa.rs
crates/core_arch/src/powerpc/altivec.rs
crates/core_arch/src/wasm32/simd128.rs
crates/core_arch/src/x86/adx.rs
crates/core_arch/src/x86/avx2.rs
crates/core_arch/src/x86/avx512f.rs
crates/core_arch/src/x86/mmx.rs
crates/core_arch/src/x86/sse.rs
crates/core_arch/src/x86/sse2.rs
crates/core_arch/src/x86_64/adx.rs
crates/core_arch/src/x86_64/sse.rs
crates/core_arch/src/x86_64/sse2.rs
crates/std_detect/src/detect/cache.rs
examples/wasm.rs

Using the primitive type associated constants throughout stdarch
* Stop importing `std::<int/float type>` since those constants are now available on the primitive types directly.
* Search and replace all instances of `min_value()` with `MIN` and `max_value()` with `MAX`.
* Remove `std::` from all `std::<int/float type>::MIN/MAX` usage.
If reviewing seems too daunting or the usage of `min_value` and `max_value` does not seem that bad, I can remove that specific commit since it's most of the lines. The other two commits should at least stop using the std modules, which is a good step in the right direction and would entail far fewer changes.
r? @dtolnay

Use primitive type associated constants

---

crates/assert-instr-macro/src/lib.rs
crates/core_arch/src/acle/barrier/cp15.rs
crates/core_arch/src/acle/hints.rs
crates/core_arch/src/acle/registers/mod.rs
crates/core_arch/src/arm/armclang.rs
crates/core_arch/src/lib.rs
crates/core_arch/src/x86/bt.rs
crates/core_arch/src/x86/cpuid.rs
crates/core_arch/src/x86/eflags.rs
crates/core_arch/src/x86/xsave.rs
crates/core_arch/src/x86_64/bt.rs
crates/std_detect/src/detect/os/aarch64.rs
crates/std_detect/src/lib.rs

`asm!` will be deprecated soon in preparation for the new `asm!` macro, so switch to using `llvm_asm!` instead.
cc https://github.com/rust-lang/rfcs/pull/2843

Use llvm_asm! instead of asm!

---

.cirrus.yml
crates/core_arch/src/powerpc/altivec.rs
crates/core_arch/src/x86/mmx.rs
crates/core_arch/src/x86/sse2.rs
crates/std_detect/src/detect/arch/x86.rs

Follow-up on #842 since rav1e (https://github.com/xiph/rav1e/pull/2250) requires some additional AVX512 features that weren't stabilized.
cc https://github.com/rust-lang/rust/issues/71473

Stabilize all remaining x86 features for feature detection

---

crates/std_detect/src/detect/mod.rs

```
error[E0432]: unresolved import `self::arm::check_for`
--> src/libstd/../stdarch/crates/std_detect/src/detect/os/freebsd/mod.rs:11:17
|
11 |         pub use self::arm::check_for;
|                 ^^^^^^^^^^^^^^^^^^^^ no `check_for` in `std_detect::detect::os::arm`
error[E0425]: cannot find value `detect_features` in module `self::os`
--> src/libstd/../stdarch/crates/std_detect/src/detect/mod.rs:121:37
|
121 |     cache::test(x as u32, self::os::detect_features)
|                                     ^^^^^^^^^^^^^^^ not found in `self::os`
|
help: possible candidate is found in another module, you can import it into scope
|
20  | use crate::std_detect::detect::os::arm::detect_features;
```
Regressed by: https://github.com/rust-lang/stdarch/commit/9fad9649a117ecbf1a84be3953183bba36f62f23 …

Unbreak non-x86 build on FreeBSD

---

crates/core_arch/src/x86/cpuid.rs

This fixes an issue observed when using __cpuid and __cpuid_count with
Address Sanitizer enabled: the generated code uses the rbx register to
access ASAN tracking information without reloading it after cpuid,
resulting in a segfault since the rbx register is overwritten by cpuid
(https://crbug.com/1072045).
This seems like a compiler backend bug, and indeed there is a
long-standing LLVM bug report about a very similar issue:
https://bugs.llvm.org/show_bug.cgi?id=17907
To work around this issue, we can manually preserve the rbx register
contents in the inline assembly.  This is the approach taken by LLVM's
own host cpuid detection code (lib/Host/Support.cpp).  The original rbx
value is stashed in rsi, which is then swapped with rbx to restore the
original value as well as keep the output …

Manually preserve rbx across cpuid instruction

---

crates/core_arch/src/mips/mod.rs

Building the MIPS MSA module for non-`fp64` targets fails with an LLVM error. This PR blacklists PSP OS targets from MSA support in order to fix building libcore.

Fix non-fp64 libcore builds

---

crates/core_arch/src/x86/mod.rs

To be consistent with Clang:
https://github.com/llvm/llvm-project/blob/1b02db52b79e01f038775f59193a49850a34184d/clang/lib/Headers/avx512fintrin.h#L37
and to simplify literals where you want to set the top bit to 1.

Convert __mmask16 to use an unsigned type

---

crates/core_arch/src/simd.rs
crates/core_arch/src/x86/avx512f.rs
crates/core_arch/src/x86/mod.rs
crates/core_arch/src/x86_64/avx512f.rs
crates/core_arch/src/x86_64/mod.rs
crates/stdarch-verify/src/lib.rs
crates/stdarch-verify/tests/x86-intel.rs

This PR adds the 64 bit AVX512f integer comparison intrinsics along with set/set1 to make it usable.  
Issue: https://github.com/rust-lang/stdarch/issues/310

Add 64 bit integer AVX512f comparisons and the intrinsics needed to test them

---

ci/docker/aarch64-unknown-linux-gnu/Dockerfile
crates/core_arch/src/aarch64/mod.rs
crates/core_arch/src/aarch64/tme.rs
crates/simd-test-macro/src/lib.rs
crates/std_detect/src/detect/arch/aarch64.rs
crates/std_detect/src/detect/os/aarch64.rs
crates/std_detect/src/detect/os/freebsd/aarch64.rs
crates/std_detect/tests/cpu-detection.rs
crates/stdarch-verify/tests/arm.rs

This enables Aarch64 TME intrinsics and documents them. We need to enable `tme` feature at `rust-lang/rust` before merging this.

Implementation for Aarch64 TME intrinsics

---

crates/core_arch/src/aarch64/mod.rs

Amanieu mentioned that stage0 build should exclude TME for Aarch64 in here: https://github.com/rust-lang/rust/pull/72749#issuecomment-636148778
r? @Amanieu

Disable bootstrap for stage0

---

crates/core_arch/src/x86/avx512f.rs
crates/core_arch/src/x86_64/avx512f.rs

I missed these in https://github.com/rust-lang/rust/pull/72722

Add 64 bit AVX512f le and ge comparisons

---

crates/core_arch/src/mod.rs

Most wasm32 SIMD intrinsics are available behind a feature gate only after recompiling libcore with relevant `target_feature`. This is documented for [atomic_notify](https://doc.rust-lang.org/core/arch/wasm32/fn.atomic_notify.html), for example but is not documented for any of the `simd128`-gated intrinsics. Unlike the atomics, it would probably not make sense to add this comment above each function so here is my attempt at putting it somewhere visible globally to make sure it is clear that recompilation of libcore is needed.

Clarify documentation about wasm32 target_feature gates

---

crates/core_arch/src/x86/avx2.rs
crates/core_arch/src/x86/sse2.rs
crates/stdarch-verify/tests/x86-intel.rs

* Update Intel intrinsics definitions with the latest version
* Surprisingly, the only thing that changed in terms of function signatures is exactly the inconsistency I pointed out in #867.
* Update _mm256_extract_epi{8,16} to match latest definition
* Fix _mm_extract_epi16 sign extension
Fixes #867

Fix x86 extract_epi{8,16} functions

---

crates/core_arch/src/mips/msa.rs
crates/core_arch/src/x86/avx.rs

On newer nightlies, the fact that these function signatures conflicted caused warnings that failed CI. I chose to convert unsigned to signed to be consistent with the LLVM signature.
Example failure: https://github.com/rust-lang/stdarch/runs/835662285

Make function signatures consistent

---

crates/core_arch/src/x86/avx512f.rs
crates/core_arch/src/x86_64/avx512f.rs

I tried to be a bit too clever and used the wrong relationship between less than and greater than or equal, etc.

Fix or equals integer comparisons

---

crates/core_arch/src/x86/sse.rs
crates/stdarch-test/src/lib.rs

Add _mm_loadu_si64

---

crates/core_arch/src/x86/avx.rs
crates/core_arch/src/x86/avx2.rs
crates/core_arch/src/x86/sse2.rs
crates/core_arch/src/x86/sse41.rs
crates/core_arch/src/x86_64/avx.rs
crates/core_arch/src/x86_64/avx2.rs
crates/core_arch/src/x86_64/sse41.rs

Fixes https://github.com/bjorn3/rustc_codegen_cranelift/issues/669
I am not quite sure about how some intrinsics should handle `imm8` values > 255. Where there was no masking before, I have used saturating through `constify_imm8`.

Constify all x86 rustc_args_required_const intrinsics

---

crates/core_arch/src/x86/avx2.rs
crates/stdarch-verify/tests/x86-intel.rs

This commit partially reverts #868 to restore the intrinsics to their
original implementation to avoid breaking changes. This is done while
rust-lang/rust#73166 is running through crater, and should unblock
rust-lang/rust#74482.

Partially revert #868

---

crates/core_arch/src/x86/sse.rs

Hello everyone,
This pull request attempts to solve https://github.com/rust-lang/rust/issues/62490.
I have based my notes on the discussion from #522
Hope this is helpful :-)

Explain the discrepancy in the mask type for _mm_shuffle_ps

---

crates/core_arch/src/x86/avx.rs

It should be 128 bits, instead of 258 bits: https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=_mm256_permute2f128_si256

Fix typo in doc for `_mm256_permute2f128_si256`

---

.github/workflows/main.yml
crates/core_arch/src/aarch64/neon/mod.rs
crates/core_arch/src/arm/neon/mod.rs
crates/stdarch-test/src/lib.rs

I'm doing this on an arm32 device so I've already run all those tests and squared that away, but for arm64 we'll have to rely on the CI.
* The last two "add"
* "add across vector" (aka horizontal add)
* "add pairwise"

add more things that do adds

---

crates/core_arch/src/aarch64/mod.rs

This won't be needed once we bootstrap from beta 1.47.

Remove cfg(not(bootstrap))

---

crates/core_arch/src/arm/mod.rs

As I noted in #889, the `neon` target feature shouldn't be required to use NEON on ARM (it should be possible to detect it at runtime).

Remove requirement on neon feature for arm

---

crates/core_arch/src/x86/avx512f.rs
crates/core_arch/src/x86_64/avx512f.rs

This made it in because "Check Style" passes if there's no rustfmt available for a particular nightly.

Reformat avx512

---

crates/core_arch/src/x86/avx2.rs
crates/stdarch-verify/tests/x86-intel.rs

Revert "Partially revert #868 (#878)". This reverts commit 311d56cd91609c1c1c0370cbd2ece8e3048653a5.
See https://github.com/rust-lang/rust/pull/73166
Fixes #867

Re-land mm_extract_epi fix

---

crates/core_arch/src/arm/neon/mod.rs

The implementation basically matches the existing vgetq_lane_u32

 Add vgetq_lane_s32

---

crates/core_arch/src/aarch64/neon/mod.rs
crates/core_arch/src/arm/neon/mod.rs

These intrinsics are implemented differently for aarch64 and arm
in clang. i.e. aarch64 uses the llvm.aarch64.neon.fcvtzs.v4i32.v4f32
intrinsic. However, there didn't seem to be any advantage to using
that intrinsic instead of just sharing code.

Add vcvtq_u32_f32 and vcvtq_s32_f32

---

crates/std_detect/src/detect/cache.rs
crates/std_detect/src/detect/mod.rs

(Hi, sorry if this is out of the blue. Also very sorry if I left something I meant to remove in there — I tried a lot of variations, and the diff *looks* clean to me, but I could easily just have selective blindness about it. I have a few more improvements I want to make after this too, and I'm even willing to do them as part of this patch set, but I wanted to test the water after doing this much).
Currently (prior to this patch), `std_detect`'s `Cache` uses `SeqCst` orderings for all operations. It notes that it could actually use `Relaxed`, but that `SeqCst` is safer. When testing the feature, it performs the following pattern of loads/stores:
- `load(SeqCst)` to test for initialization.
- if uninitialized, init and `store(SeqCst)`
- `load(SeqCst)` again to test for the feature.
This …

Optimize std_detect's caching

---

crates/core_arch/src/aarch64/mod.rs
crates/core_arch/src/aarch64/prefetch.rs
crates/core_arch/src/lib.rs
crates/stdarch-verify/tests/arm.rs

Co-authored-by: Wang Maozhang <wangmaozhang@huawei.com>
This implements prefetch hints for aarch64 via LLVMs `prefetch` instrinsic.
We wintness ~20% performance gain in seal_pre_commit_phase1 of Filecoin with 32GB data input.
Verified with `cargo +nightly test` and `cargo +nightly test --release`.
There are four failures (as shown below), but these are not cause by this PR.
These tests failed both with and without this PR.
```
---- core_arch::aarch64::tme::assert___tcommit_tcommit stdout ----
disassembly for stdarch_test_shim___tcommit_tcommit:
0: adrp x8, 16f000 <_GLOBAL_OFFSET_TABLE_+0x280>
1: ldr x8, [x8, #3792]
2: adrp x9, f1000 <anon.1626de38755f4729e9f2a08512645c0a.14.llvm.15569108828795629504+0x10b87>
3: add x9, x9, #0xd29
4: str x9, [x8]
5: msr s0_3_c3_c0_3, xzr
6: ret
thread …
```

Implement prefetch hints for aarch64

---

crates/core_arch/src/lib.rs

This remove redundant feature declaration const_fn_transmute in lib.rs.
Seems caused by PR 917 and PR 918 megerd recently.
Feature `const_fn_transmute` are declared twice on line 9 and line 41 in `lib.rs`.
Thanks.

remove redundant feature declaration const_fn_transmute in lib.rs

---

crates/core_arch/Cargo.toml
crates/core_arch/src/arm/mod.rs
crates/core_arch/src/core_arch_docs.md
crates/core_arch/src/mod.rs
crates/core_arch/src/wasm32/atomic.rs
crates/core_arch/src/wasm32/mod.rs

`dox` has to be set explicitly, but `doc` is set whenever rustdoc runs.
This simplifies the doc process to `cargo doc` and means bootstrap can
stop passing `--cfg dox` when documenting crates (https://github.com/rust-lang/rust/pull/77347).

Replace `cfg(dox)` with `cfg(doc)`

---

crates/core_arch/src/core_arch_docs.md

This was changed from `cfg(dox)` to `cfg(doc)` in
https://github.com/rust-lang/stdarch/pull/920. `cfg(doc)` is incorrect here; rustdoc sets `cfg(doctest)`, not `cfg(doc)` in doc-tests.
However, this piece of code isn't needed anyway: this code will only
ever be run as a doc-test, so it will never be compiled in.
Part of https://github.com/rust-lang/rust/pull/77347.
r? @Amanieu

Remove `cfg(not(doc))` from doctests

---

crates/core_arch/src/lib.rs
crates/core_arch/src/x86/test.rs

Turns out the `untagged_unions` feature already was not needed.
Fixes https://github.com/rust-lang/stdarch/issues/924

replace some unions by transmute and make the rest repr(C)

---

crates/core_arch/src/aarch64/mod.rs
crates/core_arch/src/arm/crypto.rs
crates/core_arch/src/arm/mod.rs

ARM Crypto Extensions supports on aarch32 too. So we should allow this intrinsics on arm.

Support ARM crypto extension on A32/T32

---

.github/workflows/main.yml
ci/run.sh
crates/core_arch/src/x86/sse.rs
crates/core_arch/src/x86/sse2.rs
crates/stdarch-test/src/disassembly.rs

As long as comment, `cargo test --release` isn't passed on i686-pc-windows-msvc. This PR passes all tests.

Run CI for i686-pc-windows-msvc

---

CONTRIBUTING.md

When I tried to execute the instructions in CONTRIBUTING.MD I noticed that they actually don't work out of the box.
First, apparently the `coresimd` package had been renamed at some point but the contributing.md was not updated, I fixed that.
Additionally apparently since this documentation was written there was an update on how tests are invoked now requiring specific environment variables. I have added text to explain which those are and what they need to say to make `cargo` and `rustc` happy.

Updated CONTRIBUTING.MD for new package name and environment variables

---

crates/core_arch/src/arm/neon/mod.rs

Hey, I haven't contributed to this repo before, so I'm not 100% sure that this is the right approach. I've tried to follow the example of other Arm intrinsics that have already been added.
This PR adds the [six variants of the popcount Neon intrinsics](https://developer.arm.com/architectures/instruction-sets/simd-isas/neon/intrinsics?search=vcnt).

Add popcount Arm intrinsics.

---

crates/core_arch/src/x86/avx.rs
crates/core_arch/src/x86/avx2.rs
crates/core_arch/src/x86/avx512f.rs

The x86 code contains several macros that following this pattern:
```rust
macro_rules! expr {
() => { true; }
}
fn bar(_val: bool) {}
fn main() {
bar(expr!());
}
```
Here, we have a macro `expr!` that expands to tokens sequence with
a trailing semicolon.
Currently, the trailing semicolon is ignored when the macro is invoked
in expression position, due to https://github.com/rust-lang/rust/issues/33953
If this behavior is changed, then a large number of macro invocations in
`stdarch` will stop compiling.
Regardless of whether nor not this change is made, removing the
semicolon more clearly expresses the intent of the code - these macros
are designed to expand to the result of a function call, not ignore its
results (as the `;` would suggest).

Remove trailing semicolons from several macro definitions

---

crates/assert-instr-macro/src/lib.rs
crates/stdarch-test/src/lib.rs

The [`black_box` implementation](https://github.com/rust-lang/rust/blob/56293097f7f877f1350a6cd00f79d03132f16515/library/core/src/hint.rs#L126) is the same as what we have in this crate.
This PR unblocks #904, see https://github.com/rust-lang/stdarch/issues/904#issuecomment-721433828
Signed-off-by: Joe Richey <joerichey@google.com>

Use black_box instead of llvm_asm

---

.github/workflows/main.yml

Fix CI warning that `set-env` and `set-path` command are deprecated [*].
* https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#environment-files

Replace set-env/set-path with GITHUB_ENV/GITHUB_PATH.

---

crates/stdarch-test/src/disassembly.rs

Actually, we don't consider thumbv7neon for `stdarch-test`. Actually disassemble doesn't work on thumb/thumb2 now.
`objdump` has `--no-show-raw-insn` argument not to show raw instruction data. We should use it to make disassemble parser simple.

Use --no-show-raw-insn to make disassemble parser simple.

---

crates/core_arch/src/aarch64/neon/mod.rs
crates/core_arch/src/arm/neon/mod.rs
crates/stdarch-gen/neon.spec

This PR adds the following groups of addition Arm intrinsics (72 in total):
* `vaddl_high_[s/u][8/16/32]` - Signed/Unsigned Add Long (vector, high half)
* `vaddw_[s/u][8/16/32]` - Signed/Unsigned Add Wide
* `vaddw_high_[s/u][8/16/32]` - Signed/Unsigned Add Wide (high half)
* `vuqadd[q]_s[8/16/32/64]` - Signed saturating Accumulate of Unsigned value - Aarch64 only
* `vsqadd[q]_u[8/16/32/64]` - Unsigned saturating Accumulate of Signed value - Aarch64 only
* `vaddhn_[s/u][16/32/64]` - Add returning High Narrow
* `vaddhn_high_[s/u][16/32/64]` - Add returning High Narrow (high half)
* `vraddhn_[s/u][16/32/64]` - Rounding Add returning High Narrow
* `vraddhn_high_[s/u][16/32/64]` - Rounding Add returning High Narrow (high half)
* `vpaddl[q]_s[8/16/32]` - Signed Add Long Pairwise
* …

Add more addition Arm intrinsics

---

crates/core_arch/src/arm/neon/mod.rs

Add reversing vector elements [*] for A32 and A64.
* https://developer.arm.com/documentation/dui0472/m/using-neon-support/neon-intrinsics-for-reversing-vector-elements--swap-endianness-

Add vrev* instructions.

---

crates/core_arch/src/x86/avx512vaes.rs
crates/core_arch/src/x86/mod.rs

This adds support for the x86-64 VAES (vectorized AES) intrinsics.
It adds in both the full-width and the VL'ed 256-bit versions
and ensures via tests that they match the same test vectors as the AES-NI
versions and that they match (though sadly w/o quickcheck validation for now)
The test vectors used are the same as in [aes.rs](https://github.com/rust-lang/stdarch/blob/master/crates/core_arch/src/x86/aes.rs).
The folder was chosen to match that of the AVX512F (+-IFMA) implementation.
The name is chosen because of [how it is detected in Rust](https://github.com/rust-lang/stdarch/blob/master/crates/std_detect/src/detect/arch/x86.rs#L154).
This PR requires rust-lang/rust#78361 to be applied to the compiler for the compiler to accept the `avx512vaes` feature.
I have marked this PR as a draft …

Add VAES intrinsics

---

crates/core_arch/src/x86/xsave.rs

`_xgetbv` was reimplemented to use inline assembly in #333 since LLVM 3.9 didn't export the intrinsic we needed to use.  LLVM 4.0 has since rectified that issue, and since rust's minimum supported version of LLVM is 8.0, this change can be reverted.

Reimplement `_xgetbv` with LLVM intrinsics

---

crates/core_arch/src/x86/avx512vpclmulqdq.rs
crates/core_arch/src/x86/mod.rs

This adds support for the two intrinsics covered by VPCLMULQDQ
and extends the tests from PCLMULQDQ as well as compares the results of these two
when the inputs on the lanes are different
Like #942 this depends on rust-lang/rust#78361 to work (though depending on `avx512pclmulqdq`) and was tested with that patch applied.
The test vectors are the same as [pclmulqdq.rs](https://github.com/rust-lang/stdarch/blob/master/crates/core_arch/src/x86/pclmulqdq.rs).
The folder is chosen to match AVX512F / -IFMA.
The name is chosen as [detected in Rust](https://github.com/rust-lang/stdarch/blob/master/crates/std_detect/src/detect/arch/x86.rs#L156).
I have marked this PR as a draft until the required compiler change landed in nightly.

Add VPCLMULQDQ Intrinsics

---

crates/core_arch/src/x86/avx512vpopcntdq.rs
crates/core_arch/src/x86/mod.rs

Adds all 18 intrinsics belongin to AVX512VPOPCNTDQ counting the number of set bits in packed 32 / 64 bit integers.
Intrinsics match `_mm(256|512)?(_maskz?)?_popcnt_epi(32|64)`.
Versions for packed 8 and 16 bit integers are part of BITALG.
This is part of my current quest to add support for all Ice Lake introduced intrinsics to Rust (the extensions are VPOPCNTDQ, BITALG, VAES, VPCLMULQDQ, GFNI, and VBMI2)

Add AVX512VPOPCNTDQ Intrinsics

---

crates/core_arch/src/x86/avx512gfni.rs
crates/core_arch/src/x86/mod.rs

This adds support for all 27 GFNI Intrinsics.
Location and style orient themselves around the style used for VAES.
Invocation of the actual LLVM intrinsics orientates itself along the same line as similar cases in AVX512F.
It might be preferable for #960 to land before this PR to ensure that I didn't oversee anything WRT the mask types (which I needed for all three vector lengths for 8-bit values).

Add GFNI Intrinsics

---

crates/core_arch/src/x86/avx512bitalg.rs
crates/core_arch/src/x86/mod.rs
crates/stdarch-verify/tests/x86-intel.rs

This adds the AVX512BITALG intrinsics.
It also patches the verification against the Intel Intrinsic Guide
because Rust uses a different naming.
Added intrinsics match _mm(256|512)?(_maskz?)?_popcnt_epi(8|16) for the popcount ones
and _mm(256|512)?(_mask)?_bitshuffle_epi64_mask
This is the second-to-last set of intrinsics that were added in Ice Lake that are still missing (the other one being VBMI2).

Add AVX512BITALG

---

crates/core_arch/src/x86/avx.rs
crates/core_arch/src/x86/avx2.rs
crates/core_arch/src/x86/avx512f.rs

* Use constify_imm3 instead of a bitmask in _mm256_insert_epi32; fixes #967.
* Use constify_imm8_gather in gather intrinsics; fixes #968.

Avoid calling intrinsics with invalid const arguments

---

crates/core_arch/src/x86/mod.rs

The recently added modules use target features that are not yet
available in rustc compiler used for bootstrapping.
Guard them with `#[cfg(not(bootstrap))]`.

Use a bootstrap guard for modules with new target features

---

crates/core_arch/src/x86/avx.rs
crates/core_arch/src/x86/avx512bw.rs
crates/core_arch/src/x86/avx512f.rs
crates/core_arch/src/x86/avx512gfni.rs

This reduces the rlib size by ~9.8 MB.

Move code out of constify macros

---

crates/std_detect/src/detect/arch/x86.rs

I saw in https://github.com/rust-lang/rust/issues/81037
that when you document private items with rustdoc the
`x86 AVX-512 BITALG` feature comment does not contain
escape characters in the message and therefore rustdoc
was emitting warnings.
Therefore this PR adds them so that the warnings do not appear
anymore.

Fix false rustdoc broken_intra_link detection

---

crates/core_arch/src/x86/avx2.rs

The old documentation seemed to suggest that the low 4 bits of bytes in `b` would index into the 32-element array `a`. That's not quite right and you'd need 5 bits to index 32 elements.

Clarify _mm256_shuffle_epi8 documentation

---

crates/core_arch/src/x86/sse.rs

The value should be loaded into the lowest 64 bits, not the highest.

fix _mm_loadu_si64

---

crates/core_arch/src/lib.rs
crates/core_arch/src/x86/cpuid.rs

`cpuid` is a serializing instruction, and is the only serializing instruction available as an intrinsic AFAIK. Various points of intels documentation suggests to use it as a way to fence other instructions — The typical case is in conjunction with rdtsc/rdtscp for measurement (though on sse2 processors you can also use `mfence`/`lfence` for this purpose), although this is not the only use case.
Without the "volatile" clobber, this intrinsic can't easily be used this way, since you have to fake the use of the result or LLVM will entirely remove it. This fails to reflect the behavior documentated for instruction, so it seems like a clear-cut bug worth fixing to me.
See these for further info if desired:
- https://www.intel.com/content/dam/www/public/us/en/documents/manuals/64-ia-32-architect …

Add 'volatile' to cpuid inline asm

---

.github/workflows/main.yml
ci/docker/wasm32-wasi/Dockerfile
crates/core_arch/src/x86/avx512bf16.rs

If wasmtime does not support the latest WASM SIMD features, then we should switch to wasmer.

Enable WASM CI

---

crates/core_arch/src/lib.rs

use min_const_generics to avoid incomplete_features

---

crates/core_arch/src/x86/avx512bf16.rs
crates/std_detect/src/detect/cache.rs
crates/std_detect/src/detect/mod.rs
crates/std_detect/src/detect/os/freebsd/auxvec.rs
crates/std_detect/src/detect/os/freebsd/mod.rs
crates/std_detect/src/detect/os/linux/aarch64.rs
crates/std_detect/src/detect/os/linux/arm.rs
crates/std_detect/src/detect/os/linux/auxvec.rs
crates/std_detect/src/detect/os/linux/cpuinfo.rs
crates/std_detect/src/detect/os/linux/mod.rs
crates/std_detect/src/detect/os/linux/powerpc.rs
crates/std_detect/src/detect/os/x86.rs
crates/std_detect/src/lib.rs
crates/std_detect/src/mod.rs

The goal of this PR is to turn `std_detect` into a proper `no_std` crate so that we can avoid dealing with the mess of including it as a submodule of `std`.

Turn std_detect into a no_std crate

---

crates/core_arch/src/lib.rs
crates/core_arch/src/mod.rs

I plan to deprecate `doc(include)` in the near future, and rust-lang/rust denies warnings in CI.
cc https://github.com/rust-lang/rust/issues/78835#issuecomment-742531894, https://github.com/rust-lang/rust/issues/44732#issuecomment-742754659

Switch from `doc(include)` to `doc = include_str!`

---

crates/core_arch/src/arm/neon/mod.rs

When I tested on my aarch64, I found that some of the vadd test cases would panic due to the overflow of x+y. Use wrapping_add (discard the overflow part) to avoid them. This will be consistent with the behavior of the instruction itself.

Fix integer overflow in vadd aarch64 test cases

---

crates/assert-instr-macro/src/lib.rs
crates/core_arch/src/lib.rs
crates/core_arch/src/x86/avx512f.rs
crates/core_arch/src/x86/sse.rs
crates/stdarch-verify/src/lib.rs

This PR builds on top https://github.com/rust-lang/rust/pull/82447 to start transition intrinsics to use const generics. This is the first step towards solving #248.
- Updated the testing infrastructure to support const generics.
- Updated the intrinsic verification to support const generics.
- Ported `_mm_shuffle_ps` and `_mm_prefetch` to use const generics.

Initial conversion to const generics

---

crates/core_arch/src/macros.rs
crates/core_arch/src/x86/sse.rs

This builds on top of #1018 and prevents invalid constants from reaching LLVM and triggering assertions. 
Thanks @lcnr and @RalfJung for helping me find a construct that works with const generics!

Use static assertions to bound-check const generics

---

crates/core_arch/src/macros.rs
crates/core_arch/src/x86/avx512bw.rs
crates/core_arch/src/x86/avx512f.rs
crates/core_arch/src/x86/sse.rs
crates/core_arch/src/x86/sse2.rs

This PR switches:
- `_mm_shuffle_epi32`
- `_mm_shufflehi_epi16`
- `_mm_shufflelo_epi16`
- `_mm_srai_epi16`
- `_mm_srai_epi32`
to const generics using `#[rustc_legacy_const_generics]`

Convert some SSE2 intrinsics to const generics

---

crates/core_arch/src/x86/avx512bw.rs
crates/core_arch/src/x86/avx512f.rs
crates/core_arch/src/x86/sse2.rs

* `_mm_slli_epi64`
* `_mm_slli_epi32`
* `_mm_slli_epi16`
* `_mm_srli_epi64`
* `_mm_srli_epi32`
* `_mm_srli_epi16`

Convert _mm_slli_epi{16,32,64} & _mm_srli_epi{16,32,64} to const generics

---

crates/core_arch/src/x86/sse42.rs
crates/stdarch-verify/src/lib.rs

This PR converts the SSE 4.2 intrinsics :
- `_mm_cmpestra`
- `_mm_cmpestro`
- `_mm_cmpestrs`
- `_mm_cmpestrc`
- `_mm_cmpestrz`
- `_mm_cmpestri`
- `_mm_cmpestrm`
- `_mm_cmpistra`
- `_mm_cmpistro`
- `_mm_cmpistrs`
- `_mm_cmpistrc`
- `_mm_cmpistrz`
- `_mm_cmpistri`
- `_mm_cmpistrm`
to `rustc_legacy_const_generics`
Of note, these intrinsics use "const int" parameters, and I _believe_ the intrinsic verification is currently incomplete here: the first commit ensures the verifier also checks this new list of required consts. I'm unfamiliar with the verifier, so I may be missing something here.

Convert SSE 4.2 intrinsics to const generics

---

crates/core_arch/src/macros.rs
crates/core_arch/src/x86/avx2.rs
crates/core_arch/src/x86/sse41.rs

This PR updates the x86 SSE 4.1 intrinsics to use const generics.
Of note, some of these made an effort to test the masking/clamping of the constify immediates macros, testing with both in-range and out-of-range values in:
- `_mm_extract_ps`: [_mm_extract_ps(a, 5)](https://github.com/rust-lang/stdarch/blob/dab4581ced4f0dc82ef9ec67b4da19da707d88fb/crates/core_arch/src/x86/sse41.rs#L1301) on a 2-bit immediate
- `_mm_extract_epi8`: [_mm_extract_epi8(a, 19)](https://github.com/rust-lang/stdarch/blob/dab4581ced4f0dc82ef9ec67b4da19da707d88fb/crates/core_arch/src/x86/sse41.rs#L1313) on a 4-bit immediate
- `_mm_extract_epi32`: [_mm_extract_epi32(a, 5)](https://github.com/rust-lang/stdarch/blob/dab4581ced4f0dc82ef9ec67b4da19da707d88fb/crates/core_arch/src/x86/sse41.rs#L1323) on a 2-bit immediate
- …

Convert `x86/sse41.rs` intrinsics to const generics

---

crates/core_arch/src/aarch64/neon/mod.rs
crates/core_arch/src/arm/neon/mod.rs
crates/core_arch/src/arm/neon/shift_and_insert_tests.rs

Use generic const in the following methods:
vsli_n_*
vsliq_n_*
Fixes #1017

Convert vsli_n_* neon methods to const generics

---

crates/core_arch/src/aarch64/neon/mod.rs
crates/core_arch/src/arm/neon/mod.rs
crates/core_arch/src/arm/neon/shift_and_insert_tests.rs

Use generic const in the following methods:
vsri_n_*
vsriq_n_*

Convert vsri_n_* methods to const generics

---

crates/core_arch/src/lib.rs
crates/core_arch/src/macros.rs
crates/core_arch/src/x86/avx2.rs
crates/core_arch/src/x86/sse.rs
crates/core_arch/src/x86/sse2.rs
crates/core_arch/src/x86/sse41.rs
crates/core_arch/src/x86/sse42.rs

Originally I wanted to allow lowercase parameter names so that I could do automated bulk conversion, but it turns out this is impractical. Using uppercase is also clearer since it gives a better indication that some parameters are constants.

Use uppercase for const generic parameters

---

crates/core_arch/src/arm/neon/mod.rs
crates/core_arch/src/macros.rs

Use generic const in the following methods:
vld1_lane_*
vld1q_lane_*
vget_lane_*
vgetq_lane_*
vshrq_n_*
vshlq_n_*
vextq_*

Convert vld1_lane_* and other methods to const generics

---

crates/core_arch/src/macros.rs
crates/core_arch/src/x86/avx.rs
crates/core_arch/src/x86/avx512f.rs
crates/core_arch/src/x86/macros.rs
crates/core_arch/src/x86/sse2.rs
crates/core_arch/src/x86_64/avx512f.rs

shuffle_ps,pd
roundscale_ps,pd
fixupimm_ps,pd
ternarylogic_epi32,epi64

Convert shuffle_ps and shuffle_pd to const generics

---

crates/core_arch/src/arm/neon/mod.rs

My first attempt to add neon instructions.
Both vbic and vorn are simple bitwise instructions, whose implementation in Clang is composed of other simd instructions. And they cannot be automatically generated using stdarch-gen.

add vbic and vorn neon instructions

---

crates/core_arch/src/x86/avx512f.rs
crates/core_arch/src/x86/macros.rs
crates/core_arch/src/x86_64/avx512f.rs

sub_round_ps,pd; mul_round_ps,pd; div_round_ps,pd
sqrt_round_ps,pd;
fmadd_round_ps,pd; fmsub_round_ps,pd; 
fnmadd_round_ps,pd; fnmsub_round_ps,pd;
fmaddsub_round_ps,pd; fmsubadd_round_ps,pd
max_round_ps,pd; min_round_ps,pd; getexp_round_ps,pd
saclef_round_ps,pd

some avx512 to const generics

---

crates/core_arch/src/x86/avx.rs
crates/core_arch/src/x86/avx2.rs
crates/core_arch/src/x86/macros.rs
crates/core_arch/src/x86/sse2.rs

This PR converts these trivial x86 intrinsics to const generics.
- `_mm_extract_epi16`
- `_mm_insert_epi16`
- `_mm256_round_pd`
- `_mm256_round_ps`
- `_mm256_dp_ps`
- `_mm256_permute2f128_ps`
- `_mm256_permute2f128_pd`
- `_mm256_permute2f128_si256`
- `_mm256_insert_epi16`
- `_mm256_insert_epi32`
- `_mm256_mpsadbw_epu8`
- `_mm256_permute2x128_si256`
- `_mm256_extract_epi16`
- `_mm256_extract_epi32`
I limited to these at first, as the other intrinsics I've done require different static assertions and `ValidateConstImm` changes that are being done in other open PRs (the MIPS ones). I wouldn't want to create conflicts and bitrot these other WIP PRs.

More trivial x86 intrinsics conversions to const generics

---

.github/workflows/main.yml
crates/core_arch/src/x86/avx512bw.rs
crates/core_arch/src/x86/macros.rs
crates/core_arch/src/x86/rtm.rs

This PR converts the following intrinsics to use const generics:
- `_mm_aeskeygenassist_si128`
- `_mm_extract_epi64`
- `_mm_insert_epi64`
- `_mm256_extract_epi64`
- `_mm_sha1rnds4_epu32`
- `_mm_clmulepi64_si128`
- `_mm512_cmp_epu16_mask`
- `_mm512_mask_cmp_epu16_mask`
- `_mm256_cmp_epu16_mask`
- `_mm256_mask_cmp_epu16_mask`
- `_mm_cmp_epu16_mask`
- `_mm_mask_cmp_epu16_mask`
- `_mm512_cmp_epu8_mask`
- `_mm512_mask_cmp_epu8_mask`
- `_mm256_cmp_epu8_mask`
- `_mm256_mask_cmp_epu8_mask`
- `_mm_cmp_epu8_mask`
- `_mm_mask_cmp_epu8_mask`
- `_mm512_cmp_epi16_mask`
- `_mm512_mask_cmp_epi16_mask`
- `_mm256_cmp_epi16_mask`
- `_mm256_mask_cmp_epi16_mask`
- `_mm_cmp_epi16_mask`
- `_mm_mask_cmp_epi16_mask`
- `_mm512_cmp_epi8_mask`
- `_mm512_mask_cmp_epi8_mask`
- `_mm256_cmp_epi8_mask`
- …

More x86 const generics conversions

---

crates/core_arch/src/mips/msa.rs
crates/core_arch/src/mips/msa/macros.rs

I intended to work on mips in many small PRs for easier reviewing.
cc #1022

1/3 mips: Convert rustc_args_required_const(0) functions to const generics

---

crates/core_arch/src/x86/avx2.rs
crates/core_arch/src/x86/avx512bw.rs
crates/core_arch/src/x86/avx512gfni.rs
crates/core_arch/src/x86/avx512vaes.rs
crates/core_arch/src/x86/avx512vpclmulqdq.rs
crates/core_arch/src/x86/macros.rs

This PR updates the following "x86/avx2.rs" intrinsics to const generics:
- `_mm_i32gather_epi32`
- `_mm_mask_i32gather_epi32`
- `_mm256_i32gather_epi32`
- `_mm256_mask_i32gather_epi32`
- `_mm_i32gather_ps`
- `_mm_mask_i32gather_ps`
- `_mm256_i32gather_ps`
- `_mm256_mask_i32gather_ps`
- `_mm_i32gather_epi64`
- `_mm_mask_i32gather_epi64`
- `_mm256_i32gather_epi64`
- `_mm256_mask_i32gather_epi64`
- `_mm_i32gather_pd`
- `_mm_mask_i32gather_pd`
- `_mm256_i32gather_pd`
- `_mm256_mask_i32gather_pd`
- `_mm_i64gather_epi32`
- `_mm_mask_i64gather_epi32`
- `_mm256_i64gather_epi32`
- `_mm256_mask_i64gather_epi32`
- `_mm_i64gather_ps`
- `_mm_mask_i64gather_ps`
- `_mm256_i64gather_ps`
- `_mm256_mask_i64gather_ps`
- `_mm_i64gather_epi64`
- `_mm_mask_i64gather_epi64`
- `_mm256_i64gather_epi64`
- …

More AVX2 conversions to const generics

---

crates/core_arch/src/aarch64/neon/generated.rs
crates/core_arch/src/arm/neon/generated.rs
crates/core_arch/src/arm/neon/mod.rs
crates/stdarch-gen/neon.spec

support instructions : vabd  vaba
vabd*  instructions are generated by stdarch-gen
vaba*  instructions are added in neon/mod.rs

support instructions : vabd  vaba

---

crates/core_arch/src/x86/avx512f.rs
crates/core_arch/src/x86/macros.rs
crates/core_arch/src/x86/test.rs
crates/core_arch/src/x86_64/avx512f.rs

This PR converts some more trivial avx512f intrinsics to const generics.
There's now only around 50 `rustc_args_required` x86 intrinsics left (and around 20 in other targets). Locally libcore_arch.rlib is now around 20MB. We all managed to divide its size by 3 since last week 🎉

More avx512f conversions to const generics

---

crates/core_arch/src/aarch64/neon/generated.rs
crates/core_arch/src/arm/neon/generated.rs
crates/stdarch-gen/neon.spec
crates/stdarch-gen/src/main.rs

This pr dose the following:
1. Modify the automatic generation program of neon instructions so that it can generate neon instructions which are composed of multiple functions. 
2. Add vtst instructions to test 1.

Modify stdarch-gen to generate instructions composed of multiple functions and add vtst instructions

---

crates/core_arch/src/aarch64/neon/mod.rs
crates/core_arch/src/arm/neon/mod.rs

add neon instruction vbsl
vbsl:   Bitwise Select. This instruction sets each bit in the destination SIMD&FP register to the corresponding bit from the first source SIMD&FP register when the original destination bit was 1, otherwise from the second source SIMD&FP register.

add neon instruction vbsl

---

crates/core_arch/src/aarch64/neon/mod.rs
crates/core_arch/src/arm/neon/mod.rs

add neon instruction vbslq(128-bit)
vbslq: Bitwise Select. This instruction sets each bit in the destination SIMD&FP register to the corresponding bit from the first source SIMD&FP register when the original destination bit was 1, otherwise from the second source SIMD&FP register.

Add neon instruction vbslq

---

crates/core_arch/src/x86/avx512f.rs
crates/core_arch/src/x86/avx512vaes.rs
crates/core_arch/src/x86/avx512vpclmulqdq.rs
crates/core_arch/src/x86_64/avx512f.rs

This PR converts the following intrinsics to const generics:
x86/avx512f.rs: 
- `_mm512_extracti64x4_epi64`
- `_mm512_extracti32x4_epi32`
- `_mm256_extracti32x4_epi32`
x86/avx512vpclmulqdq.rs:
- `_mm512_clmulepi64_epi128`
- `_mm256_clmulepi64_epi128`
Which I believe, with #1067, should complete the x86 ones

Convert the last avx512f and avx512vpclmulqdq intrinsics

---

crates/core_arch/src/aarch64/neon/generated.rs
crates/stdarch-gen/neon.spec
crates/stdarch-gen/src/main.rs

All are automatically generated single-parameter comparison instructions. In order to be consistent with the implementation in Clang, some changes have been made to stdarch-gen.

add vcgez, vcgtz, vclez, vcltz neon instructions

---

crates/core_arch/src/aarch64/neon/mod.rs
crates/core_arch/src/arm/neon/mod.rs

add neon instruction   vdup_n_*    vdupq_n_*
vdup_n: Duplicate vector element to vector or scalar. This instruction duplicates the vector element at the specified element index in the source SIMD&FP register into a scalar or each element in a vector, and writes the result to the destination SIMD&FP register.

Add neon instruction vdup

---

.github/workflows/main.yml
ci/docker/wasm32-wasi/Dockerfile
ci/run.sh
crates/core_arch/build.rs
crates/core_arch/src/wasm32/atomic.rs
crates/core_arch/src/wasm32/simd128.rs
crates/stdarch-test/Cargo.toml
examples/hex.rs

This commit syncs the atomics/simd intrinsics used on WebAssembly with
LLVM 12 and the current specifications. LLVM 12 uses new names for
atomic intrinsics and the SIMD specification has added a lot of
intrinsics and renamed a few as well.
I was hoping to hold off on this until more of SIMD had landed since
there are some opcode renumberings that have happened at the spec level
but haven't happened in LLVM. Additionally there's a small handful of
instructions that have yet to be implemented in LLVM. This means that
many tests for the simd128 feature are ignored right now and/or are
known to not pass. The breakage in the name of the atomic intrinsics,
however, has prompted me to want to update this and land ahead of time.
For now I've disabled the SIMD testing and I'll get back to it once …

Update WebAssembly SIMD/Atomics

---

crates/core_arch/src/aarch64/neon/generated.rs
crates/stdarch-gen/neon.spec

I'm not sure if that's all there is to do. Seemed like an odd omission in the first place. Maybe I'm missing something?

Add vdiv neon instructions

---

crates/core_arch/src/aarch64/neon/generated.rs
crates/core_arch/src/arm/neon/generated.rs
crates/core_arch/src/arm/neon/mod.rs
crates/stdarch-gen/neon.spec
crates/stdarch-gen/src/main.rs

This adds instructions for sqrt and some of the missing reciprocal square-root estimate instructions.

Add sqrt and more rsqrte neon instructions

---

crates/core_arch/src/aarch64/neon/generated.rs
crates/core_arch/src/arm/neon/generated.rs
crates/stdarch-gen/neon.spec

This adds the vector instructions for calculating the lane-wise reciprocal estimate.

Add vrecpe neon instruction

---

crates/std_detect/src/detect/macros.rs

Unblocks https://github.com/rust-lang/rust/pull/83089

Remove trailing semicolon from macro expression

---

crates/core_arch/src/aarch64/prefetch.rs
crates/core_arch/src/aarch64/tme.rs
crates/core_arch/src/powerpc/vsx.rs
crates/core_arch/src/wasm32/memory.rs

Except for functions defined using `asm!`, which are ported in #1052.

Port all non-x86 uses of rustc_args_required_const to rustc_legacy_const_generics

---

crates/core_arch/src/aarch64/neon/mod.rs
crates/core_arch/src/arm/neon/mod.rs

add neon instruction vget_high_*
vget_high_* : 
Duplicate vector element to vector or scalar. This instruction duplicates the vector element at the specified element index in the source SIMD&FP register into a scalar or each element in a vector, and writes the result to the destination SIMD&FP register.

add neon instruction vget_high_*

---

crates/core_arch/src/aarch64/neon/mod.rs
crates/core_arch/src/arm/neon/mod.rs

recheck vget_high_p64 in arm (https://godbolt.org/z/KM6vEx) and fix this for #1074 
vget_low_* : Duplicate vector element to vector or scalar. This instruction duplicates the vector element at the specified element index in the source SIMD&FP register into a scalar or each element in a vector, and writes the result to the destination SIMD&FP register.

add neon instruction vget_low_* and fix vget_high_*

---

crates/core_arch/src/aarch64/neon/generated.rs
crates/core_arch/src/aarch64/neon/mod.rs
crates/core_arch/src/arm/neon/generated.rs
crates/stdarch-gen/neon.spec
crates/stdarch-gen/src/main.rs

Add vcvt, vcvta, vcvtn, vcvtm, vcvtp neon instructions(Floating-point convert to fixed-point with different rounding methods).

add vcvt, vcvta, vcvtn, vcvtm, vcvtp neon instructions

---

crates/core_arch/src/acle/barrier/cp15.rs
crates/core_arch/src/acle/hints.rs
crates/core_arch/src/acle/registers/mod.rs
crates/core_arch/src/arm/armclang.rs
crates/core_arch/src/lib.rs
crates/core_arch/src/macros.rs
crates/core_arch/src/x86/bt.rs
crates/core_arch/src/x86/cpuid.rs
crates/core_arch/src/x86/eflags.rs
crates/core_arch/src/x86_64/bt.rs
crates/std_detect/src/detect/os/aarch64.rs
crates/std_detect/src/lib.rs

Convert all uses of llvm_asm! to asm!

---

crates/core_arch/src/aarch64/neon/generated.rs
crates/core_arch/src/arm/neon/generated.rs
crates/stdarch-gen/neon.spec
crates/stdarch-gen/src/main.rs

1. Enhance code generator to support neon instructions with three parameters
2. Add vmla and vmls instructions to test 1
2. Enhance code generator to support suffix without 'q' ( which is useful for vmlal_high etc.)

Support three parameters in the code generator and add vmla and vmls instructions

---

crates/core_arch/src/aarch64/neon/mod.rs
crates/core_arch/src/arm/neon/mod.rs
crates/stdarch-verify/tests/arm.rs

add neon instruction vmov_n_* and vmovq_n_*
vmov_n_* : Duplicate vector element to vector or scalar. This instruction duplicates the vector element at the specified element index in the source SIMD&FP register into a scalar or each element in a vector, and writes the result to the destination SIMD&FP register. 
Without vmov_n_p64 and vmovq_n_p64 because they are not in arm-intrinsics.html(get missing arm definition in Automatic intrinsic verification).

add neon instruction vmov_n_* and vmovq_n_*

---

crates/core_arch/src/aarch64/neon/generated.rs
crates/core_arch/src/arm/neon/generated.rs
crates/stdarch-gen/neon.spec
crates/stdarch-gen/src/main.rs

1. Add multiply long, multiply-add long and multiply-subtract long neon instructions for int*, uint*, poly8
2. Support poly16 in code generator
3. Slightly enhance multi_fn to support more flexible syntax

Add vmull, vmull_high, vmlal, vmlal_high, vmlsl, vmlsl_high neon instructions

---

crates/core_arch/src/wasm32/atomic.rs

An error was introduced in #1073 in changing the atomic intrinsic to `memory.atomic.wait.iXX` instead of `memory.atomic.waitXX`.
See also the commit [902ea58 in the llvm project](https://github.com/llvm/llvm-project/commit/902ea588eab849e7254d3bc76abf32d833ac0dd6)
r? @alexcrichton

Fix WebAssembly Atomic intrinsic names

---

ci/docker/wasm32-wasi/Dockerfile
ci/run.sh
crates/core_arch/src/macros.rs
crates/core_arch/src/mod.rs
crates/core_arch/src/wasm32/atomic.rs
crates/core_arch/src/wasm32/memory.rs
crates/core_arch/src/wasm32/mod.rs
crates/core_arch/src/wasm32/simd128.rs

* Sync with the latest LLVM which has a few new intrinsic names
* Move explicit tests back to `assert_instr` since `assert_instr` now
supports specifying const-generic arguments inline.
* Enable tests where wasmtime implements the instruction as well as LLVM.
* Ensure there are tests for all functions that can be tested at this
time (those that aren't unimplemented in wasmtime).
There's still a number of `assert_instr` tests that are commented out.
These are either because they're unimplemented in wasmtime at the moment
or LLVM doesn't have an implementation for the instruction yet.

More wasm SIMD updates

---

crates/core_arch/src/aarch64/neon/generated.rs
crates/stdarch-gen/neon.spec
crates/stdarch-gen/src/main.rs

This PR adds transpose vectors and Zip vectors neon instructions which are only avaliable in aarch64.

add vtrn1 vtrn2, vzip1, vzip2 neon instructions

---

crates/core_arch/src/wasm32/simd128.rs
examples/hex.rs

The original intention of wasm SIMD support was to very closely match
the spec 1:1 to provide low-level primitives. Over time though this has
become less appealing and "niceties" such as `i64x2_shuffle` have been
added instead of only giving users `i8x16_shuffle` (same thing for
`*_const` functions).
This commit goes through and gives special treatment to all SIMD
intrinsics and instructions for wasm. This performs changes such as:
* All `*_u` and `*_s` suffixes are now baked into the intrinsic type,
e.g. changing `i16x8` to `u16x8` where appropriate.
* `*_const` functions have been added for unsigned types
* `*_replace_lane` functions have been added for unsigned types
* `*_extract_lane` functions have been added for unsigned types
While I think it makes sense at the wasm simd spec layer …

Tweak names of wasm SIMD intrinsics

---

crates/core_arch/src/aarch64/neon/generated.rs
crates/core_arch/src/arm/neon/generated.rs
crates/stdarch-gen/neon.spec

vabal_s*:
Signed Absolute difference and Accumulate Long. This instruction subtracts the vector elements in the lower or upper half of the second source SIMD&FP register from the corresponding vector elements of the first source SIMD&FP register, and accumulates the absolute values of the results into the vector elements of the destination SIMD&FP register. The destination vector elements are twice as long as the source vector elements.
vabal_u*:
Unsigned Absolute difference and Accumulate Long. This instruction subtracts the vector elements in the lower or upper half of the second source SIMD&FP register from the corresponding vector elements of the first source SIMD&FP register, and accumulates the absolute values of the results into the vector elements of the destination SIMD&FP …

support for neon instructions vabal_* and vabal_high_*

---

crates/core_arch/src/aarch64/neon/generated.rs
crates/core_arch/src/arm/neon/generated.rs
crates/core_arch/src/simd_llvm.rs
crates/stdarch-gen/neon.spec

This PR adds simd_neg intrinsic  and vneg neon instructions since the compiler already did corresponding supports.

add simd_neg platform intrinsic and vneg, vqneg neon instructions

---

crates/core_arch/src/aarch64/neon/generated.rs
crates/core_arch/src/arm/neon/generated.rs
crates/stdarch-gen/neon.spec

vabdl_*:
Absolute Difference Long. This instruction subtracts the vector elements of the second source SIMD&FP register from the corresponding vector elements of the first source SIMD&FP register, places the absolute value of the results into a vector, and writes the vector to the lower or upper half of the destination SIMD&FP register. The destination vector elements are twice as long as the source vector elements.

support neon instruction vabdl_* and vabdl_high_*

---

crates/core_arch/src/aarch64/neon/generated.rs
crates/core_arch/src/arm/neon/generated.rs
crates/core_arch/src/arm/neon/mod.rs
crates/stdarch-gen/neon.spec
crates/stdarch-gen/src/main.rs
crates/stdarch-verify/tests/arm.rs

This PR add vreinterpret(Vector reinterpret cast operation) neon instructions.
Some modifications have been made to the code generator in order to generate the correct suffixes.
A few intrinsics are present in GCC and Clang but are missing from the official documentation.
The Github comparison program looks wrong. This PR does not make any changes to existing intructions. (Look neon.spec)

add vreinterpret neon instructions

---

crates/core_arch/src/aarch64/neon/generated.rs
crates/core_arch/src/arm/neon/generated.rs
crates/stdarch-gen/neon.spec

vqabs_* : Signed saturating Absolute value. This instruction reads each vector element from the source SIMD&FP register, puts the absolute value of the result into a vector, and writes the vector to the destination SIMD&FP register. All the values in this instruction are signed integer values.

add support for neon instruction vqabs_*

---

crates/core_arch/src/aarch64/neon/generated.rs
crates/core_arch/src/arm/neon/generated.rs
crates/core_arch/src/arm/neon/mod.rs
crates/stdarch-gen/neon.spec
crates/stdarch-gen/src/main.rs

1. Add vmovn_high, vrbit, vrnd, vsubhn neon instructions using code generator
2. Complete the vrev instruction in arm/neon/mod.rs
3. Enhanced code generator to generate more flexible link_name

add vmovn_high, vrbit, vrnd, vsubhn neon instructions

---

crates/core_arch/src/aarch64/neon/generated.rs
crates/core_arch/src/aarch64/neon/mod.rs
crates/core_arch/src/arm/neon/generated.rs
crates/core_arch/src/arm/neon/mod.rs
crates/stdarch-gen/neon.spec
crates/stdarch-gen/src/main.rs

1. Enhanced code generator to enable constant parameters.
2. Add vext neon instructions to test 1.

Enable constant parameters in the code generator and add vext instructions

---

crates/core_arch/src/aarch64/neon/generated.rs
crates/core_arch/src/arm/neon/generated.rs
crates/stdarch-gen/neon.spec
crates/stdarch-gen/src/main.rs

vmaxnm_f* :  Floating-point Maximum Number (vector). This instruction compares corresponding vector elements in the two source SIMD&FP registers, writes the larger of the two floating-point values into a vector, and writes the vector to the destination SIMD&FP register.
vpmaxnm_f* :  Floating-point Maximum Number Pairwise (vector). This instruction creates a vector by concatenating the vector elements of the first source SIMD&FP register after the vector elements of the second source SIMD&FP register, reads each pair of adjacent vector elements in the two source SIMD&FP registers, writes the largest of each pair of values into a vector, and writes the vector to the destination SIMD&FP register. All the values in this instruction are floating-point values.
vminnm_f* :  Floating-point …

add neon instruction vmaxnm_f* vpmaxnm_f* vminnm_f* vpminnm_f*

---

crates/assert-instr-macro/src/lib.rs
crates/core_arch/src/lib.rs
crates/core_arch/src/x86/avx512vpclmulqdq.rs
crates/core_arch/src/x86/fxsr.rs
crates/core_arch/src/x86/pclmulqdq.rs
crates/core_arch/src/x86/xsave.rs
crates/core_arch/src/x86_64/fxsr.rs
crates/core_arch/src/x86_64/xsave.rs
crates/simd-test-macro/src/lib.rs
crates/std_detect/src/detect/os/linux/cpuinfo.rs
crates/std_detect/src/lib.rs
crates/stdarch-test/src/lib.rs
crates/stdarch-verify/src/lib.rs

```
error: hidden lifetime parameters in types are deprecated
--> library/stdarch/crates/std_detect/src/detect/os/linux/cpuinfo.rs:20:48
|
20 |     pub(crate) fn field(&self, field: &str) -> CpuInfoField {
|                                                ^^^^^^^^^^^^- help: indicate the anonymous lifetime: `<'_>`
|
= note: `-D elided-lifetimes-in-paths` implied by `-D warnings`
```
This lint is allow by default, which is why this wasn't spotted earlier.
cc https://github.com/rust-lang/rust/pull/83776#issuecomment-813332275

Deny 2018 idiom lints

---

ci/docker/wasm32-wasi/Dockerfile
crates/core_arch/src/wasm32/simd128.rs

* Uncomment some i64-related instruction assertions now that LLVM
supports the opcodes.
* Fix the codegen for `{i,u}32x4_trunc_sat_f32x4`. This was originally
introduced using `simd_cast` but that inherits LLVM's UB related to
float-to-integer casts out of bounds. Since the original inception of
these intrinsics in LLVM dedicated intrinsics for the wasm
instructions have been added, so this swithces the implementation to
using those.
* Uncomment `f64x2_convert_low_i32x4` instruction assertion and add a
test now that this is implemented in Wasmtime.

Updates for wasm simd support

---

crates/core_arch/src/aarch64/neon/generated.rs
crates/core_arch/src/arm/neon/generated.rs
crates/stdarch-gen/neon.spec

vsubw_s*  vsubw_high_s* : Signed Subtract Wide. This instruction subtracts each vector element in the lower or upper half of the second source SIMD&FP register from the corresponding vector element in the first source SIMD&FP register, places the result in a vector, and writes the vector to the SIMD&FP destination register. All the values in this instruction are signed integer values.
vsubw_u*  vsubw_high_u* : Unsigned Subtract Wide. This instruction subtracts each vector element of the second source SIMD&FP register from the corresponding vector element in the lower or upper half of the first source SIMD&FP register, places the result in a vector, and writes the vector to the SIMD&FP destination register. All the values in this instruction are signed integer values.
vsubl_s* …

add neon instruction vsubw_* and vsubl_*

---

crates/core_arch/src/aarch64/neon/generated.rs
crates/core_arch/src/arm/neon/generated.rs
crates/core_arch/src/arm/neon/mod.rs
crates/stdarch-gen/neon.spec
crates/stdarch-gen/src/main.rs

This PR adds vshl, vshl_n, vshll, vshll_high, vshr_n, vshrn, vshrn_high neon instructions.
It makes some modifications to the code generator to generate the correct suffixes.

add vshl and vshr neon instructions

---

crates/assert-instr-macro/Cargo.toml
crates/assert-instr-macro/src/lib.rs
crates/simd-test-macro/Cargo.toml
crates/simd-test-macro/src/lib.rs
crates/stdarch-test/Cargo.toml
crates/stdarch-test/src/lib.rs

Builds on https://github.com/rust-lang/stdarch/pull/1108.

Convert all crates to 2018 edition

---

crates/core_arch/src/aarch64/neon/generated.rs
crates/core_arch/src/arm/neon/generated.rs
crates/stdarch-gen/neon.spec
crates/stdarch-gen/src/main.rs
crates/stdarch-test/src/lib.rs

1. Enhance the code generator so that primitive types can be used
2. Enhance code generator to generate more flexible suffixes
3. Add vdup neon instructions to test 1 and 2.

Allow primitive types in the code generator and add vdup instructions

---

crates/core_arch/src/aarch64/neon/mod.rs
crates/core_arch/src/arm/neon/mod.rs
crates/core_arch/src/lib.rs
crates/stdarch-verify/tests/arm.rs

This breaks when core_arch is included as a module in core.

Don't import from core

---

crates/core_arch/src/x86/sse.rs

Just something I noticed in passing in the docs.

Typo fix: fist -> first

---

crates/core_arch/src/aarch64/neon/generated.rs
crates/stdarch-gen/neon.spec
crates/stdarch-gen/src/main.rs

Add support for `uzp1` and `uzp2` intrinsics (AArch64 Neon).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rust-lang/stdarch/1118)

aarch64: add uzp1, uzp2 instructions

---

crates/core_arch/src/aarch64/neon/generated.rs
crates/core_arch/src/arm/neon/generated.rs
crates/stdarch-gen/neon.spec
crates/stdarch-gen/src/main.rs

This PR adds vqrshl*, vqrshrn*, vqrshrun* neon instructions.
When using llvm interfaces with const generics, arm and aarch64 will have different implementations, so the code generator  is enhanced accordingly to generate the required code format.

Add vqrsh* neon instructions

---

crates/core_arch/src/aarch64/neon/generated.rs
crates/core_arch/src/aarch64/neon/mod.rs
crates/stdarch-gen/neon.spec

vaddlv_* : Signed|Unsigned Add Long across Vector. This instruction adds every vector element in the source SIMD&FP register together, and writes the scalar result to the destination SIMD&FP register. The destination scalar is twice as long as the source vector elements. All the values in this instruction are signed integer values.

add neon instruction vaddlv_*

---

crates/core_arch/src/aarch64/neon/generated.rs
crates/core_arch/src/arm_shared/neon/generated.rs
crates/stdarch-gen/neon.spec
crates/stdarch-gen/src/main.rs

1. Add vqdmull, vqdmlal, vqdmlsl, vqdmulh neon instructions.
2. Correct the links of vqadd and vqsub to be consistent with Clang.

Add vqdmul* neon instructions

---

crates/core_arch/src/aarch64/neon/generated.rs
crates/core_arch/src/arm_shared/neon/generated.rs
crates/stdarch-gen/neon.spec

This adds the neon instructions for lane-wise rounding without actually converting the lanes to integers.

Add vrndn neon instructions

---

crates/std_detect/src/lib.rs

This does not seem to be needed any more (and the feature is about to be removed and replaced by more fine-grained features).

remove unused const_fn feature

---

crates/core_arch/src/aarch64/neon/generated.rs
crates/core_arch/src/aarch64/neon/mod.rs
crates/stdarch-gen/neon.spec
crates/stdarch-gen/src/main.rs

This PR adds vcopy neon instructions which are only available on aarch64

add vcopy neon instructions

---

crates/stdarch-verify/tests/mips.rs

I'm working on `try_trait_v2` which will break this, so I'm going around removing uses from the rustc tree where I can.
(Diff easier to [read in ignore-whitespace mode](https://github.com/rust-lang/stdarch/pull/1142/files?w=1), as I added an indent.)

Remove `#![feature(try_trait)]` from a test

---

crates/core_arch/src/aarch64/neon/generated.rs
crates/core_arch/src/aarch64/neon/mod.rs
crates/core_arch/src/arm_shared/neon/generated.rs
crates/stdarch-gen/neon.spec
crates/stdarch-gen/src/main.rs

This PR completes the vmul and vmulx instructions

Add vmul_n, vmul_lane, vmulx neon instructions

---

crates/core_arch/src/wasm32/simd128.rs

This round is dependant on
https://github.com/rust-lang/llvm-project/pull/101 landing first in
rust-lang/rust and won't pass CI until that does. That PR, however, will
also break wasm CI because it's changing how the wasm target works. My
goal here is to open this early to get it out there so that when that PR
lands in rust-lang/rust and CI breaks in stdarch then this can be merged
to make CI green again.
The changes here are mostly around the codegen for various intrinsics.
Some wasm-specific intrinsics have been removed in favor of more general
LLVM intrinsics, and other intrinsics have been removed in favor of
pattern-matching codegen.
The only new instruction supported as part of this chagne is
`v128.any_true`. This leaves only one instruction unsupported in LLVM
which is `i64x2.abs`. …

Another round of wasm SIMD updates

---

crates/core_arch/src/mod.rs

The cfg is not needed after bumping the bootstrap compiler.

Remove cfg(not(bootstrap)) for 1.54

---

crates/core_arch/src/lib.rs

The `const_fn` feature is dead, it does not do anything any more and we'd like to remove it.

remove const_fn leftovers
